// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: networksecurity.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.networksecurity.v1alpha1
// resource: NetworkSecurityPartnerSSERealm:PartnerSSERealm
// resource: NetworkSecurityPartnerSSEGateway:PartnerSSEGateway
// resource: NetworkSecurityTLSInspectionPolicy:TlsInspectionPolicy

package v1alpha1

/* unreachable type PartnerSseGateway
// +kcc:proto=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway
type PartnerSseGateway struct {
	// Immutable. name of resource
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.name
	Name *string `json:"name,omitempty"`

	// Optional. Labels as key value pairs
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.labels
	Labels map[string]string `json:"labels,omitempty"`

	// Required. ID of the SSEGatewayReference that pairs with this
	//  PartnerSSEGateway
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_gateway_reference_id
	// +required
	SseGatewayReferenceID *string `json:"sseGatewayReferenceID,omitempty"`

	// Optional. Subnet range of the partner_vpc
	//  This field is deprecated. Use partner_subnet_range instead.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.partner_vpc_subnet_range
	PartnerVPCSubnetRange *string `json:"partnerVPCSubnetRange,omitempty"`

	// Optional. Subnet range where SSE GW instances are deployed.
	//  Default value is set to "100.88.255.0/24".
	//  The CIDR suffix should be less than or equal to 25.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_subnet_range
	SseSubnetRange *string `json:"sseSubnetRange,omitempty"`

	// Optional. Subnet range of the partner-owned subnet.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.partner_subnet_range
	PartnerSubnetRange *string `json:"partnerSubnetRange,omitempty"`

	// Optional. Virtual Network Identifier to use in NCG.
	//  Today the only partner that depends on it is Symantec.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.vni
	Vni *int32 `json:"vni,omitempty"`

	// Optional. Required iff Partner is Symantec.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.symantec_options
	SymantecOptions *PartnerSseGateway_PartnerSseGatewaySymantecOptions `json:"symantecOptions,omitempty"`
}
*/

// +kcc:proto=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.PartnerSSEGatewaySymantecOptions
type PartnerSseGateway_PartnerSseGatewaySymantecOptions struct {

	// Optional. Target for the NCGs to send traffic to on the Symantec side.
	//  Only supports IP address today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.PartnerSSEGatewaySymantecOptions.symantec_site_target_host
	SymantecSiteTargetHost *string `json:"symantecSiteTargetHost,omitempty"`
}

/* unreachable type PartnerSseRealm
// +kcc:proto=google.cloud.networksecurity.v1alpha1.PartnerSSERealm
type PartnerSseRealm struct {
	// name of resource
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.name
	Name *string `json:"name,omitempty"`

	// Labels as key value pairs
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.labels
	Labels map[string]string `json:"labels,omitempty"`

	// Required. value of the key to establish global handshake from SSERealm
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.pairing_key
	// +required
	PairingKey *string `json:"pairingKey,omitempty"`

	// Optional. VPC owned by the partner to be peered with CDEN sse_vpc in
	//  sse_project This field is deprecated. Use partner_network instead.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.partner_vpc
	PartnerVPC *string `json:"partnerVPC,omitempty"`

	// Optional. Partner-owned network to be peered with CDEN's sse_network in
	//  sse_project
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.partner_network
	PartnerNetwork *string `json:"partnerNetwork,omitempty"`

	// Optional. Required only for PAN.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.pan_options
	PanOptions *PartnerSseRealm_PartnerSseRealmPanOptions `json:"panOptions,omitempty"`
}
*/

// +kcc:proto=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.PartnerSSERealmPanOptions
type PartnerSseRealm_PartnerSseRealmPanOptions struct {
	// Optional. serial_number is provided by PAN to identify GCP customer on
	//  PAN side.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.PartnerSSERealmPanOptions.serial_number
	SerialNumber *string `json:"serialNumber,omitempty"`

	// Optional. tenant_id is provided by PAN to identify GCP customer on PAN
	//  side.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.PartnerSSERealmPanOptions.tenant_id
	TenantID *string `json:"tenantID,omitempty"`
}

/* unreachable type TLSInspectionPolicy
// +kcc:proto=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy
type TLSInspectionPolicy struct {
	// Required. Name of the resource. Name is of the form
	//  projects/{project}/locations/{location}/tlsInspectionPolicies/{tls_inspection_policy}
	//  tls_inspection_policy should match the
	//  pattern:(^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$).
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.name
	// +required
	Name *string `json:"name,omitempty"`

	// Optional. Free-text description of the resource.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.description
	Description *string `json:"description,omitempty"`

	// Required. A CA pool resource used to issue interception certificates.
	//  The CA pool string has a relative resource path following the form
	//  "projects/{project}/locations/{location}/caPools/{ca_pool}".
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.ca_pool
	// +required
	CAPool *string `json:"caPool,omitempty"`

	// Optional. A TrustConfig resource used when making a connection to the TLS
	//  server. This is a relative resource path following the form
	//  "projects/{project}/locations/{location}/trustConfigs/{trust_config}". This
	//  is necessary to intercept TLS connections to servers with certificates
	//  signed by a private CA or self-signed certificates.
	//  Note that Secure Web Proxy does not yet honor this field.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.trust_config
	TrustConfig *string `json:"trustConfig,omitempty"`

	// Optional. If  FALSE (the default), use our default set of public CAs in
	//  addition to any CAs specified in trust_config. These public CAs are
	//  currently based on the Mozilla Root Program and are subject to change over
	//  time. If TRUE, do not accept our default set of public CAs. Only CAs
	//  specified in trust_config will be accepted. This defaults to FALSE (use
	//  public CAs in addition to trust_config) for backwards compatibility, but
	//  trusting public root CAs is *not recommended* unless the traffic in
	//  question is outbound to public web servers. When possible, prefer setting
	//  this to "false" and explicitly specifying trusted CAs and certificates in a
	//  TrustConfig. Note that Secure Web Proxy does not yet honor this field.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.exclude_public_ca_set
	ExcludePublicCASet *bool `json:"excludePublicCASet,omitempty"`

	// Optional. Minimum TLS version that the firewall should use when negotiating
	//  connections with both clients and servers. If this is not set, then the
	//  default value is to allow the broadest set of clients and servers (TLS 1.0
	//  or higher). Setting this to more restrictive values may improve security,
	//  but may also prevent the firewall from connecting to some clients or
	//  servers.
	//  Note that Secure Web Proxy does not yet honor this field.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.min_tls_version
	MinTLSVersion *string `json:"minTLSVersion,omitempty"`

	// Optional. The selected Profile. If this is not set, then the default value
	//  is to allow the broadest set of clients and servers ("PROFILE_COMPATIBLE").
	//  Setting this to more restrictive values may improve security, but may also
	//  prevent the TLS inspection proxy from connecting to some clients or
	//  servers. Note that Secure Web Proxy does not yet honor this field.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.tls_feature_profile
	TLSFeatureProfile *string `json:"tlsFeatureProfile,omitempty"`

	// Optional. List of custom TLS cipher suites selected.
	//  This field is valid only if the selected tls_feature_profile is CUSTOM.
	//  The [compute.SslPoliciesService.ListAvailableFeatures][] method returns the
	//  set of features that can be specified in this list.
	//  Note that Secure Web Proxy does not yet honor this field.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.custom_tls_features
	CustomTLSFeatures []string `json:"customTLSFeatures,omitempty"`
}
*/

/* unreachable type PartnerSseGatewayObservedState
// +kcc:observedstate:proto=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway
type PartnerSseGatewayObservedState struct {
	// Output only. Create time stamp
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. Update time stamp
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.update_time
	UpdateTime *string `json:"updateTime,omitempty"`

	// Output only. Subnet range of the subnet where partner traffic is routed.
	//  This field is deprecated. Use sse_subnet_range instead.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_vpc_subnet_range
	SseVPCSubnetRange *string `json:"sseVPCSubnetRange,omitempty"`

	// Output only. This is the IP where the partner traffic should be routed to.
	//  This field is deprecated. Use sse_target_ip instead.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_vpc_target_ip
	SseVPCTargetIP *string `json:"sseVPCTargetIP,omitempty"`

	// Output only. IP of SSE BGP
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_bgp_ips
	SseBGPIps []string `json:"sseBGPIps,omitempty"`

	// Output only. ASN of SSE BGP
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_bgp_asn
	SseBGPAsn *int32 `json:"sseBGPAsn,omitempty"`

	// Output only. name of PartnerSSERealm owning the PartnerSSEGateway
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.partner_sse_realm
	PartnerSseRealm *string `json:"partnerSseRealm,omitempty"`

	// Output only. Target IP that belongs to sse_subnet_range where partner
	//  should send the traffic to reach the customer networks.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_target_ip
	SseTargetIP *string `json:"sseTargetIP,omitempty"`

	// Optional. Required iff Partner is Symantec.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.symantec_options
	SymantecOptions *PartnerSseGateway_PartnerSseGatewaySymantecOptionsObservedState `json:"symantecOptions,omitempty"`

	// Output only. The project owning partner_facing_network. Only filled for
	//  PartnerSSEGateways associated with Symantec today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_project
	SseProject *string `json:"sseProject,omitempty"`

	// Output only. The ID of the network in sse_project containing
	//  sse_subnet_range. This is also known as the partnerFacingNetwork. Only
	//  filled for PartnerSSEGateways associated with Symantec today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.sse_network
	SseNetwork *string `json:"sseNetwork,omitempty"`

	// Output only. Full URI of the partner environment this PartnerSSEGateway is
	//  connected to. Filled from the customer SSEGateway, and only for
	//  PartnerSSEGateways associated with Symantec today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.partner_sse_environment
	PartnerSseEnvironment *string `json:"partnerSseEnvironment,omitempty"`

	// Output only. ISO-3166 alpha 2 country code used for localization.
	//  Filled from the customer SSEGateway, and only for PartnerSSEGateways
	//  associated with Symantec today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.country
	Country *string `json:"country,omitempty"`

	// Output only. tzinfo identifier used for localization.
	//  Filled from the customer SSEGateway, and only for PartnerSSEGateways
	//  associated with Symantec today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.timezone
	Timezone *string `json:"timezone,omitempty"`

	// Output only. Copied from the associated NCC resource in Symantec NCCGW
	//  flows. Used by Symantec API.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.capacity_bps
	CapacityBps *int64 `json:"capacityBps,omitempty"`

	// Output only. State of the gateway.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.state
	State *string `json:"state,omitempty"`

	// Output only. Subnet ranges for Google-issued probe packets.
	//  It's populated only for Prisma Access partners.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.prober_subnet_ranges
	ProberSubnetRanges []string `json:"proberSubnetRanges,omitempty"`
}
*/

// +kcc:observedstate:proto=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.PartnerSSEGatewaySymantecOptions
type PartnerSseGateway_PartnerSseGatewaySymantecOptionsObservedState struct {
	// Output only. UUID of the Symantec Location created on the customer's
	//  behalf.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.PartnerSSEGatewaySymantecOptions.symantec_location_uuid
	SymantecLocationUuid *string `json:"symantecLocationUuid,omitempty"`

	// Output only. Symantec data center identifier that this SSEGW will connect
	//  to. Filled from the customer SSEGateway, and only for PartnerSSEGateways
	//  associated with Symantec today.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSEGateway.PartnerSSEGatewaySymantecOptions.symantec_site
	SymantecSite *string `json:"symantecSite,omitempty"`
}

/* unreachable type PartnerSseRealmObservedState
// +kcc:observedstate:proto=google.cloud.networksecurity.v1alpha1.PartnerSSERealm
type PartnerSseRealmObservedState struct {
	// Output only. Create time stamp
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. Update time stamp
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.update_time
	UpdateTime *string `json:"updateTime,omitempty"`

	// Output only. CDEN owned VPC to be peered with partner_vpc
	//  This field is deprecated. Use sse_network instead.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.sse_vpc
	SseVPC *string `json:"sseVPC,omitempty"`

	// Output only. CDEN owned project owning sse_vpc. It stores project id in the
	//  TTM flow, but project number in the NCCGW flow. This field will be
	//  deprecated after the partner migrates from using sse_project to using
	//  sse_project_number.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.sse_project
	SseProject *string `json:"sseProject,omitempty"`

	// Output only. State of the realm. It can be either CUSTOMER_ATTACHED or
	//  CUSTOMER_DETACHED.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.state
	State *string `json:"state,omitempty"`

	// Output only. CDEN-owned network to be peered with partner_network
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.sse_network
	SseNetwork *string `json:"sseNetwork,omitempty"`

	// Output only. CDEN owned project owning sse_vpc
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.PartnerSSERealm.sse_project_number
	SseProjectNumber *int64 `json:"sseProjectNumber,omitempty"`
}
*/

/* unreachable type TLSInspectionPolicyObservedState
// +kcc:observedstate:proto=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy
type TLSInspectionPolicyObservedState struct {
	// Output only. The timestamp when the resource was created.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. The timestamp when the resource was updated.
	// +kcc:proto:field=google.cloud.networksecurity.v1alpha1.TlsInspectionPolicy.update_time
	UpdateTime *string `json:"updateTime,omitempty"`
}
*/
