// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var NotebooksExecutionGVK = GroupVersion.WithKind("NotebooksExecution")

// NotebooksExecutionSpec defines the desired state of NotebooksExecution
// +kcc:spec:proto=google.cloud.notebooks.v1.Execution
type NotebooksExecutionSpec struct {
	// The project that this resource belongs to.
	ProjectRef *refsv1beta1.ProjectRef `json:"projectRef"`

	// The Location that this resource belongs to.
	// +kcc:guess=parent-segment pattern=projects/{project}/location/{location}/executions/{execution}
	Location *string `json:"location,omitempty"`

	// The NotebooksExecution name. If not given, the metadata.name will be used.
	ResourceID *string `json:"resourceID,omitempty"`
	// execute metadata including name, hardware spec, region, labels, etc.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.execution_template
	ExecutionTemplate *ExecutionTemplate `json:"executionTemplate,omitempty"`

	// A brief description of this execution.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.description
	Description *string `json:"description,omitempty"`

	// Output notebook file generated by this execution
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.output_notebook_file
	OutputNotebookFile *string `json:"outputNotebookFile,omitempty"`
}

// NotebooksExecutionStatus defines the config connector machine state of NotebooksExecution
type NotebooksExecutionStatus struct {
	/* Conditions represent the latest available observations of the
	   object's current state. */
	Conditions []v1alpha1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// A unique specifier for the NotebooksExecution resource in GCP.
	ExternalRef *string `json:"externalRef,omitempty"`

	// ObservedState is the state of the resource as most recently observed in GCP.
	ObservedState *NotebooksExecutionObservedState `json:"observedState,omitempty"`
}

// NotebooksExecutionObservedState is the state of the NotebooksExecution resource as most recently observed in GCP.
// +kcc:observedstate:proto=google.cloud.notebooks.v1.Execution
type NotebooksExecutionObservedState struct {
	// Output only. Name used for UI purposes.
	//  Name can only contain alphanumeric characters and underscores '_'.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.display_name
	DisplayName *string `json:"displayName,omitempty"`

	// Output only. Time the Execution was instantiated.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. Time the Execution was last updated.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.update_time
	UpdateTime *string `json:"updateTime,omitempty"`

	// Output only. State of the underlying AI Platform job.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.state
	State *string `json:"state,omitempty"`

	// Output only. The URI of the external job used to execute the notebook.
	// +kcc:proto:field=google.cloud.notebooks.v1.Execution.job_uri
	JobURI *string `json:"jobURI,omitempty"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:categories=gcp,shortName=gcpnotebooksexecution;gcpnotebooksexecutions
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/managed-by-kcc=true"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/system=true"
// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type="date"
// +kubebuilder:printcolumn:name="Ready",JSONPath=".status.conditions[?(@.type=='Ready')].status",type="string",description="When 'True', the most recent reconcile of the resource succeeded"
// +kubebuilder:printcolumn:name="Status",JSONPath=".status.conditions[?(@.type=='Ready')].reason",type="string",description="The reason for the value in 'Ready'"
// +kubebuilder:printcolumn:name="Status Age",JSONPath=".status.conditions[?(@.type=='Ready')].lastTransitionTime",type="date",description="The last transition time for the value in 'Status'"

// NotebooksExecution is the Schema for the NotebooksExecution API
// +k8s:openapi-gen=true
type NotebooksExecution struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +required
	Spec   NotebooksExecutionSpec   `json:"spec,omitempty"`
	Status NotebooksExecutionStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// NotebooksExecutionList contains a list of NotebooksExecution
type NotebooksExecutionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NotebooksExecution `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NotebooksExecution{}, &NotebooksExecutionList{})
}
