//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	k8sv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerImage) DeepCopyInto(out *ContainerImage) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerImage.
func (in *ContainerImage) DeepCopy() *ContainerImage {
	if in == nil {
		return nil
	}
	out := new(ContainerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentRef) DeepCopyInto(out *EnvironmentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentRef.
func (in *EnvironmentRef) DeepCopy() *EnvironmentRef {
	if in == nil {
		return nil
	}
	out := new(EnvironmentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionObservedState) DeepCopyInto(out *ExecutionObservedState) {
	*out = *in
	if in.ExecutionTemplate != nil {
		in, out := &in.ExecutionTemplate, &out.ExecutionTemplate
		*out = new(ExecutionTemplateObservedState)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.OutputNotebookFile != nil {
		in, out := &in.OutputNotebookFile, &out.OutputNotebookFile
		*out = new(string)
		**out = **in
	}
	if in.JobURI != nil {
		in, out := &in.JobURI, &out.JobURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionObservedState.
func (in *ExecutionObservedState) DeepCopy() *ExecutionObservedState {
	if in == nil {
		return nil
	}
	out := new(ExecutionObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionTemplate) DeepCopyInto(out *ExecutionTemplate) {
	*out = *in
	if in.ScaleTier != nil {
		in, out := &in.ScaleTier, &out.ScaleTier
		*out = new(string)
		**out = **in
	}
	if in.MasterType != nil {
		in, out := &in.MasterType, &out.MasterType
		*out = new(string)
		**out = **in
	}
	if in.AcceleratorConfig != nil {
		in, out := &in.AcceleratorConfig, &out.AcceleratorConfig
		*out = new(ExecutionTemplate_SchedulerAcceleratorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InputNotebookFile != nil {
		in, out := &in.InputNotebookFile, &out.InputNotebookFile
		*out = new(string)
		**out = **in
	}
	if in.ContainerImageURI != nil {
		in, out := &in.ContainerImageURI, &out.ContainerImageURI
		*out = new(string)
		**out = **in
	}
	if in.OutputNotebookFolder != nil {
		in, out := &in.OutputNotebookFolder, &out.OutputNotebookFolder
		*out = new(string)
		**out = **in
	}
	if in.ParamsYamlFile != nil {
		in, out := &in.ParamsYamlFile, &out.ParamsYamlFile
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.JobType != nil {
		in, out := &in.JobType, &out.JobType
		*out = new(string)
		**out = **in
	}
	if in.DataprocParameters != nil {
		in, out := &in.DataprocParameters, &out.DataprocParameters
		*out = new(ExecutionTemplate_DataprocParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VertexAiParameters != nil {
		in, out := &in.VertexAiParameters, &out.VertexAiParameters
		*out = new(ExecutionTemplate_VertexAiParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelSpec != nil {
		in, out := &in.KernelSpec, &out.KernelSpec
		*out = new(string)
		**out = **in
	}
	if in.Tensorboard != nil {
		in, out := &in.Tensorboard, &out.Tensorboard
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionTemplate.
func (in *ExecutionTemplate) DeepCopy() *ExecutionTemplate {
	if in == nil {
		return nil
	}
	out := new(ExecutionTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionTemplateObservedState) DeepCopyInto(out *ExecutionTemplateObservedState) {
	*out = *in
	if in.ScaleTier != nil {
		in, out := &in.ScaleTier, &out.ScaleTier
		*out = new(string)
		**out = **in
	}
	if in.MasterType != nil {
		in, out := &in.MasterType, &out.MasterType
		*out = new(string)
		**out = **in
	}
	if in.AcceleratorConfig != nil {
		in, out := &in.AcceleratorConfig, &out.AcceleratorConfig
		*out = new(ExecutionTemplate_SchedulerAcceleratorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InputNotebookFile != nil {
		in, out := &in.InputNotebookFile, &out.InputNotebookFile
		*out = new(string)
		**out = **in
	}
	if in.ContainerImageURI != nil {
		in, out := &in.ContainerImageURI, &out.ContainerImageURI
		*out = new(string)
		**out = **in
	}
	if in.OutputNotebookFolder != nil {
		in, out := &in.OutputNotebookFolder, &out.OutputNotebookFolder
		*out = new(string)
		**out = **in
	}
	if in.ParamsYamlFile != nil {
		in, out := &in.ParamsYamlFile, &out.ParamsYamlFile
		*out = new(string)
		**out = **in
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.JobType != nil {
		in, out := &in.JobType, &out.JobType
		*out = new(string)
		**out = **in
	}
	if in.DataprocParameters != nil {
		in, out := &in.DataprocParameters, &out.DataprocParameters
		*out = new(ExecutionTemplate_DataprocParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.VertexAiParameters != nil {
		in, out := &in.VertexAiParameters, &out.VertexAiParameters
		*out = new(ExecutionTemplate_VertexAiParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelSpec != nil {
		in, out := &in.KernelSpec, &out.KernelSpec
		*out = new(string)
		**out = **in
	}
	if in.Tensorboard != nil {
		in, out := &in.Tensorboard, &out.Tensorboard
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionTemplateObservedState.
func (in *ExecutionTemplateObservedState) DeepCopy() *ExecutionTemplateObservedState {
	if in == nil {
		return nil
	}
	out := new(ExecutionTemplateObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionTemplate_DataprocParameters) DeepCopyInto(out *ExecutionTemplate_DataprocParameters) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionTemplate_DataprocParameters.
func (in *ExecutionTemplate_DataprocParameters) DeepCopy() *ExecutionTemplate_DataprocParameters {
	if in == nil {
		return nil
	}
	out := new(ExecutionTemplate_DataprocParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionTemplate_SchedulerAcceleratorConfig) DeepCopyInto(out *ExecutionTemplate_SchedulerAcceleratorConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.CoreCount != nil {
		in, out := &in.CoreCount, &out.CoreCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionTemplate_SchedulerAcceleratorConfig.
func (in *ExecutionTemplate_SchedulerAcceleratorConfig) DeepCopy() *ExecutionTemplate_SchedulerAcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(ExecutionTemplate_SchedulerAcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionTemplate_VertexAiParameters) DeepCopyInto(out *ExecutionTemplate_VertexAiParameters) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionTemplate_VertexAiParameters.
func (in *ExecutionTemplate_VertexAiParameters) DeepCopy() *ExecutionTemplate_VertexAiParameters {
	if in == nil {
		return nil
	}
	out := new(ExecutionTemplate_VertexAiParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance_AcceleratorConfig) DeepCopyInto(out *Instance_AcceleratorConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.CoreCount != nil {
		in, out := &in.CoreCount, &out.CoreCount
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance_AcceleratorConfig.
func (in *Instance_AcceleratorConfig) DeepCopy() *Instance_AcceleratorConfig {
	if in == nil {
		return nil
	}
	out := new(Instance_AcceleratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance_Disk) DeepCopyInto(out *Instance_Disk) {
	*out = *in
	if in.AutoDelete != nil {
		in, out := &in.AutoDelete, &out.AutoDelete
		*out = new(bool)
		**out = **in
	}
	if in.Boot != nil {
		in, out := &in.Boot, &out.Boot
		*out = new(bool)
		**out = **in
	}
	if in.DeviceName != nil {
		in, out := &in.DeviceName, &out.DeviceName
		*out = new(string)
		**out = **in
	}
	if in.DiskSizeGB != nil {
		in, out := &in.DiskSizeGB, &out.DiskSizeGB
		*out = new(int64)
		**out = **in
	}
	if in.GuestOSFeatures != nil {
		in, out := &in.GuestOSFeatures, &out.GuestOSFeatures
		*out = make([]Instance_Disk_GuestOSFeature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(int64)
		**out = **in
	}
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Licenses != nil {
		in, out := &in.Licenses, &out.Licenses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance_Disk.
func (in *Instance_Disk) DeepCopy() *Instance_Disk {
	if in == nil {
		return nil
	}
	out := new(Instance_Disk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance_Disk_GuestOSFeature) DeepCopyInto(out *Instance_Disk_GuestOSFeature) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance_Disk_GuestOSFeature.
func (in *Instance_Disk_GuestOSFeature) DeepCopy() *Instance_Disk_GuestOSFeature {
	if in == nil {
		return nil
	}
	out := new(Instance_Disk_GuestOSFeature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance_ShieldedInstanceConfig) DeepCopyInto(out *Instance_ShieldedInstanceConfig) {
	*out = *in
	if in.EnableSecureBoot != nil {
		in, out := &in.EnableSecureBoot, &out.EnableSecureBoot
		*out = new(bool)
		**out = **in
	}
	if in.EnableVTPM != nil {
		in, out := &in.EnableVTPM, &out.EnableVTPM
		*out = new(bool)
		**out = **in
	}
	if in.EnableIntegrityMonitoring != nil {
		in, out := &in.EnableIntegrityMonitoring, &out.EnableIntegrityMonitoring
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance_ShieldedInstanceConfig.
func (in *Instance_ShieldedInstanceConfig) DeepCopy() *Instance_ShieldedInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(Instance_ShieldedInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance_UpgradeHistoryEntry) DeepCopyInto(out *Instance_UpgradeHistoryEntry) {
	*out = *in
	if in.Snapshot != nil {
		in, out := &in.Snapshot, &out.Snapshot
		*out = new(string)
		**out = **in
	}
	if in.VMImage != nil {
		in, out := &in.VMImage, &out.VMImage
		*out = new(string)
		**out = **in
	}
	if in.ContainerImage != nil {
		in, out := &in.ContainerImage, &out.ContainerImage
		*out = new(string)
		**out = **in
	}
	if in.Framework != nil {
		in, out := &in.Framework, &out.Framework
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.TargetImage != nil {
		in, out := &in.TargetImage, &out.TargetImage
		*out = new(string)
		**out = **in
	}
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.TargetVersion != nil {
		in, out := &in.TargetVersion, &out.TargetVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance_UpgradeHistoryEntry.
func (in *Instance_UpgradeHistoryEntry) DeepCopy() *Instance_UpgradeHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(Instance_UpgradeHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookInstanceV2) DeepCopyInto(out *NotebookInstanceV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookInstanceV2.
func (in *NotebookInstanceV2) DeepCopy() *NotebookInstanceV2 {
	if in == nil {
		return nil
	}
	out := new(NotebookInstanceV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebookInstanceV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookInstanceV2List) DeepCopyInto(out *NotebookInstanceV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotebookInstanceV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookInstanceV2List.
func (in *NotebookInstanceV2List) DeepCopy() *NotebookInstanceV2List {
	if in == nil {
		return nil
	}
	out := new(NotebookInstanceV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebookInstanceV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookInstanceV2ObservedState) DeepCopyInto(out *NotebookInstanceV2ObservedState) {
	*out = *in
	if in.ProxyURI != nil {
		in, out := &in.ProxyURI, &out.ProxyURI
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]Instance_Disk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookInstanceV2ObservedState.
func (in *NotebookInstanceV2ObservedState) DeepCopy() *NotebookInstanceV2ObservedState {
	if in == nil {
		return nil
	}
	out := new(NotebookInstanceV2ObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookInstanceV2Ref) DeepCopyInto(out *NotebookInstanceV2Ref) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookInstanceV2Ref.
func (in *NotebookInstanceV2Ref) DeepCopy() *NotebookInstanceV2Ref {
	if in == nil {
		return nil
	}
	out := new(NotebookInstanceV2Ref)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookInstanceV2Spec) DeepCopyInto(out *NotebookInstanceV2Spec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.VMImage != nil {
		in, out := &in.VMImage, &out.VMImage
		*out = new(VMImage)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerImage != nil {
		in, out := &in.ContainerImage, &out.ContainerImage
		*out = new(ContainerImage)
		(*in).DeepCopyInto(*out)
	}
	if in.PostStartupScript != nil {
		in, out := &in.PostStartupScript, &out.PostStartupScript
		*out = new(string)
		**out = **in
	}
	if in.InstanceOwners != nil {
		in, out := &in.InstanceOwners, &out.InstanceOwners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
	if in.ServiceAccountScopes != nil {
		in, out := &in.ServiceAccountScopes, &out.ServiceAccountScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MachineType != nil {
		in, out := &in.MachineType, &out.MachineType
		*out = new(string)
		**out = **in
	}
	if in.AcceleratorConfig != nil {
		in, out := &in.AcceleratorConfig, &out.AcceleratorConfig
		*out = new(Instance_AcceleratorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InstallGpuDriver != nil {
		in, out := &in.InstallGpuDriver, &out.InstallGpuDriver
		*out = new(bool)
		**out = **in
	}
	if in.CustomGpuDriverPath != nil {
		in, out := &in.CustomGpuDriverPath, &out.CustomGpuDriverPath
		*out = new(string)
		**out = **in
	}
	if in.BootDiskType != nil {
		in, out := &in.BootDiskType, &out.BootDiskType
		*out = new(string)
		**out = **in
	}
	if in.BootDiskSizeGB != nil {
		in, out := &in.BootDiskSizeGB, &out.BootDiskSizeGB
		*out = new(int64)
		**out = **in
	}
	if in.DataDiskType != nil {
		in, out := &in.DataDiskType, &out.DataDiskType
		*out = new(string)
		**out = **in
	}
	if in.DataDiskSizeGB != nil {
		in, out := &in.DataDiskSizeGB, &out.DataDiskSizeGB
		*out = new(int64)
		**out = **in
	}
	if in.NoRemoveDataDisk != nil {
		in, out := &in.NoRemoveDataDisk, &out.NoRemoveDataDisk
		*out = new(bool)
		**out = **in
	}
	if in.DiskEncryption != nil {
		in, out := &in.DiskEncryption, &out.DiskEncryption
		*out = new(string)
		**out = **in
	}
	if in.KMSKey != nil {
		in, out := &in.KMSKey, &out.KMSKey
		*out = new(string)
		**out = **in
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(Instance_ShieldedInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NoPublicIP != nil {
		in, out := &in.NoPublicIP, &out.NoPublicIP
		*out = new(bool)
		**out = **in
	}
	if in.NoProxyAccess != nil {
		in, out := &in.NoProxyAccess, &out.NoProxyAccess
		*out = new(bool)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.Subnet != nil {
		in, out := &in.Subnet, &out.Subnet
		*out = new(string)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpgradeHistory != nil {
		in, out := &in.UpgradeHistory, &out.UpgradeHistory
		*out = make([]Instance_UpgradeHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NicType != nil {
		in, out := &in.NicType, &out.NicType
		*out = new(string)
		**out = **in
	}
	if in.ReservationAffinity != nil {
		in, out := &in.ReservationAffinity, &out.ReservationAffinity
		*out = new(ReservationAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.CanIPForward != nil {
		in, out := &in.CanIPForward, &out.CanIPForward
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookInstanceV2Spec.
func (in *NotebookInstanceV2Spec) DeepCopy() *NotebookInstanceV2Spec {
	if in == nil {
		return nil
	}
	out := new(NotebookInstanceV2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebookInstanceV2Status) DeepCopyInto(out *NotebookInstanceV2Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NotebookInstanceV2ObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebookInstanceV2Status.
func (in *NotebookInstanceV2Status) DeepCopy() *NotebookInstanceV2Status {
	if in == nil {
		return nil
	}
	out := new(NotebookInstanceV2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksEnvironment) DeepCopyInto(out *NotebooksEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksEnvironment.
func (in *NotebooksEnvironment) DeepCopy() *NotebooksEnvironment {
	if in == nil {
		return nil
	}
	out := new(NotebooksEnvironment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebooksEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksEnvironmentList) DeepCopyInto(out *NotebooksEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotebooksEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksEnvironmentList.
func (in *NotebooksEnvironmentList) DeepCopy() *NotebooksEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(NotebooksEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebooksEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksEnvironmentObservedState) DeepCopyInto(out *NotebooksEnvironmentObservedState) {
	*out = *in
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksEnvironmentObservedState.
func (in *NotebooksEnvironmentObservedState) DeepCopy() *NotebooksEnvironmentObservedState {
	if in == nil {
		return nil
	}
	out := new(NotebooksEnvironmentObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksEnvironmentSpec) DeepCopyInto(out *NotebooksEnvironmentSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.VMImage != nil {
		in, out := &in.VMImage, &out.VMImage
		*out = new(VMImage)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerImage != nil {
		in, out := &in.ContainerImage, &out.ContainerImage
		*out = new(ContainerImage)
		(*in).DeepCopyInto(*out)
	}
	if in.PostStartupScript != nil {
		in, out := &in.PostStartupScript, &out.PostStartupScript
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksEnvironmentSpec.
func (in *NotebooksEnvironmentSpec) DeepCopy() *NotebooksEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(NotebooksEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksEnvironmentStatus) DeepCopyInto(out *NotebooksEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NotebooksEnvironmentObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksEnvironmentStatus.
func (in *NotebooksEnvironmentStatus) DeepCopy() *NotebooksEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(NotebooksEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksExecution) DeepCopyInto(out *NotebooksExecution) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksExecution.
func (in *NotebooksExecution) DeepCopy() *NotebooksExecution {
	if in == nil {
		return nil
	}
	out := new(NotebooksExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebooksExecution) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksExecutionList) DeepCopyInto(out *NotebooksExecutionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotebooksExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksExecutionList.
func (in *NotebooksExecutionList) DeepCopy() *NotebooksExecutionList {
	if in == nil {
		return nil
	}
	out := new(NotebooksExecutionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebooksExecutionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksExecutionObservedState) DeepCopyInto(out *NotebooksExecutionObservedState) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.JobURI != nil {
		in, out := &in.JobURI, &out.JobURI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksExecutionObservedState.
func (in *NotebooksExecutionObservedState) DeepCopy() *NotebooksExecutionObservedState {
	if in == nil {
		return nil
	}
	out := new(NotebooksExecutionObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksExecutionSpec) DeepCopyInto(out *NotebooksExecutionSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ExecutionTemplate != nil {
		in, out := &in.ExecutionTemplate, &out.ExecutionTemplate
		*out = new(ExecutionTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.OutputNotebookFile != nil {
		in, out := &in.OutputNotebookFile, &out.OutputNotebookFile
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksExecutionSpec.
func (in *NotebooksExecutionSpec) DeepCopy() *NotebooksExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(NotebooksExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksExecutionStatus) DeepCopyInto(out *NotebooksExecutionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NotebooksExecutionObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksExecutionStatus.
func (in *NotebooksExecutionStatus) DeepCopy() *NotebooksExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(NotebooksExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksSchedule) DeepCopyInto(out *NotebooksSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksSchedule.
func (in *NotebooksSchedule) DeepCopy() *NotebooksSchedule {
	if in == nil {
		return nil
	}
	out := new(NotebooksSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebooksSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksScheduleList) DeepCopyInto(out *NotebooksScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotebooksSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksScheduleList.
func (in *NotebooksScheduleList) DeepCopy() *NotebooksScheduleList {
	if in == nil {
		return nil
	}
	out := new(NotebooksScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotebooksScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksScheduleObservedState) DeepCopyInto(out *NotebooksScheduleObservedState) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.CreateTime != nil {
		in, out := &in.CreateTime, &out.CreateTime
		*out = new(string)
		**out = **in
	}
	if in.UpdateTime != nil {
		in, out := &in.UpdateTime, &out.UpdateTime
		*out = new(string)
		**out = **in
	}
	if in.RecentExecutions != nil {
		in, out := &in.RecentExecutions, &out.RecentExecutions
		*out = make([]ExecutionObservedState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksScheduleObservedState.
func (in *NotebooksScheduleObservedState) DeepCopy() *NotebooksScheduleObservedState {
	if in == nil {
		return nil
	}
	out := new(NotebooksScheduleObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksScheduleSpec) DeepCopyInto(out *NotebooksScheduleSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(v1beta1.ProjectRef)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.CronSchedule != nil {
		in, out := &in.CronSchedule, &out.CronSchedule
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.ExecutionTemplate != nil {
		in, out := &in.ExecutionTemplate, &out.ExecutionTemplate
		*out = new(ExecutionTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksScheduleSpec.
func (in *NotebooksScheduleSpec) DeepCopy() *NotebooksScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(NotebooksScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotebooksScheduleStatus) DeepCopyInto(out *NotebooksScheduleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]k8sv1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(NotebooksScheduleObservedState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotebooksScheduleStatus.
func (in *NotebooksScheduleStatus) DeepCopy() *NotebooksScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(NotebooksScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReservationAffinity) DeepCopyInto(out *ReservationAffinity) {
	*out = *in
	if in.ConsumeReservationType != nil {
		in, out := &in.ConsumeReservationType, &out.ConsumeReservationType
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReservationAffinity.
func (in *ReservationAffinity) DeepCopy() *ReservationAffinity {
	if in == nil {
		return nil
	}
	out := new(ReservationAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMImage) DeepCopyInto(out *VMImage) {
	*out = *in
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = new(string)
		**out = **in
	}
	if in.ImageName != nil {
		in, out := &in.ImageName, &out.ImageName
		*out = new(string)
		**out = **in
	}
	if in.ImageFamily != nil {
		in, out := &in.ImageFamily, &out.ImageFamily
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMImage.
func (in *VMImage) DeepCopy() *VMImage {
	if in == nil {
		return nil
	}
	out := new(VMImage)
	in.DeepCopyInto(out)
	return out
}
