// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: chronicle.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.chronicle.v1
// resource: ChronicleWatchlist:Watchlist

package v1alpha1

/* unreachable type Watchlist
// +kcc:proto=google.cloud.chronicle.v1.Watchlist
type Watchlist struct {
	// Identifier. Resource name of the watchlist.
	//  Format:
	//  `projects/{project}/locations/{location}/instances/{instance}/watchlists/{watchlist}`
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.name
	Name *string `json:"name,omitempty"`

	// Required. Display name of the watchlist.
	//  Note that it must be at least one character and less than 63 characters
	//  (https://google.aip.dev/148).
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.display_name
	// +required
	DisplayName *string `json:"displayName,omitempty"`

	// Optional. Description of the watchlist.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.description
	Description *string `json:"description,omitempty"`

	// Optional. Weight applied to the risk score for entities
	//  in this watchlist.
	//  The default is 1.0 if it is not specified.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.multiplying_factor
	MultiplyingFactor *float32 `json:"multiplyingFactor,omitempty"`

	// Required. Mechanism to populate entities in the watchlist.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.entity_population_mechanism
	// +required
	EntityPopulationMechanism *Watchlist_EntityPopulationMechanism `json:"entityPopulationMechanism,omitempty"`

	// Optional. User preferences for watchlist configuration.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.watchlist_user_preferences
	WatchlistUserPreferences *WatchlistUserPreferences `json:"watchlistUserPreferences,omitempty"`
}
*/

/* unreachable type Watchlist_EntityCount
// +kcc:proto=google.cloud.chronicle.v1.Watchlist.EntityCount
type Watchlist_EntityCount struct {
}
*/

// +kcc:proto=google.cloud.chronicle.v1.Watchlist.EntityPopulationMechanism
type Watchlist_EntityPopulationMechanism struct {
	// Optional. Entities are added manually.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.EntityPopulationMechanism.manual
	Manual *Watchlist_EntityPopulationMechanism_Manual `json:"manual,omitempty"`
}

// +kcc:proto=google.cloud.chronicle.v1.Watchlist.EntityPopulationMechanism.Manual
type Watchlist_EntityPopulationMechanism_Manual struct {
}

// +kcc:proto=google.cloud.chronicle.v1.WatchlistUserPreferences
type WatchlistUserPreferences struct {
	// Optional. Whether the watchlist is pinned on the dashboard.
	// +kcc:proto:field=google.cloud.chronicle.v1.WatchlistUserPreferences.pinned
	Pinned *bool `json:"pinned,omitempty"`
}

/* unreachable type WatchlistObservedState
// +kcc:observedstate:proto=google.cloud.chronicle.v1.Watchlist
type WatchlistObservedState struct {
	// Output only. Entity count in the watchlist.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.entity_count
	EntityCount *Watchlist_EntityCountObservedState `json:"entityCount,omitempty"`

	// Output only. Time the watchlist was created.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. Time the watchlist was last updated.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.update_time
	UpdateTime *string `json:"updateTime,omitempty"`
}
*/

// +kcc:observedstate:proto=google.cloud.chronicle.v1.Watchlist.EntityCount
type Watchlist_EntityCountObservedState struct {
	// Output only. Count of user type entities in the watchlist.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.EntityCount.user
	User *int32 `json:"user,omitempty"`

	// Output only. Count of asset type entities in the watchlist.
	// +kcc:proto:field=google.cloud.chronicle.v1.Watchlist.EntityCount.asset
	Asset *int32 `json:"asset,omitempty"`
}
