// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var ComputeMachineImageGVK = GroupVersion.WithKind("ComputeMachineImage")

// ComputeMachineImageSpec defines the desired state of ComputeMachineImage
// +kcc:spec:proto=google.cloud.compute.v1.MachineImage
type ComputeMachineImageSpec struct {
	// The project that this resource belongs to.
	ProjectRef *refsv1beta1.ProjectRef `json:"projectRef"`


	// The ComputeMachineImage name. If not given, the metadata.name will be used.
	ResourceID *string `json:"resourceID,omitempty"`
	// [Output Only] The creation timestamp for this machine image in RFC3339 text format.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.creation_timestamp
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`

	// An optional description of this resource. Provide this property when you create the resource.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.description
	Description *string `json:"description,omitempty"`

	// [Input Only] Whether to attempt an application consistent machine image by informing the OS to prepare for the snapshot process.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.guest_flush
	GuestFlush *bool `json:"guestFlush,omitempty"`

	// [Output Only] A unique identifier for this machine image. The server defines this identifier.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.id
	ID *uint64 `json:"id,omitempty"`

	// [Output Only] Properties of source instance
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.instance_properties
	InstanceProperties *InstanceProperties `json:"instanceProperties,omitempty"`

	// [Output Only] The resource type, which is always compute#machineImage for machine image.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.kind
	Kind *string `json:"kind,omitempty"`

	// A fingerprint for the labels being applied to this machine image, which is essentially a hash of the labels set used for optimistic locking. The fingerprint is initially generated by Compute Engine and changes after every request to modify or update labels. You must always provide an up-to-date fingerprint hash in order to update or change labels. To see the latest fingerprint, make get() request to the machine image.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.label_fingerprint
	LabelFingerprint *string `json:"labelFingerprint,omitempty"`

	// Labels to apply to this machine image. These can be later modified by the setLabels method.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.labels
	Labels map[string]string `json:"labels,omitempty"`

	// Encrypts the machine image using a customer-supplied encryption key. After you encrypt a machine image using a customer-supplied key, you must provide the same key if you use the machine image later. For example, you must provide the encryption key when you create an instance from the encrypted machine image in a future request. Customer-supplied encryption keys do not protect access to metadata of the machine image. If you do not provide an encryption key when creating the machine image, then the machine image will be encrypted using an automatically generated key and you do not need to provide a key to use the machine image later.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.machine_image_encryption_key
	MachineImageEncryptionKey *CustomerEncryptionKey `json:"machineImageEncryptionKey,omitempty"`

	// Output only. Reserved for future use.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.satisfies_pzi
	SatisfiesPzi *bool `json:"satisfiesPzi,omitempty"`

	// [Output Only] Reserved for future use.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.satisfies_pzs
	SatisfiesPzs *bool `json:"satisfiesPzs,omitempty"`

	// An array of Machine Image specific properties for disks attached to the source instance
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.saved_disks
	SavedDisks []SavedDisk `json:"savedDisks,omitempty"`

	// [Output Only] The URL for this machine image. The server defines this URL.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.self_link
	SelfLink *string `json:"selfLink,omitempty"`

	// [Input Only] The customer-supplied encryption key of the disks attached to the source instance. Required if the source disk is protected by a customer-supplied encryption key.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.source_disk_encryption_keys
	SourceDiskEncryptionKeys []SourceDiskEncryptionKey `json:"sourceDiskEncryptionKeys,omitempty"`

	// The source instance used to create the machine image. You can provide this as a partial or full URL to the resource. For example, the following are valid values: - https://www.googleapis.com/compute/v1/projects/project/zones/zone /instances/instance - projects/project/zones/zone/instances/instance
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.source_instance
	SourceInstance *string `json:"sourceInstance,omitempty"`

	// [Output Only] DEPRECATED: Please use instance_properties instead for source instance related properties. New properties will not be added to this field.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.source_instance_properties
	SourceInstanceProperties *SourceInstanceProperties `json:"sourceInstanceProperties,omitempty"`

	// [Output Only] The status of the machine image. One of the following values: INVALID, CREATING, READY, DELETING, and UPLOADING.
	//  Check the Status enum for the list of possible values.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.status
	Status *string `json:"status,omitempty"`

	// The regional or multi-regional Cloud Storage bucket location where the machine image is stored.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.storage_locations
	StorageLocations []string `json:"storageLocations,omitempty"`

	// [Output Only] Total size of the storage used by the machine image.
	// +kcc:proto:field=google.cloud.compute.v1.MachineImage.total_storage_bytes
	TotalStorageBytes *int64 `json:"totalStorageBytes,omitempty"`
}

// ComputeMachineImageStatus defines the config connector machine state of ComputeMachineImage
type ComputeMachineImageStatus struct {
	/* Conditions represent the latest available observations of the
	   object's current state. */
	Conditions []v1alpha1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// A unique specifier for the ComputeMachineImage resource in GCP.
	ExternalRef *string `json:"externalRef,omitempty"`

	// ObservedState is the state of the resource as most recently observed in GCP.
	ObservedState *ComputeMachineImageObservedState `json:"observedState,omitempty"`
}

// ComputeMachineImageObservedState is the state of the ComputeMachineImage resource as most recently observed in GCP.
// +kcc:observedstate:proto=google.cloud.compute.v1.MachineImage
type ComputeMachineImageObservedState struct {
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:categories=gcp,shortName=gcpcomputemachineimage;gcpcomputemachineimages
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/managed-by-kcc=true"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/system=true"
// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type="date"
// +kubebuilder:printcolumn:name="Ready",JSONPath=".status.conditions[?(@.type=='Ready')].status",type="string",description="When 'True', the most recent reconcile of the resource succeeded"
// +kubebuilder:printcolumn:name="Status",JSONPath=".status.conditions[?(@.type=='Ready')].reason",type="string",description="The reason for the value in 'Ready'"
// +kubebuilder:printcolumn:name="Status Age",JSONPath=".status.conditions[?(@.type=='Ready')].lastTransitionTime",type="date",description="The last transition time for the value in 'Status'"

// ComputeMachineImage is the Schema for the ComputeMachineImage API
// +k8s:openapi-gen=true
type ComputeMachineImage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +required
	Spec   ComputeMachineImageSpec   `json:"spec,omitempty"`
	Status ComputeMachineImageStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// ComputeMachineImageList contains a list of ComputeMachineImage
type ComputeMachineImageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ComputeMachineImage `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ComputeMachineImage{}, &ComputeMachineImageList{})
}
