// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: kms.cnrm.cloud.google.com
// krm.version: v1beta1
// proto.service: google.cloud.kms.v1

package kms

import (
	pb "cloud.google.com/go/kms/apiv1/kmspb"
	krmkmsv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/kms/v1alpha1"
	krmkmsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/kms/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

/* found existing non-generated mapping function "CryptoKeyVersionTemplate_v1beta1_FromProto", skipping
func CryptoKeyVersionTemplate_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CryptoKeyVersionTemplate) *krmkmsv1beta1.CryptoKeyVersionTemplate {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.CryptoKeyVersionTemplate{}
	out.ProtectionLevel = direct.Enum_FromProto(mapCtx, in.GetProtectionLevel())
	out.Algorithm = direct.Enum_FromProto(mapCtx, in.GetAlgorithm())
	return out
}
*/

/*
found existing non-generated mapping function "CryptoKeyVersionTemplate_v1beta1_ToProto", skipping

	func CryptoKeyVersionTemplate_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.CryptoKeyVersionTemplate) *pb.CryptoKeyVersionTemplate {
		if in == nil {
			return nil
		}
		out := &pb.CryptoKeyVersionTemplate{}
		out.ProtectionLevel = direct.Enum_ToProto[pb.ProtectionLevel](mapCtx, in.ProtectionLevel)
		out.Algorithm = direct.Enum_ToProto[pb.CryptoKeyVersion_CryptoKeyVersionAlgorithm](mapCtx, in.Algorithm)
		return out
	}
*/
func ExternalProtectionLevelOptions_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ExternalProtectionLevelOptions) *krmkmsv1alpha1.ExternalProtectionLevelOptions {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.ExternalProtectionLevelOptions{}
	out.ExternalKeyURI = direct.LazyPtr(in.GetExternalKeyUri())
	out.EkmConnectionKeyPath = direct.LazyPtr(in.GetEkmConnectionKeyPath())
	return out
}
func ExternalProtectionLevelOptions_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.ExternalProtectionLevelOptions) *pb.ExternalProtectionLevelOptions {
	if in == nil {
		return nil
	}
	out := &pb.ExternalProtectionLevelOptions{}
	out.ExternalKeyUri = direct.ValueOf(in.ExternalKeyURI)
	out.EkmConnectionKeyPath = direct.ValueOf(in.EkmConnectionKeyPath)
	return out
}
func ImportJob_WrappingPublicKey_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ImportJob_WrappingPublicKey) *krmkmsv1alpha1.ImportJob_WrappingPublicKey {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.ImportJob_WrappingPublicKey{}
	out.Pem = direct.LazyPtr(in.GetPem())
	return out
}
func ImportJob_WrappingPublicKey_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.ImportJob_WrappingPublicKey) *pb.ImportJob_WrappingPublicKey {
	if in == nil {
		return nil
	}
	out := &pb.ImportJob_WrappingPublicKey{}
	out.Pem = direct.ValueOf(in.Pem)
	return out
}
func KMSAutokeyConfigObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.AutokeyConfig) *krmkmsv1beta1.KMSAutokeyConfigObservedState {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSAutokeyConfigObservedState{}
	// MISSING: Name
	// MISSING: KeyProject
	// MISSING: State
	// MISSING: Etag
	return out
}
func KMSAutokeyConfigObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSAutokeyConfigObservedState) *pb.AutokeyConfig {
	if in == nil {
		return nil
	}
	out := &pb.AutokeyConfig{}
	// MISSING: Name
	// MISSING: KeyProject
	// MISSING: State
	// MISSING: Etag
	return out
}
func KMSAutokeyConfigSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.AutokeyConfig) *krmkmsv1beta1.KMSAutokeyConfigSpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSAutokeyConfigSpec{}
	// MISSING: Name
	// MISSING: KeyProject
	// MISSING: State
	// MISSING: Etag
	return out
}
func KMSAutokeyConfigSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSAutokeyConfigSpec) *pb.AutokeyConfig {
	if in == nil {
		return nil
	}
	out := &pb.AutokeyConfig{}
	// MISSING: Name
	// MISSING: KeyProject
	// MISSING: State
	// MISSING: Etag
	return out
}
func KMSCryptoKeySpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CryptoKey) *krmkmsv1beta1.KMSCryptoKeySpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSCryptoKeySpec{}
	// MISSING: Name
	// MISSING: Primary
	out.Purpose = direct.Enum_FromProto(mapCtx, in.GetPurpose())
	// MISSING: CreateTime
	// MISSING: NextRotationTime
	out.RotationPeriod = direct.StringDuration_FromProto(mapCtx, in.GetRotationPeriod())
	out.VersionTemplate = CryptoKeyVersionTemplate_v1beta1_FromProto(mapCtx, in.GetVersionTemplate())
	// MISSING: Labels
	out.ImportOnly = direct.LazyPtr(in.GetImportOnly())
	out.DestroyScheduledDuration = direct.StringDuration_FromProto(mapCtx, in.GetDestroyScheduledDuration())
	// MISSING: CryptoKeyBackend
	// MISSING: KeyAccessJustificationsPolicy
	return out
}
func KMSCryptoKeySpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSCryptoKeySpec) *pb.CryptoKey {
	if in == nil {
		return nil
	}
	out := &pb.CryptoKey{}
	// MISSING: Name
	// MISSING: Primary
	out.Purpose = direct.Enum_ToProto[pb.CryptoKey_CryptoKeyPurpose](mapCtx, in.Purpose)
	// MISSING: CreateTime
	// MISSING: NextRotationTime
	if oneof := direct.StringDuration_ToProto(mapCtx, in.RotationPeriod); oneof != nil {
		out.RotationSchedule = &pb.CryptoKey_RotationPeriod{RotationPeriod: oneof}
	}
	out.VersionTemplate = CryptoKeyVersionTemplate_v1beta1_ToProto(mapCtx, in.VersionTemplate)
	// MISSING: Labels
	out.ImportOnly = direct.ValueOf(in.ImportOnly)
	out.DestroyScheduledDuration = direct.StringDuration_ToProto(mapCtx, in.DestroyScheduledDuration)
	// MISSING: CryptoKeyBackend
	// MISSING: KeyAccessJustificationsPolicy
	return out
}
func KMSCryptoKeyStatus_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.CryptoKey) *krmkmsv1beta1.KMSCryptoKeyStatus {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSCryptoKeyStatus{}
	// MISSING: Name
	// MISSING: Primary
	// MISSING: Purpose
	// MISSING: CreateTime
	// MISSING: NextRotationTime
	// MISSING: RotationPeriod
	// MISSING: VersionTemplate
	// MISSING: Labels
	// MISSING: ImportOnly
	// MISSING: DestroyScheduledDuration
	// MISSING: CryptoKeyBackend
	// MISSING: KeyAccessJustificationsPolicy
	return out
}
func KMSCryptoKeyStatus_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSCryptoKeyStatus) *pb.CryptoKey {
	if in == nil {
		return nil
	}
	out := &pb.CryptoKey{}
	// MISSING: Name
	// MISSING: Primary
	// MISSING: Purpose
	// MISSING: CreateTime
	// MISSING: NextRotationTime
	// MISSING: RotationPeriod
	// MISSING: VersionTemplate
	// MISSING: Labels
	// MISSING: ImportOnly
	// MISSING: DestroyScheduledDuration
	// MISSING: CryptoKeyBackend
	// MISSING: KeyAccessJustificationsPolicy
	return out
}
func KMSCryptoKeyVersionObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CryptoKeyVersion) *krmkmsv1alpha1.KMSCryptoKeyVersionObservedState {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.KMSCryptoKeyVersionObservedState{}
	// MISSING: Name
	out.ProtectionLevel = direct.Enum_FromProto(mapCtx, in.GetProtectionLevel())
	out.Algorithm = direct.Enum_FromProto(mapCtx, in.GetAlgorithm())
	out.Attestation = KeyOperationAttestationObservedState_v1alpha1_FromProto(mapCtx, in.GetAttestation())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.GenerateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetGenerateTime())
	out.DestroyTime = direct.StringTimestamp_FromProto(mapCtx, in.GetDestroyTime())
	out.DestroyEventTime = direct.StringTimestamp_FromProto(mapCtx, in.GetDestroyEventTime())
	out.ImportJob = direct.LazyPtr(in.GetImportJob())
	out.ImportTime = direct.StringTimestamp_FromProto(mapCtx, in.GetImportTime())
	out.ImportFailureReason = direct.LazyPtr(in.GetImportFailureReason())
	out.GenerationFailureReason = direct.LazyPtr(in.GetGenerationFailureReason())
	out.ExternalDestructionFailureReason = direct.LazyPtr(in.GetExternalDestructionFailureReason())
	out.ReimportEligible = direct.LazyPtr(in.GetReimportEligible())
	return out
}
func KMSCryptoKeyVersionObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.KMSCryptoKeyVersionObservedState) *pb.CryptoKeyVersion {
	if in == nil {
		return nil
	}
	out := &pb.CryptoKeyVersion{}
	// MISSING: Name
	out.ProtectionLevel = direct.Enum_ToProto[pb.ProtectionLevel](mapCtx, in.ProtectionLevel)
	out.Algorithm = direct.Enum_ToProto[pb.CryptoKeyVersion_CryptoKeyVersionAlgorithm](mapCtx, in.Algorithm)
	out.Attestation = KeyOperationAttestationObservedState_v1alpha1_ToProto(mapCtx, in.Attestation)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.GenerateTime = direct.StringTimestamp_ToProto(mapCtx, in.GenerateTime)
	out.DestroyTime = direct.StringTimestamp_ToProto(mapCtx, in.DestroyTime)
	out.DestroyEventTime = direct.StringTimestamp_ToProto(mapCtx, in.DestroyEventTime)
	out.ImportJob = direct.ValueOf(in.ImportJob)
	out.ImportTime = direct.StringTimestamp_ToProto(mapCtx, in.ImportTime)
	out.ImportFailureReason = direct.ValueOf(in.ImportFailureReason)
	out.GenerationFailureReason = direct.ValueOf(in.GenerationFailureReason)
	out.ExternalDestructionFailureReason = direct.ValueOf(in.ExternalDestructionFailureReason)
	out.ReimportEligible = direct.ValueOf(in.ReimportEligible)
	return out
}
func KMSCryptoKeyVersionSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CryptoKeyVersion) *krmkmsv1alpha1.KMSCryptoKeyVersionSpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.KMSCryptoKeyVersionSpec{}
	// MISSING: Name
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.ExternalProtectionLevelOptions = ExternalProtectionLevelOptions_v1alpha1_FromProto(mapCtx, in.GetExternalProtectionLevelOptions())
	return out
}
func KMSCryptoKeyVersionSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.KMSCryptoKeyVersionSpec) *pb.CryptoKeyVersion {
	if in == nil {
		return nil
	}
	out := &pb.CryptoKeyVersion{}
	// MISSING: Name
	out.State = direct.Enum_ToProto[pb.CryptoKeyVersion_CryptoKeyVersionState](mapCtx, in.State)
	out.ExternalProtectionLevelOptions = ExternalProtectionLevelOptions_v1alpha1_ToProto(mapCtx, in.ExternalProtectionLevelOptions)
	return out
}
func KMSImportJobObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.ImportJob) *krmkmsv1beta1.KMSImportJobObservedState {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSImportJobObservedState{}
	// MISSING: Name
	// MISSING: ImportMethod
	// MISSING: ProtectionLevel
	// MISSING: CreateTime
	// MISSING: GenerateTime
	// MISSING: ExpireTime
	// MISSING: ExpireEventTime
	// MISSING: State
	// MISSING: PublicKey
	// MISSING: Attestation
	return out
}
func KMSImportJobObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSImportJobObservedState) *pb.ImportJob {
	if in == nil {
		return nil
	}
	out := &pb.ImportJob{}
	// MISSING: Name
	// MISSING: ImportMethod
	// MISSING: ProtectionLevel
	// MISSING: CreateTime
	// MISSING: GenerateTime
	// MISSING: ExpireTime
	// MISSING: ExpireEventTime
	// MISSING: State
	// MISSING: PublicKey
	// MISSING: Attestation
	return out
}
func KMSImportJobSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.ImportJob) *krmkmsv1beta1.KMSImportJobSpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSImportJobSpec{}
	// MISSING: Name
	// MISSING: ImportMethod
	// MISSING: ProtectionLevel
	// MISSING: CreateTime
	// MISSING: GenerateTime
	// MISSING: ExpireTime
	// MISSING: ExpireEventTime
	// MISSING: State
	// MISSING: PublicKey
	// MISSING: Attestation
	return out
}
func KMSImportJobSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSImportJobSpec) *pb.ImportJob {
	if in == nil {
		return nil
	}
	out := &pb.ImportJob{}
	// MISSING: Name
	// MISSING: ImportMethod
	// MISSING: ProtectionLevel
	// MISSING: CreateTime
	// MISSING: GenerateTime
	// MISSING: ExpireTime
	// MISSING: ExpireEventTime
	// MISSING: State
	// MISSING: PublicKey
	// MISSING: Attestation
	return out
}
func KMSKeyHandleObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KeyHandle) *krmkmsv1beta1.KMSKeyHandleObservedState {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSKeyHandleObservedState{}
	// MISSING: Name
	// MISSING: KMSKey
	// MISSING: ResourceTypeSelector
	return out
}
func KMSKeyHandleObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSKeyHandleObservedState) *pb.KeyHandle {
	if in == nil {
		return nil
	}
	out := &pb.KeyHandle{}
	// MISSING: Name
	// MISSING: KMSKey
	// MISSING: ResourceTypeSelector
	return out
}
func KMSKeyHandleSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KeyHandle) *krmkmsv1beta1.KMSKeyHandleSpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSKeyHandleSpec{}
	// MISSING: Name
	// MISSING: KMSKey
	// MISSING: ResourceTypeSelector
	return out
}
func KMSKeyHandleSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSKeyHandleSpec) *pb.KeyHandle {
	if in == nil {
		return nil
	}
	out := &pb.KeyHandle{}
	// MISSING: Name
	// MISSING: KMSKey
	// MISSING: ResourceTypeSelector
	return out
}
func KMSKeyRingImportJobObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ImportJob) *krmkmsv1alpha1.KMSKeyRingImportJobObservedState {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.KMSKeyRingImportJobObservedState{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.GenerateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetGenerateTime())
	out.ExpireTime = direct.StringTimestamp_FromProto(mapCtx, in.GetExpireTime())
	out.ExpireEventTime = direct.StringTimestamp_FromProto(mapCtx, in.GetExpireEventTime())
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.PublicKey = ImportJob_WrappingPublicKey_v1alpha1_FromProto(mapCtx, in.GetPublicKey())
	out.Attestation = KeyOperationAttestationObservedState_v1alpha1_FromProto(mapCtx, in.GetAttestation())
	return out
}
func KMSKeyRingImportJobObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.KMSKeyRingImportJobObservedState) *pb.ImportJob {
	if in == nil {
		return nil
	}
	out := &pb.ImportJob{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.GenerateTime = direct.StringTimestamp_ToProto(mapCtx, in.GenerateTime)
	out.ExpireTime = direct.StringTimestamp_ToProto(mapCtx, in.ExpireTime)
	out.ExpireEventTime = direct.StringTimestamp_ToProto(mapCtx, in.ExpireEventTime)
	out.State = direct.Enum_ToProto[pb.ImportJob_ImportJobState](mapCtx, in.State)
	out.PublicKey = ImportJob_WrappingPublicKey_v1alpha1_ToProto(mapCtx, in.PublicKey)
	out.Attestation = KeyOperationAttestationObservedState_v1alpha1_ToProto(mapCtx, in.Attestation)
	return out
}

/* found existing non-generated mapping function "KMSKeyRingImportJobSpec_v1alpha1_FromProto", skipping
func KMSKeyRingImportJobSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ImportJob) *krmkmsv1alpha1.KMSKeyRingImportJobSpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.KMSKeyRingImportJobSpec{}
	// MISSING: Name
	out.ImportMethod = direct.Enum_FromProto(mapCtx, in.GetImportMethod())
	out.ProtectionLevel = direct.Enum_FromProto(mapCtx, in.GetProtectionLevel())
	return out
}
*/

/*
found existing non-generated mapping function "KMSKeyRingImportJobSpec_v1alpha1_ToProto", skipping

	func KMSKeyRingImportJobSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.KMSKeyRingImportJobSpec) *pb.ImportJob {
		if in == nil {
			return nil
		}
		out := &pb.ImportJob{}
		// MISSING: Name
		out.ImportMethod = direct.Enum_ToProto[pb.ImportJob_ImportMethod](mapCtx, in.ImportMethod)
		out.ProtectionLevel = direct.Enum_ToProto[pb.ProtectionLevel](mapCtx, in.ProtectionLevel)
		return out
	}
*/
func KMSKeyRingSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KeyRing) *krmkmsv1beta1.KMSKeyRingSpec {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSKeyRingSpec{}
	// MISSING: Name
	// MISSING: CreateTime
	return out
}
func KMSKeyRingSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSKeyRingSpec) *pb.KeyRing {
	if in == nil {
		return nil
	}
	out := &pb.KeyRing{}
	// MISSING: Name
	// MISSING: CreateTime
	return out
}
func KMSKeyRingStatus_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.KeyRing) *krmkmsv1beta1.KMSKeyRingStatus {
	if in == nil {
		return nil
	}
	out := &krmkmsv1beta1.KMSKeyRingStatus{}
	// MISSING: Name
	// MISSING: CreateTime
	return out
}
func KMSKeyRingStatus_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1beta1.KMSKeyRingStatus) *pb.KeyRing {
	if in == nil {
		return nil
	}
	out := &pb.KeyRing{}
	// MISSING: Name
	// MISSING: CreateTime
	return out
}
func KeyOperationAttestationObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.KeyOperationAttestation) *krmkmsv1alpha1.KeyOperationAttestationObservedState {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.KeyOperationAttestationObservedState{}
	out.Format = direct.Enum_FromProto(mapCtx, in.GetFormat())
	out.Content = in.GetContent()
	out.CertChains = KeyOperationAttestation_CertificateChains_v1alpha1_FromProto(mapCtx, in.GetCertChains())
	return out
}
func KeyOperationAttestationObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.KeyOperationAttestationObservedState) *pb.KeyOperationAttestation {
	if in == nil {
		return nil
	}
	out := &pb.KeyOperationAttestation{}
	out.Format = direct.Enum_ToProto[pb.KeyOperationAttestation_AttestationFormat](mapCtx, in.Format)
	out.Content = in.Content
	out.CertChains = KeyOperationAttestation_CertificateChains_v1alpha1_ToProto(mapCtx, in.CertChains)
	return out
}
func KeyOperationAttestation_CertificateChains_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.KeyOperationAttestation_CertificateChains) *krmkmsv1alpha1.KeyOperationAttestation_CertificateChains {
	if in == nil {
		return nil
	}
	out := &krmkmsv1alpha1.KeyOperationAttestation_CertificateChains{}
	out.CaviumCerts = in.CaviumCerts
	out.GoogleCardCerts = in.GoogleCardCerts
	out.GooglePartitionCerts = in.GooglePartitionCerts
	return out
}
func KeyOperationAttestation_CertificateChains_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmkmsv1alpha1.KeyOperationAttestation_CertificateChains) *pb.KeyOperationAttestation_CertificateChains {
	if in == nil {
		return nil
	}
	out := &pb.KeyOperationAttestation_CertificateChains{}
	out.CaviumCerts = in.CaviumCerts
	out.GoogleCardCerts = in.GoogleCardCerts
	out.GooglePartitionCerts = in.GooglePartitionCerts
	return out
}
