// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: securitycenter.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.securitycenter.v1
// resource: SecurityCenterMuteConfig:MuteConfig
// resource: SecurityCenterBigQueryExport:BigQueryExport

package v1alpha1

/* unreachable type BigQueryExport
// +kcc:proto=google.cloud.securitycenter.v1.BigQueryExport
type BigQueryExport struct {
	// The relative resource name of this export. See:
	//  https://cloud.google.com/apis/design/resource_names#relative_resource_name.
	//  Example format:
	//  "organizations/{organization_id}/bigQueryExports/{export_id}" Example
	//  format: "folders/{folder_id}/bigQueryExports/{export_id}" Example format:
	//  "projects/{project_id}/bigQueryExports/{export_id}"
	//  This field is provided in responses, and is ignored when provided in create
	//  requests.
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.name
	Name *string `json:"name,omitempty"`

	// The description of the export (max of 1024 characters).
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.description
	Description *string `json:"description,omitempty"`

	// Expression that defines the filter to apply across create/update events
	//  of findings. The expression is a list of zero or more restrictions combined
	//  via logical operators `AND` and `OR`. Parentheses are supported, and `OR`
	//  has higher precedence than `AND`.
	//
	//  Restrictions have the form `<field> <operator> <value>` and may have a
	//  `-` character in front of them to indicate negation. The fields map to
	//  those defined in the corresponding resource.
	//
	//  The supported operators are:
	//
	//  * `=` for all value types.
	//  * `>`, `<`, `>=`, `<=` for integer values.
	//  * `:`, meaning substring matching, for strings.
	//
	//  The supported value types are:
	//
	//  * string literals in quotes.
	//  * integer literals without quotes.
	//  * boolean literals `true` and `false` without quotes.
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.filter
	Filter *string `json:"filter,omitempty"`

	// The dataset to write findings' updates to. Its format is
	//  "projects/[project_id]/datasets/[bigquery_dataset_id]".
	//  BigQuery Dataset unique ID  must contain only letters (a-z, A-Z), numbers
	//  (0-9), or underscores (_).
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.dataset
	Dataset *string `json:"dataset,omitempty"`
}
*/

/* unreachable type MuteConfig
// +kcc:proto=google.cloud.securitycenter.v1.MuteConfig
type MuteConfig struct {
	// This field will be ignored if provided on config creation. Format
	//  `organizations/{organization}/muteConfigs/{mute_config}`
	//  `folders/{folder}/muteConfigs/{mute_config}`
	//  `projects/{project}/muteConfigs/{mute_config}`
	//  `organizations/{organization}/locations/global/muteConfigs/{mute_config}`
	//  `folders/{folder}/locations/global/muteConfigs/{mute_config}`
	//  `projects/{project}/locations/global/muteConfigs/{mute_config}`
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.name
	Name *string `json:"name,omitempty"`

	// The human readable name to be displayed for the mute config.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.display_name
	DisplayName *string `json:"displayName,omitempty"`

	// A description of the mute config.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.description
	Description *string `json:"description,omitempty"`

	// Required. An expression that defines the filter to apply across
	//  create/update events of findings. While creating a filter string, be
	//  mindful of the scope in which the mute configuration is being created.
	//  E.g., If a filter contains project = X but is created under the project = Y
	//  scope, it might not match any findings.
	//
	//  The following field and operator combinations are supported:
	//
	//  * severity: `=`, `:`
	//  * category: `=`, `:`
	//  * resource.name: `=`, `:`
	//  * resource.project_name: `=`, `:`
	//  * resource.project_display_name: `=`, `:`
	//  * resource.folders.resource_folder: `=`, `:`
	//  * resource.parent_name: `=`, `:`
	//  * resource.parent_display_name: `=`, `:`
	//  * resource.type: `=`, `:`
	//  * finding_class: `=`, `:`
	//  * indicator.ip_addresses: `=`, `:`
	//  * indicator.domains: `=`, `:`
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.filter
	// +required
	Filter *string `json:"filter,omitempty"`

	// Optional. The type of the mute config, which determines what type of mute
	//  state the config affects. The static mute state takes precedence over the
	//  dynamic mute state. Immutable after creation. STATIC by default if not set
	//  during creation.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.type
	Type *string `json:"type,omitempty"`

	// Optional. The expiry of the mute config. Only applicable for dynamic
	//  configs. If the expiry is set, when the config expires, it is removed from
	//  all findings.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.expiry_time
	ExpiryTime *string `json:"expiryTime,omitempty"`
}
*/

/* unreachable type BigQueryExportObservedState
// +kcc:observedstate:proto=google.cloud.securitycenter.v1.BigQueryExport
type BigQueryExportObservedState struct {
	// Output only. The time at which the BigQuery export was created.
	//  This field is set by the server and will be ignored if provided on export
	//  on creation.
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. The most recent time at which the BigQuery export was updated.
	//  This field is set by the server and will be ignored if provided on export
	//  creation or update.
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.update_time
	UpdateTime *string `json:"updateTime,omitempty"`

	// Output only. Email address of the user who last edited the BigQuery export.
	//  This field is set by the server and will be ignored if provided on export
	//  creation or update.
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.most_recent_editor
	MostRecentEditor *string `json:"mostRecentEditor,omitempty"`

	// Output only. The service account that needs permission to create table and
	//  upload data to the BigQuery dataset.
	// +kcc:proto:field=google.cloud.securitycenter.v1.BigQueryExport.principal
	Principal *string `json:"principal,omitempty"`
}
*/

/* unreachable type MuteConfigObservedState
// +kcc:observedstate:proto=google.cloud.securitycenter.v1.MuteConfig
type MuteConfigObservedState struct {
	// Output only. The time at which the mute config was created.
	//  This field is set by the server and will be ignored if provided on config
	//  creation.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. The most recent time at which the mute config was updated.
	//  This field is set by the server and will be ignored if provided on config
	//  creation or update.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.update_time
	UpdateTime *string `json:"updateTime,omitempty"`

	// Output only. Email address of the user who last edited the mute config.
	//  This field is set by the server and will be ignored if provided on config
	//  creation or update.
	// +kcc:proto:field=google.cloud.securitycenter.v1.MuteConfig.most_recent_editor
	MostRecentEditor *string `json:"mostRecentEditor,omitempty"`
}
*/
