// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generatetypes

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/GoogleCloudPlatform/k8s-config-connector/dev/tools/controllerbuilder/pkg/annotations"
	"github.com/GoogleCloudPlatform/k8s-config-connector/dev/tools/controllerbuilder/pkg/codegen"
	"github.com/GoogleCloudPlatform/k8s-config-connector/dev/tools/controllerbuilder/pkg/commands/prunetypes"
	"github.com/GoogleCloudPlatform/k8s-config-connector/dev/tools/controllerbuilder/pkg/options"
	"github.com/GoogleCloudPlatform/k8s-config-connector/dev/tools/controllerbuilder/pkg/protoapi"
	"github.com/GoogleCloudPlatform/k8s-config-connector/dev/tools/controllerbuilder/scaffold"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/klog/v2"

	"github.com/spf13/cobra"
)

type GenerateCRDOptions struct {
	*options.GenerateOptions

	ServiceName string

	OutputAPIDirectory string
	SkipScaffoldFiles  bool

	Resources options.ResourceList

	PruneUnusedTypes bool

	EmitRequiredFromProto bool
	PrepopulateSpec       bool
	DetectOutputOnly      bool
	EmitPluralAcronyms    bool
	PlaceServerSetFields  bool
}

func (o *GenerateCRDOptions) InitDefaults() error {
	root, err := options.RepoRoot()
	if err != nil {
		return err
	}
	o.OutputAPIDirectory = root + "/apis/"
	o.PruneUnusedTypes = true
	return nil
}

func (o *GenerateCRDOptions) BindFlags(cmd *cobra.Command) {
	cmd.Flags().StringVarP(&o.ServiceName, "service", "s", o.ServiceName, "the GCP service name")

	cmd.Flags().StringVar(&o.OutputAPIDirectory, "output-api", o.OutputAPIDirectory, "base directory for writing APIs")
	cmd.Flags().Var(&o.Resources, "resource", "the KRM Kind and the equivalent proto resource separated with a colon.  e.g. for resource google.storage.v1.Bucket, the flag should be `StorageBucket:Bucket`.  Can be specified multiple times.")
	cmd.Flags().BoolVar(&o.SkipScaffoldFiles, "skip-scaffold-files", false, "skip generating scaffold files (types, refs, and identity) for all resources generated by this command")
	cmd.Flags().BoolVar(&o.PruneUnusedTypes, "prune-unused-types", o.PruneUnusedTypes, "prune unreachable types from generated files")
	cmd.Flags().BoolVar(&o.PrepopulateSpec, "prepopulate-spec", false, "fill the scaffolded Spec and ObservedState from the proto message instead of emitting a three-field stub, and record what still needs a human in apis/<service>/needs_judgement_call.txt. Opt in one service at a time")
	cmd.Flags().BoolVar(&o.EmitPluralAcronyms, "emit-plural-acronyms", false, "case plural acronyms as KRM conventions want, so related_uris becomes relatedURIs rather than relatedUris. Opt in one service at a time: it renames fields, which is a breaking change for a resource people already use")
	cmd.Flags().BoolVar(&o.DetectOutputOnly, "detect-output-only-in-comments", false, "report spec fields whose proto comment says \"Output only.\" while carrying no field_behavior annotation, to apis/<service>/detected_output_only_in_comments.txt. Reports only; moving them is a hand edit")
	cmd.Flags().BoolVar(&o.PlaceServerSetFields, "place-server-set-fields", false, "put a small allowlist of server-computed fields (createTime, uid, selfLink, etag and friends) into ObservedState when the proto carries no field_behavior anywhere, instead of leaving them in the Spec for a user to set. Each one is also recorded in apis/<service>/needs_judgement_call.txt. Opt in one service at a time: it moves fields between spec and status, which is a breaking change for a resource people already use")
	cmd.Flags().BoolVar(&o.EmitRequiredFromProto, "emit-required-from-proto", false, "emit // +required for fields the proto marks REQUIRED. Opt in one service at a time: turning it on for a resource people already use can tighten its CRD schema, because nested types are shared between spec and status")
}

func BuildCommand(baseOptions *options.GenerateOptions) *cobra.Command {
	opt := &GenerateCRDOptions{
		GenerateOptions: baseOptions,
	}

	if err := opt.InitDefaults(); err != nil {
		fmt.Fprintf(os.Stderr, "Error initializing defaults: %v\n", err)
		os.Exit(1)
	}

	cmd := &cobra.Command{
		Use:   "generate-types",
		Short: "generate KRM types for a proto service",
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if err := opt.loadAndApplyConfig(); err != nil {
				return err
			}
			return opt.validate()
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()
			if err := RunGenerateCRD(ctx, opt); err != nil {
				return err
			}
			return nil
		},
	}

	opt.BindFlags(cmd)

	return cmd
}

func RunGenerateCRD(ctx context.Context, o *GenerateCRDOptions) error {
	log := klog.FromContext(ctx)

	gv, err := schema.ParseGroupVersion(o.APIVersion)
	if err != nil {
		return fmt.Errorf("APIVersion %q is not valid: %w", o.APIVersion, err)
	}

	api, err := protoapi.LoadProto(o.GenerateOptions.ProtoSourcePath, o.GenerateOptions.ProtoOverlayPath)
	if err != nil {
		return fmt.Errorf("loading proto: %w", err)
	}

	goPackage := strings.TrimSuffix(gv.Group, ".cnrm.cloud.google.com") + "/" + gv.Version

	scaffolder := &scaffold.APIScaffolder{
		BaseDir:         o.OutputAPIDirectory,
		GoPackage:       goPackage,
		Group:           gv.Group,
		Version:         gv.Version,
		PackageProtoTag: o.ServiceName,
		// Without this the scaffolder cannot read google.api.resource, so every
		// resource is classified ParentUnknown and the collection segment is
		// guessed from the message name. The field was added with the parent-shape
		// work but never set here, so that work has never run for generate-types.
		Proto: api,
	}
	if scaffolder.DocFileNotExist() {
		if err := scaffolder.AddDocFile(); err != nil {
			return fmt.Errorf("add doc.go file: %w", err)
		}
	}
	if scaffolder.GroupVersionFileNotExist() {
		if err := scaffolder.AddGroupVersionFile(); err != nil {
			return fmt.Errorf("add groupversion_info.go file: %w", err)
		}
	}

	writeOptions := codegen.WriteOptions{
		EmitRequired:         o.EmitRequiredFromProto,
		EmitPluralAcronyms:   o.EmitPluralAcronyms,
		PlaceServerSetFields: o.PlaceServerSetFields,
	}

	typeGenerator := codegen.NewTypeGenerator(goPackage, o.OutputAPIDirectory, api)
	typeGenerator.WithIncludeSkippedOutput(o.GenerateOptions.IncludeSkippedOutput)
	typeGenerator.WithWriteOptions(writeOptions)
	// The scaffolder writes each Kind's struct after this generator runs, so
	// reserve those names now; a wipe-based regeneration means the files it will
	// write do not exist yet for findTypeDeclaration to find.
	for _, resource := range o.Resources {
		typeGenerator.WithReservedTypeNames(resource.Kind)
	}

	// Queue entries accumulate across every resource in this invocation and are
	// written once at the end, so a service's file is replaced wholesale rather
	// than appended to.
	var judgement []string
	// Candidates are collected per service and written once, like the queue above.
	var outputOnly []string

	resourceAnnotations := make([]string, 0, len(o.Resources))
	for _, resource := range o.Resources {
		resourceProtoFullName := resolveProtoFullName(api, o.ServiceName, resource)
		log.V(2).Info("visiting proto", "name", resourceProtoFullName)
		if err := typeGenerator.VisitProto(resourceProtoFullName); err != nil {
			return err
		}
		resourceAnnotations = append(resourceAnnotations, fmt.Sprintf("%s:%s", resource.Kind, resource.ProtoName))
	}

	generatedFileAnnotation := &annotations.FileAnnotation{
		Key: "+generated:types",
		Attributes: map[string][]string{
			"proto.service": {o.ServiceName},
			"krm.group":     {gv.Group},
			"krm.version":   {gv.Version},
			"resource":      resourceAnnotations,
		},
	}
	typeGenerator = typeGenerator.WithGeneratedFileAnnotation(generatedFileAnnotation)

	if err := typeGenerator.WriteVisitedMessages(); err != nil {
		return err
	}

	if err := typeGenerator.WriteOutputMessages(); err != nil {
		return err
	}

	for _, resource := range o.Resources { // A separate loop is needed to scaffold files AFTER all the visited messages have been generated.
		skipScaffold := o.SkipScaffoldFiles || resource.SkipScaffoldFiles
		if skipScaffold {
			log.Info("skipping scaffolding type, refs and identity files", "resource", resource.ProtoName)
		} else {
			if scaffolder.TypeFileExists(resource) {
				klog.V(1).Infof("file %s already exists, skipping\n", scaffolder.PathToTypeFile(resource))
			} else {
				var prepopulated *scaffold.PrepopulateResult
				if o.PrepopulateSpec {
					msg, err := resourceMessage(api, o.ServiceName, resource)
					if err != nil {
						return err
					}
					prepopulated, err = scaffold.PrepopulateSpec(msg, writeOptions)
					if err != nil {
						return fmt.Errorf("prepopulating spec for %s: %w", resource.Kind, err)
					}
					// The observed-state body needs what the type generator worked
					// out during the visit above, so it is filled here rather than
					// inside PrepopulateSpec. No entry means the proto marks nothing
					// OUTPUT_ONLY, and the struct is left empty.
					if o.DetectOutputOnly {
						if c := scaffold.DetectOutputOnlyInComments(msg); len(c) > 0 {
							outputOnly = append(outputOnly, scaffold.FormatOutputOnlyCandidates(resource.Kind, gv.Group, c))
							// Also into the queue. The report on its own is a file
							// nothing reads: the field is in the Spec, looks
							// generated, and nothing says it is in the wrong struct.
							// The queue is where a resource's outstanding decisions
							// are counted, so a finding that never reaches it is
							// indistinguishable from no finding at all.
							for _, cand := range c {
								// Named where the field belongs, not where it
								// currently sits. The entry exists to account for a
								// field absent from ObservedState, so pointing it at
								// .spec would never line up with what is missing.
								prepopulated.Judgement = append(prepopulated.Judgement, scaffold.JudgementItem{
									FieldPath: ".status.observedState." + strings.TrimPrefix(cand.FieldPath, ".spec."),
									Reason:    "output-only-in-comment-only",
									Detail:    "proto comment says output only but no field_behavior annotation, so it was generated into the Spec instead. Move it if the comment is right: " + cand.Comment,
								})
							}
						}
					}
					if details, ok := typeGenerator.OutputFieldsFor(string(msg.FullName())); ok {
						var obsJudgement []scaffold.JudgementItem
						prepopulated.ObservedStateFields, prepopulated.ExtraImports, obsJudgement =
							scaffold.PrepopulateObservedState(details, typeGenerator.ObservedStateMessages(), writeOptions)
						// Appended to the spec's items so one queue file covers the
						// whole resource, spec and status alike.
						prepopulated.Judgement = append(prepopulated.Judgement, obsJudgement...)
					}
				}
				if err := scaffolder.AddTypeFile(resource, prepopulated); err != nil {
					return fmt.Errorf("add type file %s: %w", scaffolder.PathToTypeFile(resource), err)
				}
				// After AddTypeFile, which is where decisions that depend on the
				// parent shape are recorded.
				if prepopulated != nil {
					judgement = append(judgement, scaffold.FormatJudgementEntries(resource.Kind, gv.Group, prepopulated.Judgement))
				}
			}
		}
	}

	if o.PrepopulateSpec {
		// Fields the generator could not type are recorded here rather than only
		// as a comment in generated source. They are absent from the CRD, so
		// leaving them unlisted makes a silent drop look like a complete resource.
		// Reported per service, since a nested message can be shared by several
		// resources and the generator has no single owner to attribute it to.
		// Written as comments, not entries. A nested message is shared by any
		// resource that references it, so there is no single Kind to attribute it
		// to -- and every non-comment line in this file suppresses [refs] for the
		// Kind it names, so a made-up Kind would quietly switch off a real check.
		if u := typeGenerator.UnsupportedFields(); len(u) > 0 {
			var b strings.Builder
			b.WriteString("\n# Fields dropped because the generator could not produce a Go type for\n")
			b.WriteString("# them. They are absent from the CRD. Shared nested messages, so they are\n")
			b.WriteString("# listed per service rather than against one Kind.\n")
			for _, f := range u {
				fmt.Fprintf(&b, "# dropped: %s.%s reason=%s\n", f.Message, f.Field, f.Reason)
			}
			judgement = append(judgement, b.String())
		}
		if err := writeJudgementQueue(o.OutputAPIDirectory, goPackage, judgement); err != nil {
			return fmt.Errorf("writing judgement queue: %w", err)
		}
	}

	if o.DetectOutputOnly {
		if err := writeOutputOnlyReport(o.OutputAPIDirectory, goPackage, outputOnly); err != nil {
			return fmt.Errorf("writing output-only report: %w", err)
		}
	}

	addCopyright := true
	writeEmptyFiles := true
	if err := typeGenerator.WriteFiles(addCopyright, writeEmptyFiles); err != nil {
		return err
	}

	if o.PruneUnusedTypes {
		pruneOpt := &prunetypes.PruneTypesOptions{
			GenerateOptions: o.GenerateOptions,
			Target:          filepath.Join(o.OutputAPIDirectory, goPackage),
		}
		if err := prunetypes.PruneTypes(ctx, pruneOpt); err != nil {
			return fmt.Errorf("pruning unreachable types: %w", err)
		}
	}

	return nil
}

func (o *GenerateCRDOptions) loadAndApplyConfig() error {
	if o.ConfigFilePath == "" {
		return nil
	}
	config, err := codegen.LoadConfig(o.ConfigFilePath)
	if err != nil {
		return fmt.Errorf("loading service config: %w", err)
	}
	if config == nil {
		return nil
	}

	o.ServiceName = config.Service
	o.APIVersion = config.APIVersion
	if o.ProtoOverlayPath == "" && config.ProtoOverlay != "" {
		if filepath.IsAbs(config.ProtoOverlay) {
			o.ProtoOverlayPath = config.ProtoOverlay
		} else {
			o.ProtoOverlayPath = filepath.Join(filepath.Dir(o.ConfigFilePath), config.ProtoOverlay)
		}
	}
	for _, res := range config.Resources {
		o.Resources = append(o.Resources, options.Resource{
			Kind:              res.Kind,
			ProtoName:         res.ProtoName,
			SkipScaffoldFiles: res.SkipScaffoldFiles,
		})
	}
	return nil
}

func (o *GenerateCRDOptions) validate() error {
	if o.ServiceName == "" {
		return fmt.Errorf("`--service` is required")
	}
	if o.GenerateOptions.ProtoSourcePath == "" {
		return fmt.Errorf("`--proto-source-path` is required")
	}
	if len(o.Resources) == 0 {
		return fmt.Errorf("`--resource` is required")
	}
	return nil
}

// resolveProtoFullName maps a --resource entry to a fully qualified proto message
// name, trying each comma-separated service in turn.
func resolveProtoFullName(api *protoapi.Proto, serviceName string, resource options.Resource) string {
	if strings.Contains(resource.ProtoName, ".") {
		return resource.ProtoName
	}
	// Collect every service the bare name resolves in, not just the first.
	// Taking the first silently is how NotebookInstanceV2 came to be generated
	// from notebooks.v1.Instance while its Kind and its upstream counterpart both
	// say v2: the block declares v1 and v2, both have an Instance, and v1 won.
	// The v1 message is shaped differently enough that 39 CRD fields went missing
	// without anything reporting a problem.
	var matches []string
	for _, svc := range strings.Split(serviceName, ",") {
		candidate := svc + "." + resource.ProtoName
		if _, err := api.Files().FindDescriptorByName(protoreflect.FullName(candidate)); err == nil {
			matches = append(matches, candidate)
		}
	}
	if len(matches) > 1 {
		klog.Warningf("%q resolves in %d of the declared services (%s); using %s. "+
			"Qualify the --resource proto name to choose deliberately.",
			resource.ProtoName, len(matches), strings.Join(matches, ", "), matches[0])
	}
	if len(matches) > 0 {
		return matches[0]
	}
	// Nothing matched, so fall back to the first service and let the caller's
	// lookup produce the error with the full name in it.
	return strings.Split(serviceName, ",")[0] + "." + resource.ProtoName
}

// resourceMessage looks up the descriptor for a --resource entry.
func resourceMessage(api *protoapi.Proto, serviceName string, resource options.Resource) (protoreflect.MessageDescriptor, error) {
	fullName := resolveProtoFullName(api, serviceName, resource)
	d, err := api.Files().FindDescriptorByName(protoreflect.FullName(fullName))
	if err != nil {
		return nil, fmt.Errorf("finding proto message %s: %w", fullName, err)
	}
	msg, ok := d.(protoreflect.MessageDescriptor)
	if !ok {
		return nil, fmt.Errorf("%s is not a message", fullName)
	}
	return msg, nil
}

// writeJudgementQueue records what the generator could not decide, for the
// service just generated. Written wholesale rather than appended so that
// re-running generation for a service does not accumulate duplicates.
func writeJudgementQueue(apiDir, goPackage string, entries []string) error {
	var body strings.Builder
	for _, e := range entries {
		body.WriteString(e)
	}
	if body.Len() == 0 {
		return nil
	}

	// The queue lives at apis/<service>/needs_judgement_call.txt, one level above
	// the version directory, because it is per-service rather than per-version.
	serviceDir := filepath.Dir(filepath.Join(apiDir, goPackage))
	path := filepath.Join(serviceDir, "needs_judgement_call.txt")

	header := "# Fields the generator emitted mechanically but cannot vouch for.\n" +
		"# Each entry needs a human decision: is it a reference, should it be omitted,\n" +
		"# should it be renamed for KRM conventions?\n" +
		"#\n" +
		"# While a resource has entries here, TestMissingRefs suppresses its [refs]\n" +
		"# findings. Clearing them graduates the resource and the ratchet applies.\n" +
		"\n"

	if err := os.MkdirAll(serviceDir, 0755); err != nil {
		return err
	}

	// Merge rather than truncate. The queue is per service but generate.sh calls
	// generate-types once per proto version -- discoveryengine twice,
	// networksecurity three times, dialogflow four -- and writing the file
	// outright meant the last call silently discarded every earlier call's
	// entries. That left 34 fields carrying a +kcc:guess marker in the types file
	// with nothing about them in the queue.
	//
	// Keyed on the whole line, so re-running is idempotent, and existing lines
	// come first so a hand-edited queue keeps its order.
	existing := ""
	if prior, err := os.ReadFile(path); err == nil {
		existing = string(prior)
	}
	seen := map[string]bool{}
	var out []string
	for _, line := range strings.Split(existing, "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if !seen[line] {
			seen[line] = true
			out = append(out, line)
		}
	}
	for _, line := range strings.Split(body.String(), "\n") {
		if line == "" {
			continue
		}
		if !seen[line] {
			seen[line] = true
			out = append(out, line)
		}
	}
	return os.WriteFile(path, []byte(header+strings.Join(out, "\n")+"\n"), 0644)
}

// writeOutputOnlyReport records fields the proto documents as output-only in
// prose while carrying no annotation to say so.
//
// Deliberately a separate file from needs_judgement_call.txt. That file drives
// [refs] suppression, and loadJudgementQueue keys off any non-comment line in
// it, so putting these entries there would quietly stop TestMissingRefs
// reporting on resources whose references are perfectly fine.
func writeOutputOnlyReport(apiDir, goPackage string, entries []string) error {
	var body strings.Builder
	for _, e := range entries {
		body.WriteString(e)
	}
	if body.Len() == 0 {
		return nil
	}

	serviceDir := filepath.Dir(filepath.Join(apiDir, goPackage))
	path := filepath.Join(serviceDir, "detected_output_only_in_comments.txt")

	header := "# Spec fields whose proto comment says \"Output only.\" but which carry no\n" +
		"# google.api.field_behavior annotation, so the generator could not place them\n" +
		"# in ObservedState by itself.\n" +
		"#\n" +
		"# This file reports; it changes nothing. To act on an entry, move the field\n" +
		"# out of the Spec struct and into the ObservedState struct in\n" +
		"# <kind>_types.go by hand.\n" +
		"\n"

	if err := os.MkdirAll(serviceDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(header+body.String()), 0644)
}
