// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: documentai.cnrm.cloud.google.com
// krm.version: v1beta1
// proto.service: google.cloud.documentai.v1

package documentai

import (
	pb "cloud.google.com/go/documentai/apiv1/documentaipb"
	krmdocumentaiv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/documentai/v1alpha1"
	krmdocumentaiv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/documentai/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func DocumentAIProcessorObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Processor) *krmdocumentaiv1alpha1.DocumentAIProcessorObservedState {
	if in == nil {
		return nil
	}
	out := &krmdocumentaiv1alpha1.DocumentAIProcessorObservedState{}
	// MISSING: Name
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.ProcessorVersionAliases = direct.Slice_FromProto(mapCtx, in.ProcessorVersionAliases, ProcessorVersionAlias_v1alpha1_FromProto)
	out.ProcessEndpoint = direct.LazyPtr(in.GetProcessEndpoint())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.SatisfiesPzs = direct.LazyPtr(in.GetSatisfiesPzs())
	out.SatisfiesPzi = direct.LazyPtr(in.GetSatisfiesPzi())
	return out
}
func DocumentAIProcessorObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmdocumentaiv1alpha1.DocumentAIProcessorObservedState) *pb.Processor {
	if in == nil {
		return nil
	}
	out := &pb.Processor{}
	// MISSING: Name
	out.State = direct.Enum_ToProto[pb.Processor_State](mapCtx, in.State)
	out.ProcessorVersionAliases = direct.Slice_ToProto(mapCtx, in.ProcessorVersionAliases, ProcessorVersionAlias_v1alpha1_ToProto)
	out.ProcessEndpoint = direct.ValueOf(in.ProcessEndpoint)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.SatisfiesPzs = direct.ValueOf(in.SatisfiesPzs)
	out.SatisfiesPzi = direct.ValueOf(in.SatisfiesPzi)
	return out
}
func DocumentAIProcessorSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Processor) *krmdocumentaiv1alpha1.DocumentAIProcessorSpec {
	if in == nil {
		return nil
	}
	out := &krmdocumentaiv1alpha1.DocumentAIProcessorSpec{}
	// MISSING: Name
	out.Type = direct.LazyPtr(in.GetType())
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	out.DefaultProcessorVersion = direct.LazyPtr(in.GetDefaultProcessorVersion())
	out.KMSKeyName = direct.LazyPtr(in.GetKmsKeyName())
	return out
}
func DocumentAIProcessorSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmdocumentaiv1alpha1.DocumentAIProcessorSpec) *pb.Processor {
	if in == nil {
		return nil
	}
	out := &pb.Processor{}
	// MISSING: Name
	out.Type = direct.ValueOf(in.Type)
	out.DisplayName = direct.ValueOf(in.DisplayName)
	out.DefaultProcessorVersion = direct.ValueOf(in.DefaultProcessorVersion)
	out.KmsKeyName = direct.ValueOf(in.KMSKeyName)
	return out
}
func DocumentAIProcessorVersionObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.ProcessorVersion) *krmdocumentaiv1beta1.DocumentAIProcessorVersionObservedState {
	if in == nil {
		return nil
	}
	out := &krmdocumentaiv1beta1.DocumentAIProcessorVersionObservedState{}
	// MISSING: Name
	// MISSING: DisplayName
	// MISSING: DocumentSchema
	// MISSING: State
	// MISSING: CreateTime
	// MISSING: LatestEvaluation
	// MISSING: KMSKeyName
	// MISSING: KMSKeyVersionName
	// MISSING: GoogleManaged
	// MISSING: DeprecationInfo
	// MISSING: ModelType
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	// MISSING: GenAiModelInfo
	return out
}
func DocumentAIProcessorVersionObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmdocumentaiv1beta1.DocumentAIProcessorVersionObservedState) *pb.ProcessorVersion {
	if in == nil {
		return nil
	}
	out := &pb.ProcessorVersion{}
	// MISSING: Name
	// MISSING: DisplayName
	// MISSING: DocumentSchema
	// MISSING: State
	// MISSING: CreateTime
	// MISSING: LatestEvaluation
	// MISSING: KMSKeyName
	// MISSING: KMSKeyVersionName
	// MISSING: GoogleManaged
	// MISSING: DeprecationInfo
	// MISSING: ModelType
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	// MISSING: GenAiModelInfo
	return out
}
func DocumentAIProcessorVersionSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.ProcessorVersion) *krmdocumentaiv1beta1.DocumentAIProcessorVersionSpec {
	if in == nil {
		return nil
	}
	out := &krmdocumentaiv1beta1.DocumentAIProcessorVersionSpec{}
	// MISSING: Name
	// MISSING: DisplayName
	// MISSING: DocumentSchema
	// MISSING: State
	// MISSING: CreateTime
	// MISSING: LatestEvaluation
	// MISSING: KMSKeyName
	// MISSING: KMSKeyVersionName
	// MISSING: GoogleManaged
	// MISSING: DeprecationInfo
	// MISSING: ModelType
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	// MISSING: GenAiModelInfo
	return out
}
func DocumentAIProcessorVersionSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmdocumentaiv1beta1.DocumentAIProcessorVersionSpec) *pb.ProcessorVersion {
	if in == nil {
		return nil
	}
	out := &pb.ProcessorVersion{}
	// MISSING: Name
	// MISSING: DisplayName
	// MISSING: DocumentSchema
	// MISSING: State
	// MISSING: CreateTime
	// MISSING: LatestEvaluation
	// MISSING: KMSKeyName
	// MISSING: KMSKeyVersionName
	// MISSING: GoogleManaged
	// MISSING: DeprecationInfo
	// MISSING: ModelType
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	// MISSING: GenAiModelInfo
	return out
}
func ProcessorVersionAlias_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ProcessorVersionAlias) *krmdocumentaiv1alpha1.ProcessorVersionAlias {
	if in == nil {
		return nil
	}
	out := &krmdocumentaiv1alpha1.ProcessorVersionAlias{}
	out.Alias = direct.LazyPtr(in.GetAlias())
	out.ProcessorVersion = direct.LazyPtr(in.GetProcessorVersion())
	return out
}
func ProcessorVersionAlias_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmdocumentaiv1alpha1.ProcessorVersionAlias) *pb.ProcessorVersionAlias {
	if in == nil {
		return nil
	}
	out := &pb.ProcessorVersionAlias{}
	out.Alias = direct.ValueOf(in.Alias)
	out.ProcessorVersion = direct.ValueOf(in.ProcessorVersion)
	return out
}
