// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var NetworkServicesWasmPluginGVK = GroupVersion.WithKind("NetworkServicesWasmPlugin")

// NetworkServicesWasmPluginSpec defines the desired state of NetworkServicesWasmPlugin
// +kcc:spec:proto=google.cloud.networkservices.v1.WasmPlugin
type NetworkServicesWasmPluginSpec struct {
	// The project that this resource belongs to.
	ProjectRef *refsv1beta1.ProjectRef `json:"projectRef"`

	// The location of this resource.
	// +kcc:guess=parent-location pattern=projects/{project}/locations/{location}/wasmPlugins/{wasm_plugin}
	Location *string `json:"location"`

	// The NetworkServicesWasmPlugin name. If not given, the metadata.name will be used.
	ResourceID *string `json:"resourceID,omitempty"`
	// Optional. A human-readable description of the resource.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.description
	Description *string `json:"description,omitempty"`

	// Optional. Set of labels associated with the `WasmPlugin` resource.
	//
	//  The format must comply with [the following
	//  requirements](/compute/docs/labeling-resources#requirements).
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.labels
	Labels map[string]string `json:"labels,omitempty"`

	// Optional. The ID of the `WasmPluginVersion` resource that is the
	//  currently serving one. The version referred to must be a child of this
	//  `WasmPlugin` resource.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.main_version_id
	MainVersionID *string `json:"mainVersionID,omitempty"`

	// Optional. Specifies the logging options for the activity performed by this
	//  plugin. If logging is enabled, plugin logs are exported to
	//  Cloud Logging.
	//  Note that the settings relate to the logs generated by using
	//  logging statements in your Wasm code.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.log_config
	LogConfig *WasmPlugin_LogConfig `json:"logConfig,omitempty"`

	// Optional. All versions of this `WasmPlugin` resource in the key-value
	//  format. The key is the resource ID, and the value is the `VersionDetails`
	//  object.
	//
	//  Lets you create or update a `WasmPlugin` resource and its versions in a
	//  single request. When the `main_version_id` field is not empty, it must
	//  point to one of the `VersionDetails` objects in the map.
	//
	//  If provided in a `PATCH` request, the new versions replace the
	//  previous set. Any version omitted from the `versions` field is removed.
	//  Because the `WasmPluginVersion` resource is immutable, if a
	//  `WasmPluginVersion` resource with the same name already exists and differs,
	//  the request fails.
	//
	//  Note: In a `GET` request, this field is populated only if the field
	//  `GetWasmPluginRequest.view` is set to `WASM_PLUGIN_VIEW_FULL`.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.versions
	Versions map[string]WasmPlugin_VersionDetails `json:"versions,omitempty"`
}

// NetworkServicesWasmPluginStatus defines the config connector machine state of NetworkServicesWasmPlugin
type NetworkServicesWasmPluginStatus struct {
	/* Conditions represent the latest available observations of the
	   object's current state. */
	Conditions []v1alpha1.Condition `json:"conditions,omitempty"`

	// ObservedGeneration is the generation of the resource that was most recently observed by the Config Connector controller. If this is equal to metadata.generation, then that means that the current reported status reflects the most recent desired state of the resource.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// A unique specifier for the NetworkServicesWasmPlugin resource in GCP.
	ExternalRef *string `json:"externalRef,omitempty"`

	// ObservedState is the state of the resource as most recently observed in GCP.
	ObservedState *NetworkServicesWasmPluginObservedState `json:"observedState,omitempty"`
}

// NetworkServicesWasmPluginObservedState is the state of the NetworkServicesWasmPlugin resource as most recently observed in GCP.
// +kcc:observedstate:proto=google.cloud.networkservices.v1.WasmPlugin
type NetworkServicesWasmPluginObservedState struct {
	// Output only. The timestamp when the resource was created.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.create_time
	CreateTime *string `json:"createTime,omitempty"`

	// Output only. The timestamp when the resource was updated.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.update_time
	UpdateTime *string `json:"updateTime,omitempty"`

	// Output only. List of all
	//  [extensions](https://cloud.google.com/service-extensions/docs/overview)
	//  that use this `WasmPlugin` resource.
	// +kcc:proto:field=google.cloud.networkservices.v1.WasmPlugin.used_by
	UsedBy []WasmPlugin_UsedByObservedState `json:"usedBy,omitempty"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:categories=gcp,shortName=gcpnetworkserviceswasmplugin;gcpnetworkserviceswasmplugins
// +kubebuilder:subresource:status
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/managed-by-kcc=true"
// +kubebuilder:metadata:labels="cnrm.cloud.google.com/system=true"
// +kubebuilder:printcolumn:name="Age",JSONPath=".metadata.creationTimestamp",type="date"
// +kubebuilder:printcolumn:name="Ready",JSONPath=".status.conditions[?(@.type=='Ready')].status",type="string",description="When 'True', the most recent reconcile of the resource succeeded"
// +kubebuilder:printcolumn:name="Status",JSONPath=".status.conditions[?(@.type=='Ready')].reason",type="string",description="The reason for the value in 'Ready'"
// +kubebuilder:printcolumn:name="Status Age",JSONPath=".status.conditions[?(@.type=='Ready')].lastTransitionTime",type="date",description="The last transition time for the value in 'Status'"

// NetworkServicesWasmPlugin is the Schema for the NetworkServicesWasmPlugin API
// +k8s:openapi-gen=true
type NetworkServicesWasmPlugin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// +required
	Spec   NetworkServicesWasmPluginSpec   `json:"spec,omitempty"`
	Status NetworkServicesWasmPluginStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// NetworkServicesWasmPluginList contains a list of NetworkServicesWasmPlugin
type NetworkServicesWasmPluginList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkServicesWasmPlugin `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NetworkServicesWasmPlugin{}, &NetworkServicesWasmPluginList{})
}
