// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: bigqueryreservation.cnrm.cloud.google.com
// krm.version: v1beta1
// proto.service: google.cloud.bigquery.reservation.v1

package bigqueryreservation

import (
	pb "cloud.google.com/go/bigquery/reservation/apiv1/reservationpb"
	krmbigqueryreservationv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/bigqueryreservation/v1alpha1"
	krmbigqueryreservationv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/bigqueryreservation/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func BigQueryReservationAssignmentObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Assignment) *krmbigqueryreservationv1beta1.BigQueryReservationAssignmentObservedState {
	if in == nil {
		return nil
	}
	out := &krmbigqueryreservationv1beta1.BigQueryReservationAssignmentObservedState{}
	// MISSING: Name
	// MISSING: Assignee
	// MISSING: JobType
	// MISSING: State
	// MISSING: EnableGeminiInBigquery
	return out
}
func BigQueryReservationAssignmentObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmbigqueryreservationv1beta1.BigQueryReservationAssignmentObservedState) *pb.Assignment {
	if in == nil {
		return nil
	}
	out := &pb.Assignment{}
	// MISSING: Name
	// MISSING: Assignee
	// MISSING: JobType
	// MISSING: State
	// MISSING: EnableGeminiInBigquery
	return out
}

/* found existing non-generated mapping function "BigQueryReservationAssignmentSpec_v1beta1_FromProto", skipping
func BigQueryReservationAssignmentSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Assignment) *krmbigqueryreservationv1beta1.BigQueryReservationAssignmentSpec {
	if in == nil {
		return nil
	}
	out := &krmbigqueryreservationv1beta1.BigQueryReservationAssignmentSpec{}
	// MISSING: Name
	// MISSING: Assignee
	// MISSING: JobType
	// MISSING: State
	// MISSING: EnableGeminiInBigquery
	return out
}
*/

/*
found existing non-generated mapping function "BigQueryReservationAssignmentSpec_v1beta1_ToProto", skipping

	func BigQueryReservationAssignmentSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmbigqueryreservationv1beta1.BigQueryReservationAssignmentSpec) *pb.Assignment {
		if in == nil {
			return nil
		}
		out := &pb.Assignment{}
		// MISSING: Name
		// MISSING: Assignee
		// MISSING: JobType
		// MISSING: State
		// MISSING: EnableGeminiInBigquery
		return out
	}
*/
func BigQueryReservationCapacityCommitmentObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CapacityCommitment) *krmbigqueryreservationv1alpha1.BigQueryReservationCapacityCommitmentObservedState {
	if in == nil {
		return nil
	}
	out := &krmbigqueryreservationv1alpha1.BigQueryReservationCapacityCommitmentObservedState{}
	// MISSING: Name
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.CommitmentStartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCommitmentStartTime())
	out.CommitmentEndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCommitmentEndTime())
	out.FailureStatus = direct.Status_FromProto(mapCtx, in.GetFailureStatus())
	out.IsFlatRate = direct.LazyPtr(in.GetIsFlatRate())
	return out
}
func BigQueryReservationCapacityCommitmentObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmbigqueryreservationv1alpha1.BigQueryReservationCapacityCommitmentObservedState) *pb.CapacityCommitment {
	if in == nil {
		return nil
	}
	out := &pb.CapacityCommitment{}
	// MISSING: Name
	out.State = direct.Enum_ToProto[pb.CapacityCommitment_State](mapCtx, in.State)
	out.CommitmentStartTime = direct.StringTimestamp_ToProto(mapCtx, in.CommitmentStartTime)
	out.CommitmentEndTime = direct.StringTimestamp_ToProto(mapCtx, in.CommitmentEndTime)
	out.FailureStatus = direct.Status_ToProto(mapCtx, in.FailureStatus)
	out.IsFlatRate = direct.ValueOf(in.IsFlatRate)
	return out
}
func BigQueryReservationCapacityCommitmentSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CapacityCommitment) *krmbigqueryreservationv1alpha1.BigQueryReservationCapacityCommitmentSpec {
	if in == nil {
		return nil
	}
	out := &krmbigqueryreservationv1alpha1.BigQueryReservationCapacityCommitmentSpec{}
	// MISSING: Name
	out.SlotCount = direct.LazyPtr(in.GetSlotCount())
	out.Plan = direct.Enum_FromProto(mapCtx, in.GetPlan())
	out.RenewalPlan = direct.Enum_FromProto(mapCtx, in.GetRenewalPlan())
	out.MultiRegionAuxiliary = direct.LazyPtr(in.GetMultiRegionAuxiliary())
	out.Edition = direct.Enum_FromProto(mapCtx, in.GetEdition())
	return out
}
func BigQueryReservationCapacityCommitmentSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmbigqueryreservationv1alpha1.BigQueryReservationCapacityCommitmentSpec) *pb.CapacityCommitment {
	if in == nil {
		return nil
	}
	out := &pb.CapacityCommitment{}
	// MISSING: Name
	out.SlotCount = direct.ValueOf(in.SlotCount)
	out.Plan = direct.Enum_ToProto[pb.CapacityCommitment_CommitmentPlan](mapCtx, in.Plan)
	out.RenewalPlan = direct.Enum_ToProto[pb.CapacityCommitment_CommitmentPlan](mapCtx, in.RenewalPlan)
	out.MultiRegionAuxiliary = direct.ValueOf(in.MultiRegionAuxiliary)
	out.Edition = direct.Enum_ToProto[pb.Edition](mapCtx, in.Edition)
	return out
}

/* found existing non-generated mapping function "BigQueryReservationReservationObservedState_v1beta1_FromProto", skipping
func BigQueryReservationReservationObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Reservation) *krmbigqueryreservationv1beta1.BigQueryReservationReservationObservedState {
	if in == nil {
		return nil
	}
	out := &krmbigqueryreservationv1beta1.BigQueryReservationReservationObservedState{}
	// MISSING: Name
	// MISSING: SlotCapacity
	// MISSING: IgnoreIdleSlots
	// MISSING: Autoscale
	// MISSING: Concurrency
	// MISSING: CreationTime
	// MISSING: UpdateTime
	// MISSING: MultiRegionAuxiliary
	// MISSING: Edition
	// MISSING: PrimaryLocation
	// MISSING: SecondaryLocation
	// MISSING: OriginalPrimaryLocation
	// MISSING: MaxSlots
	// MISSING: ScalingMode
	// MISSING: ReplicationStatus
	return out
}
*/

/* found existing non-generated mapping function "BigQueryReservationReservationObservedState_v1beta1_ToProto", skipping
func BigQueryReservationReservationObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmbigqueryreservationv1beta1.BigQueryReservationReservationObservedState) *pb.Reservation {
	if in == nil {
		return nil
	}
	out := &pb.Reservation{}
	// MISSING: Name
	// MISSING: SlotCapacity
	// MISSING: IgnoreIdleSlots
	// MISSING: Autoscale
	// MISSING: Concurrency
	// MISSING: CreationTime
	// MISSING: UpdateTime
	// MISSING: MultiRegionAuxiliary
	// MISSING: Edition
	// MISSING: PrimaryLocation
	// MISSING: SecondaryLocation
	// MISSING: OriginalPrimaryLocation
	// MISSING: MaxSlots
	// MISSING: ScalingMode
	// MISSING: ReplicationStatus
	return out
}
*/

/* found existing non-generated mapping function "BigQueryReservationReservationSpec_v1beta1_FromProto", skipping
func BigQueryReservationReservationSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Reservation) *krmbigqueryreservationv1beta1.BigQueryReservationReservationSpec {
	if in == nil {
		return nil
	}
	out := &krmbigqueryreservationv1beta1.BigQueryReservationReservationSpec{}
	// MISSING: Name
	// MISSING: SlotCapacity
	// MISSING: IgnoreIdleSlots
	// MISSING: Autoscale
	// MISSING: Concurrency
	// MISSING: CreationTime
	// MISSING: UpdateTime
	// MISSING: MultiRegionAuxiliary
	// MISSING: Edition
	// MISSING: PrimaryLocation
	// MISSING: SecondaryLocation
	// MISSING: OriginalPrimaryLocation
	// MISSING: MaxSlots
	// MISSING: ScalingMode
	// MISSING: ReplicationStatus
	return out
}
*/

/* found existing non-generated mapping function "BigQueryReservationReservationSpec_v1beta1_ToProto", skipping
func BigQueryReservationReservationSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmbigqueryreservationv1beta1.BigQueryReservationReservationSpec) *pb.Reservation {
	if in == nil {
		return nil
	}
	out := &pb.Reservation{}
	// MISSING: Name
	// MISSING: SlotCapacity
	// MISSING: IgnoreIdleSlots
	// MISSING: Autoscale
	// MISSING: Concurrency
	// MISSING: CreationTime
	// MISSING: UpdateTime
	// MISSING: MultiRegionAuxiliary
	// MISSING: Edition
	// MISSING: PrimaryLocation
	// MISSING: SecondaryLocation
	// MISSING: OriginalPrimaryLocation
	// MISSING: MaxSlots
	// MISSING: ScalingMode
	// MISSING: ReplicationStatus
	return out
}
*/
