// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: clouddeploy.cnrm.cloud.google.com
// krm.version: v1beta1
// proto.service: google.cloud.deploy.v1

package clouddeploy

import (
	pb "cloud.google.com/go/deploy/apiv1/deploypb"
	krmclouddeployv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/clouddeploy/v1alpha1"
	krmclouddeployv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/clouddeploy/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
	dayofweekpb "google.golang.org/genproto/googleapis/type/dayofweek"
)

func AdvanceRolloutRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.AdvanceRolloutRuleObservedState) *pb.AdvanceRolloutRule {
	if in == nil {
		return nil
	}
	out := &pb.AdvanceRolloutRule{}
	// MISSING: ID
	// MISSING: SourcePhases
	// MISSING: Wait
	out.Condition = AutomationRuleConditionObservedState_v1alpha1_ToProto(mapCtx, in.Condition)
	return out
}
func AnthosCluster_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.AnthosCluster) *krmclouddeployv1alpha1.AnthosCluster {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.AnthosCluster{}
	out.Membership = direct.LazyPtr(in.GetMembership())
	return out
}
func AnthosCluster_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.AnthosCluster) *pb.AnthosCluster {
	if in == nil {
		return nil
	}
	out := &pb.AnthosCluster{}
	out.Membership = direct.ValueOf(in.Membership)
	return out
}
func AutomationRuleConditionObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.AutomationRuleCondition) *krmclouddeployv1alpha1.AutomationRuleConditionObservedState {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.AutomationRuleConditionObservedState{}
	out.TargetsPresentCondition = TargetsPresentCondition_v1alpha1_FromProto(mapCtx, in.GetTargetsPresentCondition())
	out.TimedPromoteReleaseCondition = TimedPromoteReleaseConditionObservedState_v1alpha1_FromProto(mapCtx, in.GetTimedPromoteReleaseCondition())
	return out
}
func AutomationRuleConditionObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.AutomationRuleConditionObservedState) *pb.AutomationRuleCondition {
	if in == nil {
		return nil
	}
	out := &pb.AutomationRuleCondition{}
	out.TargetsPresentCondition = TargetsPresentCondition_v1alpha1_ToProto(mapCtx, in.TargetsPresentCondition)
	if oneof := TimedPromoteReleaseConditionObservedState_v1alpha1_ToProto(mapCtx, in.TimedPromoteReleaseCondition); oneof != nil {
		out.RuleTypeCondition = &pb.AutomationRuleCondition_TimedPromoteReleaseCondition{TimedPromoteReleaseCondition: oneof}
	}
	return out
}
func AutomationRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.AutomationRuleObservedState) *pb.AutomationRule {
	if in == nil {
		return nil
	}
	out := &pb.AutomationRule{}
	if oneof := PromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx, in.PromoteReleaseRule); oneof != nil {
		out.Rule = &pb.AutomationRule_PromoteReleaseRule{PromoteReleaseRule: oneof}
	}
	if oneof := AdvanceRolloutRuleObservedState_v1alpha1_ToProto(mapCtx, in.AdvanceRolloutRule); oneof != nil {
		out.Rule = &pb.AutomationRule_AdvanceRolloutRule{AdvanceRolloutRule: oneof}
	}
	if oneof := RepairRolloutRuleObservedState_v1alpha1_ToProto(mapCtx, in.RepairRolloutRule); oneof != nil {
		out.Rule = &pb.AutomationRule_RepairRolloutRule{RepairRolloutRule: oneof}
	}
	if oneof := TimedPromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx, in.TimedPromoteReleaseRule); oneof != nil {
		out.Rule = &pb.AutomationRule_TimedPromoteReleaseRule{TimedPromoteReleaseRule: oneof}
	}
	return out
}
func CloudDeployCustomTargetTypeObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTargetType) *krmclouddeployv1alpha1.CloudDeployCustomTargetTypeObservedState {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CloudDeployCustomTargetTypeObservedState{}
	// MISSING: Name
	out.CustomTargetTypeID = direct.LazyPtr(in.GetCustomTargetTypeId())
	out.Uid = direct.LazyPtr(in.GetUid())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	return out
}
func CloudDeployCustomTargetTypeObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CloudDeployCustomTargetTypeObservedState) *pb.CustomTargetType {
	if in == nil {
		return nil
	}
	out := &pb.CustomTargetType{}
	// MISSING: Name
	out.CustomTargetTypeId = direct.ValueOf(in.CustomTargetTypeID)
	out.Uid = direct.ValueOf(in.Uid)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func CloudDeployCustomTargetTypeSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTargetType) *krmclouddeployv1alpha1.CloudDeployCustomTargetTypeSpec {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CloudDeployCustomTargetTypeSpec{}
	// MISSING: Name
	out.Description = direct.LazyPtr(in.GetDescription())
	out.Annotations = in.Annotations
	out.Labels = in.Labels
	out.Etag = direct.LazyPtr(in.GetEtag())
	out.CustomActions = CustomTargetSkaffoldActions_v1alpha1_FromProto(mapCtx, in.GetCustomActions())
	return out
}
func CloudDeployCustomTargetTypeSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CloudDeployCustomTargetTypeSpec) *pb.CustomTargetType {
	if in == nil {
		return nil
	}
	out := &pb.CustomTargetType{}
	// MISSING: Name
	out.Description = direct.ValueOf(in.Description)
	out.Annotations = in.Annotations
	out.Labels = in.Labels
	out.Etag = direct.ValueOf(in.Etag)
	if oneof := CustomTargetSkaffoldActions_v1alpha1_ToProto(mapCtx, in.CustomActions); oneof != nil {
		out.Definition = &pb.CustomTargetType_CustomActions{CustomActions: oneof}
	}
	return out
}
func CloudDeployDeliveryPipelineObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.DeliveryPipeline) *krmclouddeployv1beta1.CloudDeployDeliveryPipelineObservedState {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.CloudDeployDeliveryPipelineObservedState{}
	// MISSING: Name
	// MISSING: Uid
	// MISSING: Description
	// MISSING: Annotations
	// MISSING: Labels
	// MISSING: CreateTime
	// MISSING: UpdateTime
	// MISSING: SerialPipeline
	// MISSING: Condition
	// MISSING: Etag
	// MISSING: Suspended
	return out
}
func CloudDeployDeliveryPipelineObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.CloudDeployDeliveryPipelineObservedState) *pb.DeliveryPipeline {
	if in == nil {
		return nil
	}
	out := &pb.DeliveryPipeline{}
	// MISSING: Name
	// MISSING: Uid
	// MISSING: Description
	// MISSING: Annotations
	// MISSING: Labels
	// MISSING: CreateTime
	// MISSING: UpdateTime
	// MISSING: SerialPipeline
	// MISSING: Condition
	// MISSING: Etag
	// MISSING: Suspended
	return out
}
func CloudDeployDeliveryPipelineSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.DeliveryPipeline) *krmclouddeployv1beta1.CloudDeployDeliveryPipelineSpec {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1beta1.CloudDeployDeliveryPipelineSpec{}
	// MISSING: Name
	// MISSING: Uid
	// MISSING: Description
	// MISSING: Annotations
	// MISSING: Labels
	// MISSING: CreateTime
	// MISSING: UpdateTime
	// MISSING: SerialPipeline
	// MISSING: Condition
	// MISSING: Etag
	// MISSING: Suspended
	return out
}
func CloudDeployDeliveryPipelineSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1beta1.CloudDeployDeliveryPipelineSpec) *pb.DeliveryPipeline {
	if in == nil {
		return nil
	}
	out := &pb.DeliveryPipeline{}
	// MISSING: Name
	// MISSING: Uid
	// MISSING: Description
	// MISSING: Annotations
	// MISSING: Labels
	// MISSING: CreateTime
	// MISSING: UpdateTime
	// MISSING: SerialPipeline
	// MISSING: Condition
	// MISSING: Etag
	// MISSING: Suspended
	return out
}
func CloudDeployDeployPolicyObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeployPolicy) *krmclouddeployv1alpha1.CloudDeployDeployPolicyObservedState {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CloudDeployDeployPolicyObservedState{}
	// MISSING: Name
	out.Uid = direct.LazyPtr(in.GetUid())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	return out
}
func CloudDeployDeployPolicyObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CloudDeployDeployPolicyObservedState) *pb.DeployPolicy {
	if in == nil {
		return nil
	}
	out := &pb.DeployPolicy{}
	// MISSING: Name
	out.Uid = direct.ValueOf(in.Uid)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func CloudDeployDeployPolicySpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeployPolicy) *krmclouddeployv1alpha1.CloudDeployDeployPolicySpec {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CloudDeployDeployPolicySpec{}
	// MISSING: Name
	out.Description = direct.LazyPtr(in.GetDescription())
	out.Annotations = in.Annotations
	out.Labels = in.Labels
	out.Suspended = direct.LazyPtr(in.GetSuspended())
	out.Selectors = direct.Slice_FromProto(mapCtx, in.Selectors, DeployPolicyResourceSelector_v1alpha1_FromProto)
	out.Rules = direct.Slice_FromProto(mapCtx, in.Rules, PolicyRule_v1alpha1_FromProto)
	out.Etag = direct.LazyPtr(in.GetEtag())
	return out
}
func CloudDeployDeployPolicySpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CloudDeployDeployPolicySpec) *pb.DeployPolicy {
	if in == nil {
		return nil
	}
	out := &pb.DeployPolicy{}
	// MISSING: Name
	out.Description = direct.ValueOf(in.Description)
	out.Annotations = in.Annotations
	out.Labels = in.Labels
	out.Suspended = direct.ValueOf(in.Suspended)
	out.Selectors = direct.Slice_ToProto(mapCtx, in.Selectors, DeployPolicyResourceSelector_v1alpha1_ToProto)
	out.Rules = direct.Slice_ToProto(mapCtx, in.Rules, PolicyRule_v1alpha1_ToProto)
	out.Etag = direct.ValueOf(in.Etag)
	return out
}
func CloudRunLocation_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CloudRunLocation) *krmclouddeployv1alpha1.CloudRunLocation {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CloudRunLocation{}
	out.Location = direct.LazyPtr(in.GetLocation())
	return out
}
func CloudRunLocation_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CloudRunLocation) *pb.CloudRunLocation {
	if in == nil {
		return nil
	}
	out := &pb.CloudRunLocation{}
	out.Location = direct.ValueOf(in.Location)
	return out
}
func CustomTarget_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTarget) *krmclouddeployv1alpha1.CustomTarget {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CustomTarget{}
	out.CustomTargetType = direct.LazyPtr(in.GetCustomTargetType())
	return out
}
func CustomTarget_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CustomTarget) *pb.CustomTarget {
	if in == nil {
		return nil
	}
	out := &pb.CustomTarget{}
	out.CustomTargetType = direct.ValueOf(in.CustomTargetType)
	return out
}
func CustomTargetSkaffoldActions_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomTargetSkaffoldActions) *krmclouddeployv1alpha1.CustomTargetSkaffoldActions {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.CustomTargetSkaffoldActions{}
	out.RenderAction = direct.LazyPtr(in.GetRenderAction())
	out.DeployAction = direct.LazyPtr(in.GetDeployAction())
	out.IncludeSkaffoldModules = direct.Slice_FromProto(mapCtx, in.IncludeSkaffoldModules, SkaffoldModules_v1alpha1_FromProto)
	return out
}
func CustomTargetSkaffoldActions_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.CustomTargetSkaffoldActions) *pb.CustomTargetSkaffoldActions {
	if in == nil {
		return nil
	}
	out := &pb.CustomTargetSkaffoldActions{}
	out.RenderAction = direct.ValueOf(in.RenderAction)
	out.DeployAction = direct.ValueOf(in.DeployAction)
	out.IncludeSkaffoldModules = direct.Slice_ToProto(mapCtx, in.IncludeSkaffoldModules, SkaffoldModules_v1alpha1_ToProto)
	return out
}
func DefaultPool_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DefaultPool) *krmclouddeployv1alpha1.DefaultPool {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.DefaultPool{}
	out.ServiceAccount = direct.LazyPtr(in.GetServiceAccount())
	out.ArtifactStorage = direct.LazyPtr(in.GetArtifactStorage())
	return out
}
func DefaultPool_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.DefaultPool) *pb.DefaultPool {
	if in == nil {
		return nil
	}
	out := &pb.DefaultPool{}
	out.ServiceAccount = direct.ValueOf(in.ServiceAccount)
	out.ArtifactStorage = direct.ValueOf(in.ArtifactStorage)
	return out
}
func DeliveryPipelineAttribute_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeliveryPipelineAttribute) *krmclouddeployv1alpha1.DeliveryPipelineAttribute {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.DeliveryPipelineAttribute{}
	out.ID = direct.LazyPtr(in.GetId())
	out.Labels = in.Labels
	return out
}
func DeliveryPipelineAttribute_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.DeliveryPipelineAttribute) *pb.DeliveryPipelineAttribute {
	if in == nil {
		return nil
	}
	out := &pb.DeliveryPipelineAttribute{}
	out.Id = direct.ValueOf(in.ID)
	out.Labels = in.Labels
	return out
}
func DeployPolicyResourceSelector_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeployPolicyResourceSelector) *krmclouddeployv1alpha1.DeployPolicyResourceSelector {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.DeployPolicyResourceSelector{}
	out.DeliveryPipeline = DeliveryPipelineAttribute_v1alpha1_FromProto(mapCtx, in.GetDeliveryPipeline())
	out.Target = TargetAttribute_v1alpha1_FromProto(mapCtx, in.GetTarget())
	return out
}
func DeployPolicyResourceSelector_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.DeployPolicyResourceSelector) *pb.DeployPolicyResourceSelector {
	if in == nil {
		return nil
	}
	out := &pb.DeployPolicyResourceSelector{}
	out.DeliveryPipeline = DeliveryPipelineAttribute_v1alpha1_ToProto(mapCtx, in.DeliveryPipeline)
	out.Target = TargetAttribute_v1alpha1_ToProto(mapCtx, in.Target)
	return out
}
func ExecutionConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ExecutionConfig) *krmclouddeployv1alpha1.ExecutionConfig {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.ExecutionConfig{}
	out.Usages = direct.EnumSlice_FromProto(mapCtx, in.Usages)
	out.DefaultPool = DefaultPool_v1alpha1_FromProto(mapCtx, in.GetDefaultPool())
	out.PrivatePool = PrivatePool_v1alpha1_FromProto(mapCtx, in.GetPrivatePool())
	out.WorkerPool = direct.LazyPtr(in.GetWorkerPool())
	out.ServiceAccount = direct.LazyPtr(in.GetServiceAccount())
	out.ArtifactStorage = direct.LazyPtr(in.GetArtifactStorage())
	out.ExecutionTimeout = direct.StringDuration_FromProto(mapCtx, in.GetExecutionTimeout())
	out.Verbose = direct.LazyPtr(in.GetVerbose())
	return out
}
func ExecutionConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.ExecutionConfig) *pb.ExecutionConfig {
	if in == nil {
		return nil
	}
	out := &pb.ExecutionConfig{}
	out.Usages = direct.EnumSlice_ToProto[pb.ExecutionConfig_ExecutionEnvironmentUsage](mapCtx, in.Usages)
	if oneof := DefaultPool_v1alpha1_ToProto(mapCtx, in.DefaultPool); oneof != nil {
		out.ExecutionEnvironment = &pb.ExecutionConfig_DefaultPool{DefaultPool: oneof}
	}
	if oneof := PrivatePool_v1alpha1_ToProto(mapCtx, in.PrivatePool); oneof != nil {
		out.ExecutionEnvironment = &pb.ExecutionConfig_PrivatePool{PrivatePool: oneof}
	}
	out.WorkerPool = direct.ValueOf(in.WorkerPool)
	out.ServiceAccount = direct.ValueOf(in.ServiceAccount)
	out.ArtifactStorage = direct.ValueOf(in.ArtifactStorage)
	out.ExecutionTimeout = direct.StringDuration_ToProto(mapCtx, in.ExecutionTimeout)
	out.Verbose = direct.ValueOf(in.Verbose)
	return out
}
func OneTimeWindow_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.OneTimeWindow) *krmclouddeployv1alpha1.OneTimeWindow {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.OneTimeWindow{}
	out.StartDate = Date_v1alpha1_FromProto(mapCtx, in.GetStartDate())
	out.StartTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetStartTime())
	out.EndDate = Date_v1alpha1_FromProto(mapCtx, in.GetEndDate())
	out.EndTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetEndTime())
	return out
}
func OneTimeWindow_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.OneTimeWindow) *pb.OneTimeWindow {
	if in == nil {
		return nil
	}
	out := &pb.OneTimeWindow{}
	out.StartDate = Date_v1alpha1_ToProto(mapCtx, in.StartDate)
	out.StartTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.StartTime)
	out.EndDate = Date_v1alpha1_ToProto(mapCtx, in.EndDate)
	out.EndTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.EndTime)
	return out
}
func PolicyRule_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PolicyRule) *krmclouddeployv1alpha1.PolicyRule {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.PolicyRule{}
	out.RolloutRestriction = RolloutRestriction_v1alpha1_FromProto(mapCtx, in.GetRolloutRestriction())
	return out
}
func PolicyRule_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.PolicyRule) *pb.PolicyRule {
	if in == nil {
		return nil
	}
	out := &pb.PolicyRule{}
	if oneof := RolloutRestriction_v1alpha1_ToProto(mapCtx, in.RolloutRestriction); oneof != nil {
		out.Rule = &pb.PolicyRule_RolloutRestriction{RolloutRestriction: oneof}
	}
	return out
}
func PrivatePool_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PrivatePool) *krmclouddeployv1alpha1.PrivatePool {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.PrivatePool{}
	out.WorkerPool = direct.LazyPtr(in.GetWorkerPool())
	out.ServiceAccount = direct.LazyPtr(in.GetServiceAccount())
	out.ArtifactStorage = direct.LazyPtr(in.GetArtifactStorage())
	return out
}
func PrivatePool_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.PrivatePool) *pb.PrivatePool {
	if in == nil {
		return nil
	}
	out := &pb.PrivatePool{}
	out.WorkerPool = direct.ValueOf(in.WorkerPool)
	out.ServiceAccount = direct.ValueOf(in.ServiceAccount)
	out.ArtifactStorage = direct.ValueOf(in.ArtifactStorage)
	return out
}
func PromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.PromoteReleaseRuleObservedState) *pb.PromoteReleaseRule {
	if in == nil {
		return nil
	}
	out := &pb.PromoteReleaseRule{}
	// MISSING: ID
	// MISSING: Wait
	// MISSING: DestinationTargetID
	out.Condition = AutomationRuleConditionObservedState_v1alpha1_ToProto(mapCtx, in.Condition)
	// MISSING: DestinationPhase
	return out
}
func RepairRolloutRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.RepairRolloutRuleObservedState) *pb.RepairRolloutRule {
	if in == nil {
		return nil
	}
	out := &pb.RepairRolloutRule{}
	// MISSING: ID
	// MISSING: Phases
	// MISSING: Jobs
	out.Condition = AutomationRuleConditionObservedState_v1alpha1_ToProto(mapCtx, in.Condition)
	// MISSING: RepairPhases
	return out
}
func RolloutRestriction_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.RolloutRestriction) *krmclouddeployv1alpha1.RolloutRestriction {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.RolloutRestriction{}
	out.ID = direct.LazyPtr(in.GetId())
	out.Invokers = direct.EnumSlice_FromProto(mapCtx, in.Invokers)
	out.Actions = direct.EnumSlice_FromProto(mapCtx, in.Actions)
	out.TimeWindows = TimeWindows_v1alpha1_FromProto(mapCtx, in.GetTimeWindows())
	return out
}
func RolloutRestriction_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.RolloutRestriction) *pb.RolloutRestriction {
	if in == nil {
		return nil
	}
	out := &pb.RolloutRestriction{}
	out.Id = direct.ValueOf(in.ID)
	out.Invokers = direct.EnumSlice_ToProto[pb.DeployPolicy_Invoker](mapCtx, in.Invokers)
	out.Actions = direct.EnumSlice_ToProto[pb.RolloutRestriction_RolloutActions](mapCtx, in.Actions)
	out.TimeWindows = TimeWindows_v1alpha1_ToProto(mapCtx, in.TimeWindows)
	return out
}
func SkaffoldModules_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules) *krmclouddeployv1alpha1.SkaffoldModules {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.SkaffoldModules{}
	out.Configs = in.Configs
	out.Git = SkaffoldModules_SkaffoldGitSource_v1alpha1_FromProto(mapCtx, in.GetGit())
	out.GoogleCloudStorage = SkaffoldModules_SkaffoldGCSSource_v1alpha1_FromProto(mapCtx, in.GetGoogleCloudStorage())
	out.GoogleCloudBuildRepo = SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_FromProto(mapCtx, in.GetGoogleCloudBuildRepo())
	return out
}
func SkaffoldModules_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.SkaffoldModules) *pb.SkaffoldModules {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules{}
	out.Configs = in.Configs
	if oneof := SkaffoldModules_SkaffoldGitSource_v1alpha1_ToProto(mapCtx, in.Git); oneof != nil {
		out.Source = &pb.SkaffoldModules_Git{Git: oneof}
	}
	if oneof := SkaffoldModules_SkaffoldGCSSource_v1alpha1_ToProto(mapCtx, in.GoogleCloudStorage); oneof != nil {
		out.Source = &pb.SkaffoldModules_GoogleCloudStorage{GoogleCloudStorage: oneof}
	}
	if oneof := SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_ToProto(mapCtx, in.GoogleCloudBuildRepo); oneof != nil {
		out.Source = &pb.SkaffoldModules_GoogleCloudBuildRepo{GoogleCloudBuildRepo: oneof}
	}
	return out
}
func SkaffoldModules_SkaffoldGCSSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules_SkaffoldGCSSource) *krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGCSSource {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGCSSource{}
	out.Source = direct.LazyPtr(in.GetSource())
	out.Path = direct.LazyPtr(in.GetPath())
	return out
}
func SkaffoldModules_SkaffoldGCSSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGCSSource) *pb.SkaffoldModules_SkaffoldGCSSource {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules_SkaffoldGCSSource{}
	out.Source = direct.ValueOf(in.Source)
	out.Path = direct.ValueOf(in.Path)
	return out
}
func SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules_SkaffoldGCBRepoSource) *krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGcbRepoSource {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGcbRepoSource{}
	out.Repository = direct.LazyPtr(in.GetRepository())
	out.Path = direct.LazyPtr(in.GetPath())
	out.Ref = direct.LazyPtr(in.GetRef())
	return out
}
func SkaffoldModules_SkaffoldGcbRepoSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGcbRepoSource) *pb.SkaffoldModules_SkaffoldGCBRepoSource {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules_SkaffoldGCBRepoSource{}
	out.Repository = direct.ValueOf(in.Repository)
	out.Path = direct.ValueOf(in.Path)
	out.Ref = direct.ValueOf(in.Ref)
	return out
}
func SkaffoldModules_SkaffoldGitSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SkaffoldModules_SkaffoldGitSource) *krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGitSource {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGitSource{}
	out.Repo = direct.LazyPtr(in.GetRepo())
	out.Path = direct.LazyPtr(in.GetPath())
	out.Ref = direct.LazyPtr(in.GetRef())
	return out
}
func SkaffoldModules_SkaffoldGitSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.SkaffoldModules_SkaffoldGitSource) *pb.SkaffoldModules_SkaffoldGitSource {
	if in == nil {
		return nil
	}
	out := &pb.SkaffoldModules_SkaffoldGitSource{}
	out.Repo = direct.ValueOf(in.Repo)
	out.Path = direct.ValueOf(in.Path)
	out.Ref = direct.ValueOf(in.Ref)
	return out
}
func TargetsPresentCondition_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.TargetsPresentCondition) *pb.TargetsPresentCondition {
	if in == nil {
		return nil
	}
	out := &pb.TargetsPresentCondition{}
	out.Status = direct.ValueOf(in.Status)
	out.MissingTargets = in.MissingTargets
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func TimeWindows_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.TimeWindows) *krmclouddeployv1alpha1.TimeWindows {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.TimeWindows{}
	out.TimeZone = direct.LazyPtr(in.GetTimeZone())
	out.OneTimeWindows = direct.Slice_FromProto(mapCtx, in.OneTimeWindows, OneTimeWindow_v1alpha1_FromProto)
	out.WeeklyWindows = direct.Slice_FromProto(mapCtx, in.WeeklyWindows, WeeklyWindow_v1alpha1_FromProto)
	return out
}
func TimeWindows_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.TimeWindows) *pb.TimeWindows {
	if in == nil {
		return nil
	}
	out := &pb.TimeWindows{}
	out.TimeZone = direct.ValueOf(in.TimeZone)
	out.OneTimeWindows = direct.Slice_ToProto(mapCtx, in.OneTimeWindows, OneTimeWindow_v1alpha1_ToProto)
	out.WeeklyWindows = direct.Slice_ToProto(mapCtx, in.WeeklyWindows, WeeklyWindow_v1alpha1_ToProto)
	return out
}
func TimedPromoteReleaseConditionObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.TimedPromoteReleaseCondition) *krmclouddeployv1alpha1.TimedPromoteReleaseConditionObservedState {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.TimedPromoteReleaseConditionObservedState{}
	out.NextPromotionTime = direct.StringTimestamp_FromProto(mapCtx, in.GetNextPromotionTime())
	out.TargetsList = direct.Slice_FromProto(mapCtx, in.TargetsList, TimedPromoteReleaseCondition_Targets_v1alpha1_FromProto)
	return out
}
func TimedPromoteReleaseConditionObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.TimedPromoteReleaseConditionObservedState) *pb.TimedPromoteReleaseCondition {
	if in == nil {
		return nil
	}
	out := &pb.TimedPromoteReleaseCondition{}
	out.NextPromotionTime = direct.StringTimestamp_ToProto(mapCtx, in.NextPromotionTime)
	out.TargetsList = direct.Slice_ToProto(mapCtx, in.TargetsList, TimedPromoteReleaseCondition_Targets_v1alpha1_ToProto)
	return out
}
func TimedPromoteReleaseCondition_Targets_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.TimedPromoteReleaseCondition_Targets) *pb.TimedPromoteReleaseCondition_Targets {
	if in == nil {
		return nil
	}
	out := &pb.TimedPromoteReleaseCondition_Targets{}
	out.SourceTargetId = direct.ValueOf(in.SourceTargetID)
	out.DestinationTargetId = direct.ValueOf(in.DestinationTargetID)
	return out
}
func TimedPromoteReleaseRuleObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.TimedPromoteReleaseRuleObservedState) *pb.TimedPromoteReleaseRule {
	if in == nil {
		return nil
	}
	out := &pb.TimedPromoteReleaseRule{}
	// MISSING: ID
	// MISSING: DestinationTargetID
	// MISSING: Schedule
	// MISSING: TimeZone
	out.Condition = AutomationRuleConditionObservedState_v1alpha1_ToProto(mapCtx, in.Condition)
	// MISSING: DestinationPhase
	return out
}
func WeeklyWindow_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.WeeklyWindow) *krmclouddeployv1alpha1.WeeklyWindow {
	if in == nil {
		return nil
	}
	out := &krmclouddeployv1alpha1.WeeklyWindow{}
	out.DaysOfWeek = direct.EnumSlice_FromProto(mapCtx, in.DaysOfWeek)
	out.StartTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = TimeOfDay_v1alpha1_FromProto(mapCtx, in.GetEndTime())
	return out
}
func WeeklyWindow_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmclouddeployv1alpha1.WeeklyWindow) *pb.WeeklyWindow {
	if in == nil {
		return nil
	}
	out := &pb.WeeklyWindow{}
	out.DaysOfWeek = direct.EnumSlice_ToProto[dayofweekpb.DayOfWeek](mapCtx, in.DaysOfWeek)
	out.StartTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.StartTime)
	out.EndTime = TimeOfDay_v1alpha1_ToProto(mapCtx, in.EndTime)
	return out
}
