// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: vision.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.vision.v1
// resource: VisionProduct:Product

package v1alpha1

// +kcc:proto=google.cloud.vision.v1.Product.KeyValue
type Product_KeyValue struct {
	// The key of the label attached to the product. Cannot be empty and cannot
	//  exceed 128 bytes.
	// +kcc:proto:field=google.cloud.vision.v1.Product.KeyValue.key
	Key *string `json:"key,omitempty"`

	// The value of the label attached to the product. Cannot be empty and
	//  cannot exceed 128 bytes.
	// +kcc:proto:field=google.cloud.vision.v1.Product.KeyValue.value
	Value *string `json:"value,omitempty"`
}
