// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: tpu.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.tpu.v2

package tpu

import (
	pb "cloud.google.com/go/tpu/apiv2/tpupb"
	krmcomputerefs "github.com/GoogleCloudPlatform/k8s-config-connector/apis/compute/refs"
	krmcomputev1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/compute/v1beta1"
	krm "github.com/GoogleCloudPlatform/k8s-config-connector/apis/tpu/v1alpha1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func AccessConfigObservedState_FromProto(mapCtx *direct.MapContext, in *pb.AccessConfig) *krm.AccessConfigObservedState {
	if in == nil {
		return nil
	}
	out := &krm.AccessConfigObservedState{}
	out.ExternalIP = direct.LazyPtr(in.GetExternalIp())
	return out
}
func AccessConfigObservedState_ToProto(mapCtx *direct.MapContext, in *krm.AccessConfigObservedState) *pb.AccessConfig {
	if in == nil {
		return nil
	}
	out := &pb.AccessConfig{}
	out.ExternalIp = direct.ValueOf(in.ExternalIP)
	return out
}
func NetworkConfig_FromProto(mapCtx *direct.MapContext, in *pb.NetworkConfig) *krm.NetworkConfig {
	if in == nil {
		return nil
	}
	out := &krm.NetworkConfig{}
	if in.GetNetwork() != "" {
		out.NetworkRef = &krmcomputerefs.ComputeNetworkRef{External: in.GetNetwork()}
	}
	if in.GetSubnetwork() != "" {
		out.SubnetworkRef = &krmcomputev1beta1.ComputeSubnetworkRef{External: in.GetSubnetwork()}
	}
	out.EnableExternalIps = direct.LazyPtr(in.GetEnableExternalIps())
	out.CanIPForward = direct.LazyPtr(in.GetCanIpForward())
	out.QueueCount = direct.LazyPtr(in.GetQueueCount())
	return out
}
func NetworkConfig_ToProto(mapCtx *direct.MapContext, in *krm.NetworkConfig) *pb.NetworkConfig {
	if in == nil {
		return nil
	}
	out := &pb.NetworkConfig{}
	if in.NetworkRef != nil {
		out.Network = in.NetworkRef.External
	}
	if in.SubnetworkRef != nil {
		out.Subnetwork = in.SubnetworkRef.External
	}
	out.EnableExternalIps = direct.ValueOf(in.EnableExternalIps)
	out.CanIpForward = direct.ValueOf(in.CanIPForward)
	out.QueueCount = direct.ValueOf(in.QueueCount)
	return out
}
func NetworkEndpoint_FromProto(mapCtx *direct.MapContext, in *pb.NetworkEndpoint) *krm.NetworkEndpoint {
	if in == nil {
		return nil
	}
	out := &krm.NetworkEndpoint{}
	out.IPAddress = direct.LazyPtr(in.GetIpAddress())
	out.Port = direct.LazyPtr(in.GetPort())
	// MISSING: AccessConfig
	return out
}
func NetworkEndpoint_ToProto(mapCtx *direct.MapContext, in *krm.NetworkEndpoint) *pb.NetworkEndpoint {
	if in == nil {
		return nil
	}
	out := &pb.NetworkEndpoint{}
	out.IpAddress = direct.ValueOf(in.IPAddress)
	out.Port = direct.ValueOf(in.Port)
	// MISSING: AccessConfig
	return out
}
func NetworkEndpointObservedState_FromProto(mapCtx *direct.MapContext, in *pb.NetworkEndpoint) *krm.NetworkEndpointObservedState {
	if in == nil {
		return nil
	}
	out := &krm.NetworkEndpointObservedState{}
	// MISSING: IPAddress
	// MISSING: Port
	out.AccessConfig = AccessConfigObservedState_FromProto(mapCtx, in.GetAccessConfig())
	return out
}
func NetworkEndpointObservedState_ToProto(mapCtx *direct.MapContext, in *krm.NetworkEndpointObservedState) *pb.NetworkEndpoint {
	if in == nil {
		return nil
	}
	out := &pb.NetworkEndpoint{}
	// MISSING: IPAddress
	// MISSING: Port
	out.AccessConfig = AccessConfigObservedState_ToProto(mapCtx, in.AccessConfig)
	return out
}
func TPUVirtualMachineObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Node) *krm.TPUVirtualMachineObservedState {
	if in == nil {
		return nil
	}
	out := &krm.TPUVirtualMachineObservedState{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: AcceleratorType
	// MISSING: State
	// MISSING: HealthDescription
	// MISSING: RuntimeVersion
	// MISSING: NetworkConfig
	// MISSING: NetworkConfigs
	// MISSING: CIDRBlock
	// MISSING: ServiceAccount
	// MISSING: CreateTime
	// MISSING: SchedulingConfig
	// MISSING: NetworkEndpoints
	// MISSING: Health
	// MISSING: Labels
	// MISSING: Metadata
	// MISSING: Tags
	// MISSING: ID
	// MISSING: DataDisks
	// MISSING: APIVersion
	// MISSING: Symptoms
	// MISSING: ShieldedInstanceConfig
	// MISSING: AcceleratorConfig
	// MISSING: QueuedResource
	// MISSING: MultisliceNode
	return out
}
func TPUVirtualMachineObservedState_ToProto(mapCtx *direct.MapContext, in *krm.TPUVirtualMachineObservedState) *pb.Node {
	if in == nil {
		return nil
	}
	out := &pb.Node{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: AcceleratorType
	// MISSING: State
	// MISSING: HealthDescription
	// MISSING: RuntimeVersion
	// MISSING: NetworkConfig
	// MISSING: NetworkConfigs
	// MISSING: CIDRBlock
	// MISSING: ServiceAccount
	// MISSING: CreateTime
	// MISSING: SchedulingConfig
	// MISSING: NetworkEndpoints
	// MISSING: Health
	// MISSING: Labels
	// MISSING: Metadata
	// MISSING: Tags
	// MISSING: ID
	// MISSING: DataDisks
	// MISSING: APIVersion
	// MISSING: Symptoms
	// MISSING: ShieldedInstanceConfig
	// MISSING: AcceleratorConfig
	// MISSING: QueuedResource
	// MISSING: MultisliceNode
	return out
}
func TPUVirtualMachineSpec_FromProto(mapCtx *direct.MapContext, in *pb.Node) *krm.TPUVirtualMachineSpec {
	if in == nil {
		return nil
	}
	out := &krm.TPUVirtualMachineSpec{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: AcceleratorType
	// MISSING: State
	// MISSING: HealthDescription
	// MISSING: RuntimeVersion
	// MISSING: NetworkConfig
	// MISSING: NetworkConfigs
	// MISSING: CIDRBlock
	// MISSING: ServiceAccount
	// MISSING: CreateTime
	// MISSING: SchedulingConfig
	// MISSING: NetworkEndpoints
	// MISSING: Health
	// MISSING: Labels
	// MISSING: Metadata
	// MISSING: Tags
	// MISSING: ID
	// MISSING: DataDisks
	// MISSING: APIVersion
	// MISSING: Symptoms
	// MISSING: ShieldedInstanceConfig
	// MISSING: AcceleratorConfig
	// MISSING: QueuedResource
	// MISSING: MultisliceNode
	return out
}
func TPUVirtualMachineSpec_ToProto(mapCtx *direct.MapContext, in *krm.TPUVirtualMachineSpec) *pb.Node {
	if in == nil {
		return nil
	}
	out := &pb.Node{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: AcceleratorType
	// MISSING: State
	// MISSING: HealthDescription
	// MISSING: RuntimeVersion
	// MISSING: NetworkConfig
	// MISSING: NetworkConfigs
	// MISSING: CIDRBlock
	// MISSING: ServiceAccount
	// MISSING: CreateTime
	// MISSING: SchedulingConfig
	// MISSING: NetworkEndpoints
	// MISSING: Health
	// MISSING: Labels
	// MISSING: Metadata
	// MISSING: Tags
	// MISSING: ID
	// MISSING: DataDisks
	// MISSING: APIVersion
	// MISSING: Symptoms
	// MISSING: ShieldedInstanceConfig
	// MISSING: AcceleratorConfig
	// MISSING: QueuedResource
	// MISSING: MultisliceNode
	return out
}
