// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: asset.cnrm.cloud.google.com
// krm.version: v1beta1
// proto.service: google.cloud.asset.v1

package asset

import (
	pb "cloud.google.com/go/asset/apiv1/assetpb"
	krm "github.com/GoogleCloudPlatform/k8s-config-connector/apis/asset/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func AssetFeedObservedState_FromProto(mapCtx *direct.MapContext, in *pb.Feed) *krm.AssetFeedObservedState {
	if in == nil {
		return nil
	}
	out := &krm.AssetFeedObservedState{}
	// MISSING: Name
	// MISSING: AssetNames
	// MISSING: AssetTypes
	// MISSING: ContentType
	// MISSING: FeedOutputConfig
	// MISSING: Condition
	// MISSING: RelationshipTypes
	return out
}
func AssetFeedObservedState_ToProto(mapCtx *direct.MapContext, in *krm.AssetFeedObservedState) *pb.Feed {
	if in == nil {
		return nil
	}
	out := &pb.Feed{}
	// MISSING: Name
	// MISSING: AssetNames
	// MISSING: AssetTypes
	// MISSING: ContentType
	// MISSING: FeedOutputConfig
	// MISSING: Condition
	// MISSING: RelationshipTypes
	return out
}
func AssetFeedSpec_FromProto(mapCtx *direct.MapContext, in *pb.Feed) *krm.AssetFeedSpec {
	if in == nil {
		return nil
	}
	out := &krm.AssetFeedSpec{}
	// MISSING: Name
	// MISSING: AssetNames
	// MISSING: AssetTypes
	// MISSING: ContentType
	// MISSING: FeedOutputConfig
	// MISSING: Condition
	// MISSING: RelationshipTypes
	return out
}
func AssetFeedSpec_ToProto(mapCtx *direct.MapContext, in *krm.AssetFeedSpec) *pb.Feed {
	if in == nil {
		return nil
	}
	out := &pb.Feed{}
	// MISSING: Name
	// MISSING: AssetNames
	// MISSING: AssetTypes
	// MISSING: ContentType
	// MISSING: FeedOutputConfig
	// MISSING: Condition
	// MISSING: RelationshipTypes
	return out
}
func AssetSavedQueryObservedState_FromProto(mapCtx *direct.MapContext, in *pb.SavedQuery) *krm.AssetSavedQueryObservedState {
	if in == nil {
		return nil
	}
	out := &krm.AssetSavedQueryObservedState{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: CreateTime
	// MISSING: Creator
	// MISSING: LastUpdateTime
	// MISSING: LastUpdater
	// MISSING: Labels
	// MISSING: Content
	return out
}
func AssetSavedQueryObservedState_ToProto(mapCtx *direct.MapContext, in *krm.AssetSavedQueryObservedState) *pb.SavedQuery {
	if in == nil {
		return nil
	}
	out := &pb.SavedQuery{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: CreateTime
	// MISSING: Creator
	// MISSING: LastUpdateTime
	// MISSING: LastUpdater
	// MISSING: Labels
	// MISSING: Content
	return out
}
func AssetSavedQuerySpec_FromProto(mapCtx *direct.MapContext, in *pb.SavedQuery) *krm.AssetSavedQuerySpec {
	if in == nil {
		return nil
	}
	out := &krm.AssetSavedQuerySpec{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: CreateTime
	// MISSING: Creator
	// MISSING: LastUpdateTime
	// MISSING: LastUpdater
	// MISSING: Labels
	// MISSING: Content
	return out
}
func AssetSavedQuerySpec_ToProto(mapCtx *direct.MapContext, in *krm.AssetSavedQuerySpec) *pb.SavedQuery {
	if in == nil {
		return nil
	}
	out := &pb.SavedQuery{}
	// MISSING: Name
	// MISSING: Description
	// MISSING: CreateTime
	// MISSING: Creator
	// MISSING: LastUpdateTime
	// MISSING: LastUpdater
	// MISSING: Labels
	// MISSING: Content
	return out
}
