// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// +generated:mapper
// krm.group: vertexai.cnrm.cloud.google.com
// krm.version: v1beta1
// proto.service: google.cloud.aiplatform.v1beta1

package vertexai

import (
	pb "cloud.google.com/go/aiplatform/apiv1beta1/aiplatformpb"
	krmaiplatformv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/aiplatform/v1alpha1"
	krmcomputerefs "github.com/GoogleCloudPlatform/k8s-config-connector/apis/compute/refs"
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	krmvertexaiv1alpha1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/vertexai/v1alpha1"
	krmvertexaiv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/vertexai/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct"
)

func ActiveLearningConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ActiveLearningConfig) *krmvertexaiv1alpha1.ActiveLearningConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ActiveLearningConfig{}
	out.MaxDataItemCount = direct.LazyPtr(in.GetMaxDataItemCount())
	out.MaxDataItemPercentage = direct.LazyPtr(in.GetMaxDataItemPercentage())
	out.SampleConfig = SampleConfig_v1alpha1_FromProto(mapCtx, in.GetSampleConfig())
	out.TrainingConfig = TrainingConfig_v1alpha1_FromProto(mapCtx, in.GetTrainingConfig())
	return out
}
func ActiveLearningConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ActiveLearningConfig) *pb.ActiveLearningConfig {
	if in == nil {
		return nil
	}
	out := &pb.ActiveLearningConfig{}
	if oneof := ActiveLearningConfig_MaxDataItemCount_ToProto(mapCtx, in.MaxDataItemCount); oneof != nil {
		out.HumanLabelingBudget = oneof
	}
	if oneof := ActiveLearningConfig_MaxDataItemPercentage_ToProto(mapCtx, in.MaxDataItemPercentage); oneof != nil {
		out.HumanLabelingBudget = oneof
	}
	out.SampleConfig = SampleConfig_v1alpha1_ToProto(mapCtx, in.SampleConfig)
	out.TrainingConfig = TrainingConfig_v1alpha1_ToProto(mapCtx, in.TrainingConfig)
	return out
}
func ActiveLearningConfig_MaxDataItemCount_ToProto(mapCtx *direct.MapContext, in *int64) *pb.ActiveLearningConfig_MaxDataItemCount {
	if in == nil {
		return nil
	}
	return &pb.ActiveLearningConfig_MaxDataItemCount{MaxDataItemCount: *in}
}
func ActiveLearningConfig_MaxDataItemPercentage_ToProto(mapCtx *direct.MapContext, in *int32) *pb.ActiveLearningConfig_MaxDataItemPercentage {
	if in == nil {
		return nil
	}
	return &pb.ActiveLearningConfig_MaxDataItemPercentage{MaxDataItemPercentage: *in}
}
func AutoscalingMetricSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.AutoscalingMetricSpec) *krmvertexaiv1alpha1.AutoscalingMetricSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.AutoscalingMetricSpec{}
	out.MetricName = direct.LazyPtr(in.GetMetricName())
	out.Target = direct.LazyPtr(in.GetTarget())
	out.MonitoredResourceLabels = in.MonitoredResourceLabels
	return out
}
func AutoscalingMetricSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.AutoscalingMetricSpec) *pb.AutoscalingMetricSpec {
	if in == nil {
		return nil
	}
	out := &pb.AutoscalingMetricSpec{}
	out.MetricName = direct.ValueOf(in.MetricName)
	out.Target = direct.ValueOf(in.Target)
	out.MonitoredResourceLabels = in.MonitoredResourceLabels
	return out
}
func BatchDedicatedResources_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchDedicatedResources) *krmvertexaiv1alpha1.BatchDedicatedResources {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BatchDedicatedResources{}
	out.MachineSpec = MachineSpec_v1alpha1_FromProto(mapCtx, in.GetMachineSpec())
	out.StartingReplicaCount = direct.LazyPtr(in.GetStartingReplicaCount())
	out.MaxReplicaCount = direct.LazyPtr(in.GetMaxReplicaCount())
	out.FlexStart = FlexStart_v1alpha1_FromProto(mapCtx, in.GetFlexStart())
	out.Spot = direct.LazyPtr(in.GetSpot())
	return out
}
func BatchDedicatedResources_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BatchDedicatedResources) *pb.BatchDedicatedResources {
	if in == nil {
		return nil
	}
	out := &pb.BatchDedicatedResources{}
	out.MachineSpec = MachineSpec_v1alpha1_ToProto(mapCtx, in.MachineSpec)
	out.StartingReplicaCount = direct.ValueOf(in.StartingReplicaCount)
	out.MaxReplicaCount = direct.ValueOf(in.MaxReplicaCount)
	out.FlexStart = FlexStart_v1alpha1_ToProto(mapCtx, in.FlexStart)
	out.Spot = direct.ValueOf(in.Spot)
	return out
}
func BatchPredictionJob_InputConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchPredictionJob_InputConfig) *krmvertexaiv1alpha1.BatchPredictionJob_InputConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BatchPredictionJob_InputConfig{}
	out.GCSSource = GCSSource_v1alpha1_FromProto(mapCtx, in.GetGcsSource())
	out.BigquerySource = BigQuerySource_v1alpha1_FromProto(mapCtx, in.GetBigquerySource())
	out.InstancesFormat = direct.LazyPtr(in.GetInstancesFormat())
	return out
}
func BatchPredictionJob_InputConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BatchPredictionJob_InputConfig) *pb.BatchPredictionJob_InputConfig {
	if in == nil {
		return nil
	}
	out := &pb.BatchPredictionJob_InputConfig{}
	if oneof := GCSSource_v1alpha1_ToProto(mapCtx, in.GCSSource); oneof != nil {
		out.Source = &pb.BatchPredictionJob_InputConfig_GcsSource{GcsSource: oneof}
	}
	if oneof := BigQuerySource_v1alpha1_ToProto(mapCtx, in.BigquerySource); oneof != nil {
		out.Source = &pb.BatchPredictionJob_InputConfig_BigquerySource{BigquerySource: oneof}
	}
	out.InstancesFormat = direct.ValueOf(in.InstancesFormat)
	return out
}
func BatchPredictionJob_InstanceConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchPredictionJob_InstanceConfig) *krmvertexaiv1alpha1.BatchPredictionJob_InstanceConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BatchPredictionJob_InstanceConfig{}
	out.InstanceType = direct.LazyPtr(in.GetInstanceType())
	out.KeyField = direct.LazyPtr(in.GetKeyField())
	out.IncludedFields = in.IncludedFields
	out.ExcludedFields = in.ExcludedFields
	return out
}
func BatchPredictionJob_InstanceConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BatchPredictionJob_InstanceConfig) *pb.BatchPredictionJob_InstanceConfig {
	if in == nil {
		return nil
	}
	out := &pb.BatchPredictionJob_InstanceConfig{}
	out.InstanceType = direct.ValueOf(in.InstanceType)
	out.KeyField = direct.ValueOf(in.KeyField)
	out.IncludedFields = in.IncludedFields
	out.ExcludedFields = in.ExcludedFields
	return out
}
func BatchPredictionJob_OutputConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchPredictionJob_OutputConfig) *krmvertexaiv1alpha1.BatchPredictionJob_OutputConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BatchPredictionJob_OutputConfig{}
	out.GCSDestination = GCSDestination_v1alpha1_FromProto(mapCtx, in.GetGcsDestination())
	out.BigqueryDestination = BigQueryDestination_v1alpha1_FromProto(mapCtx, in.GetBigqueryDestination())
	out.PredictionsFormat = direct.LazyPtr(in.GetPredictionsFormat())
	return out
}
func BatchPredictionJob_OutputConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BatchPredictionJob_OutputConfig) *pb.BatchPredictionJob_OutputConfig {
	if in == nil {
		return nil
	}
	out := &pb.BatchPredictionJob_OutputConfig{}
	if oneof := GCSDestination_v1alpha1_ToProto(mapCtx, in.GCSDestination); oneof != nil {
		out.Destination = &pb.BatchPredictionJob_OutputConfig_GcsDestination{GcsDestination: oneof}
	}
	if oneof := BigQueryDestination_v1alpha1_ToProto(mapCtx, in.BigqueryDestination); oneof != nil {
		out.Destination = &pb.BatchPredictionJob_OutputConfig_BigqueryDestination{BigqueryDestination: oneof}
	}
	out.PredictionsFormat = direct.ValueOf(in.PredictionsFormat)
	return out
}
func BatchPredictionJob_OutputInfoObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchPredictionJob_OutputInfo) *krmvertexaiv1alpha1.BatchPredictionJob_OutputInfoObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BatchPredictionJob_OutputInfoObservedState{}
	out.GCSOutputDirectory = direct.LazyPtr(in.GetGcsOutputDirectory())
	out.BigqueryOutputDataset = direct.LazyPtr(in.GetBigqueryOutputDataset())
	out.BigqueryOutputTable = direct.LazyPtr(in.GetBigqueryOutputTable())
	return out
}
func BatchPredictionJob_OutputInfoObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BatchPredictionJob_OutputInfoObservedState) *pb.BatchPredictionJob_OutputInfo {
	if in == nil {
		return nil
	}
	out := &pb.BatchPredictionJob_OutputInfo{}
	if oneof := BatchPredictionJob_OutputInfoObservedState_GcsOutputDirectory_ToProto(mapCtx, in.GCSOutputDirectory); oneof != nil {
		out.OutputLocation = oneof
	}
	if oneof := BatchPredictionJob_OutputInfoObservedState_BigqueryOutputDataset_ToProto(mapCtx, in.BigqueryOutputDataset); oneof != nil {
		out.OutputLocation = oneof
	}
	out.BigqueryOutputTable = direct.ValueOf(in.BigqueryOutputTable)
	return out
}
func BatchPredictionJob_OutputInfoObservedState_GcsOutputDirectory_ToProto(mapCtx *direct.MapContext, in *string) *pb.BatchPredictionJob_OutputInfo_GcsOutputDirectory {
	if in == nil {
		return nil
	}
	return &pb.BatchPredictionJob_OutputInfo_GcsOutputDirectory{GcsOutputDirectory: *in}
}
func BatchPredictionJob_OutputInfoObservedState_BigqueryOutputDataset_ToProto(mapCtx *direct.MapContext, in *string) *pb.BatchPredictionJob_OutputInfo_BigqueryOutputDataset {
	if in == nil {
		return nil
	}
	return &pb.BatchPredictionJob_OutputInfo_BigqueryOutputDataset{BigqueryOutputDataset: *in}
}
func BigQueryDestination_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BigQueryDestination) *krmvertexaiv1alpha1.BigQueryDestination {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BigQueryDestination{}
	out.OutputURI = direct.LazyPtr(in.GetOutputUri())
	return out
}
func BigQueryDestination_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BigQueryDestination) *pb.BigQueryDestination {
	if in == nil {
		return nil
	}
	out := &pb.BigQueryDestination{}
	out.OutputUri = direct.ValueOf(in.OutputURI)
	return out
}
func BigQuerySource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BigQuerySource) *krmvertexaiv1alpha1.BigQuerySource {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.BigQuerySource{}
	out.InputURI = direct.LazyPtr(in.GetInputUri())
	return out
}
func BigQuerySource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.BigQuerySource) *pb.BigQuerySource {
	if in == nil {
		return nil
	}
	out := &pb.BigQuerySource{}
	out.InputUri = direct.ValueOf(in.InputURI)
	return out
}
func CompletionStatsObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CompletionStats) *krmvertexaiv1alpha1.CompletionStatsObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.CompletionStatsObservedState{}
	out.SuccessfulCount = direct.LazyPtr(in.GetSuccessfulCount())
	out.FailedCount = direct.LazyPtr(in.GetFailedCount())
	out.IncompleteCount = direct.LazyPtr(in.GetIncompleteCount())
	out.SuccessfulForecastPointCount = direct.LazyPtr(in.GetSuccessfulForecastPointCount())
	return out
}
func CompletionStatsObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.CompletionStatsObservedState) *pb.CompletionStats {
	if in == nil {
		return nil
	}
	out := &pb.CompletionStats{}
	out.SuccessfulCount = direct.ValueOf(in.SuccessfulCount)
	out.FailedCount = direct.ValueOf(in.FailedCount)
	out.IncompleteCount = direct.ValueOf(in.IncompleteCount)
	out.SuccessfulForecastPointCount = direct.ValueOf(in.SuccessfulForecastPointCount)
	return out
}
func ContainerSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ContainerSpec) *krmvertexaiv1alpha1.ContainerSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ContainerSpec{}
	out.ImageURI = direct.LazyPtr(in.GetImageUri())
	out.Command = in.Command
	out.Args = in.Args
	out.Env = direct.Slice_FromProto(mapCtx, in.Env, EnvVar_v1alpha1_FromProto)
	return out
}
func ContainerSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ContainerSpec) *pb.ContainerSpec {
	if in == nil {
		return nil
	}
	out := &pb.ContainerSpec{}
	out.ImageUri = direct.ValueOf(in.ImageURI)
	out.Command = in.Command
	out.Args = in.Args
	out.Env = direct.Slice_ToProto(mapCtx, in.Env, EnvVar_v1alpha1_ToProto)
	return out
}
func CustomJobSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomJobSpec) *krmvertexaiv1alpha1.CustomJobSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.CustomJobSpec{}
	out.PersistentResourceID = direct.LazyPtr(in.GetPersistentResourceId())
	out.WorkerPoolSpecs = direct.Slice_FromProto(mapCtx, in.WorkerPoolSpecs, WorkerPoolSpec_v1alpha1_FromProto)
	out.Scheduling = Scheduling_v1alpha1_FromProto(mapCtx, in.GetScheduling())
	if in.GetServiceAccount() != "" {
		out.ServiceAccountRef = &refsv1beta1.IAMServiceAccountRef{External: in.GetServiceAccount()}
	}
	if in.GetNetwork() != "" {
		out.NetworkRef = &krmcomputerefs.ComputeNetworkRef{External: in.GetNetwork()}
	}
	out.ReservedIPRanges = in.ReservedIpRanges
	out.PSCInterfaceConfig = PSCInterfaceConfig_v1alpha1_FromProto(mapCtx, in.GetPscInterfaceConfig())
	out.BaseOutputDirectory = GCSDestination_v1alpha1_FromProto(mapCtx, in.GetBaseOutputDirectory())
	out.ProtectedArtifactLocationID = direct.LazyPtr(in.GetProtectedArtifactLocationId())
	if in.GetTensorboard() != "" {
		out.TensorboardRef = &krmvertexaiv1alpha1.VertexAITensorboardRef{External: in.GetTensorboard()}
	}
	out.EnableWebAccess = direct.LazyPtr(in.GetEnableWebAccess())
	out.EnableDashboardAccess = direct.LazyPtr(in.GetEnableDashboardAccess())
	if in.GetExperiment() != "" {
		out.ExperimentRef = &krmvertexaiv1alpha1.VertexAIExperimentRef{External: in.GetExperiment()}
	}
	if in.GetExperimentRun() != "" {
		out.ExperimentRunRef = &krmvertexaiv1alpha1.VertexAIExperimentRunRef{External: in.GetExperimentRun()}
	}

	if v := in.GetModels(); len(v) != 0 {
		for i := range v {
			out.ModelRefs = append(out.ModelRefs, krmaiplatformv1alpha1.AIPlatformModelRef{External: v[i]})
		}
	}

	return out
}
func CustomJobSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.CustomJobSpec) *pb.CustomJobSpec {
	if in == nil {
		return nil
	}
	out := &pb.CustomJobSpec{}
	out.PersistentResourceId = direct.ValueOf(in.PersistentResourceID)
	out.WorkerPoolSpecs = direct.Slice_ToProto(mapCtx, in.WorkerPoolSpecs, WorkerPoolSpec_v1alpha1_ToProto)
	out.Scheduling = Scheduling_v1alpha1_ToProto(mapCtx, in.Scheduling)
	if in.ServiceAccountRef != nil {
		out.ServiceAccount = in.ServiceAccountRef.External
	}
	if in.NetworkRef != nil {
		out.Network = in.NetworkRef.External
	}
	out.ReservedIpRanges = in.ReservedIPRanges
	out.PscInterfaceConfig = PSCInterfaceConfig_v1alpha1_ToProto(mapCtx, in.PSCInterfaceConfig)
	out.BaseOutputDirectory = GCSDestination_v1alpha1_ToProto(mapCtx, in.BaseOutputDirectory)
	out.ProtectedArtifactLocationId = direct.ValueOf(in.ProtectedArtifactLocationID)
	if in.TensorboardRef != nil {
		out.Tensorboard = in.TensorboardRef.External
	}
	out.EnableWebAccess = direct.ValueOf(in.EnableWebAccess)
	out.EnableDashboardAccess = direct.ValueOf(in.EnableDashboardAccess)
	if in.ExperimentRef != nil {
		out.Experiment = in.ExperimentRef.External
	}
	if in.ExperimentRunRef != nil {
		out.ExperimentRun = in.ExperimentRunRef.External
	}

	if v := in.ModelRefs; len(v) != 0 {
		for i := range v {
			out.Models = append(out.Models, v[i].External)
		}
	}

	return out
}
func DNSPeeringConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DnsPeeringConfig) *krmvertexaiv1alpha1.DNSPeeringConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.DNSPeeringConfig{}
	out.Domain = direct.LazyPtr(in.GetDomain())
	out.TargetProject = direct.LazyPtr(in.GetTargetProject())
	out.TargetNetwork = direct.LazyPtr(in.GetTargetNetwork())
	return out
}
func DNSPeeringConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.DNSPeeringConfig) *pb.DnsPeeringConfig {
	if in == nil {
		return nil
	}
	out := &pb.DnsPeeringConfig{}
	out.Domain = direct.ValueOf(in.Domain)
	out.TargetProject = direct.ValueOf(in.TargetProject)
	out.TargetNetwork = direct.ValueOf(in.TargetNetwork)
	return out
}
func DedicatedResources_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DedicatedResources) *krmvertexaiv1alpha1.DedicatedResources {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.DedicatedResources{}
	out.MachineSpec = MachineSpec_v1alpha1_FromProto(mapCtx, in.GetMachineSpec())
	out.MinReplicaCount = direct.LazyPtr(in.GetMinReplicaCount())
	out.MaxReplicaCount = direct.LazyPtr(in.GetMaxReplicaCount())
	out.RequiredReplicaCount = direct.LazyPtr(in.GetRequiredReplicaCount())
	out.AutoscalingMetricSpecs = direct.Slice_FromProto(mapCtx, in.AutoscalingMetricSpecs, AutoscalingMetricSpec_v1alpha1_FromProto)
	out.Spot = direct.LazyPtr(in.GetSpot())
	out.FlexStart = FlexStart_v1alpha1_FromProto(mapCtx, in.GetFlexStart())
	return out
}
func DedicatedResources_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.DedicatedResources) *pb.DedicatedResources {
	if in == nil {
		return nil
	}
	out := &pb.DedicatedResources{}
	out.MachineSpec = MachineSpec_v1alpha1_ToProto(mapCtx, in.MachineSpec)
	out.MinReplicaCount = direct.ValueOf(in.MinReplicaCount)
	out.MaxReplicaCount = direct.ValueOf(in.MaxReplicaCount)
	out.RequiredReplicaCount = direct.ValueOf(in.RequiredReplicaCount)
	out.AutoscalingMetricSpecs = direct.Slice_ToProto(mapCtx, in.AutoscalingMetricSpecs, AutoscalingMetricSpec_v1alpha1_ToProto)
	out.Spot = direct.ValueOf(in.Spot)
	out.FlexStart = FlexStart_v1alpha1_ToProto(mapCtx, in.FlexStart)
	return out
}
func DiskSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DiskSpec) *krmvertexaiv1alpha1.DiskSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.DiskSpec{}
	out.BootDiskType = direct.LazyPtr(in.GetBootDiskType())
	out.BootDiskSizeGB = direct.LazyPtr(in.GetBootDiskSizeGb())
	return out
}
func DiskSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.DiskSpec) *pb.DiskSpec {
	if in == nil {
		return nil
	}
	out := &pb.DiskSpec{}
	out.BootDiskType = direct.ValueOf(in.BootDiskType)
	out.BootDiskSizeGb = direct.ValueOf(in.BootDiskSizeGB)
	return out
}

/* found existing non-generated mapping function "EncryptionSpec_v1alpha1_FromProto", skipping
func EncryptionSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.EncryptionSpec) *krmvertexaiv1alpha1.EncryptionSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.EncryptionSpec{}
	// MISSING: KMSKeyName
	return out
}
*/

/* found existing non-generated mapping function "EncryptionSpec_v1alpha1_ToProto", skipping
func EncryptionSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.EncryptionSpec) *pb.EncryptionSpec {
	if in == nil {
		return nil
	}
	out := &pb.EncryptionSpec{}
	// MISSING: KMSKeyName
	return out
}
*/

/* found existing non-generated mapping function "EncryptionSpec_v1beta1_FromProto", skipping
func EncryptionSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.EncryptionSpec) *krmvertexaiv1beta1.EncryptionSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.EncryptionSpec{}
	// MISSING: KMSKeyName
	return out
}
*/

/*
found existing non-generated mapping function "EncryptionSpec_v1beta1_ToProto", skipping

	func EncryptionSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.EncryptionSpec) *pb.EncryptionSpec {
		if in == nil {
			return nil
		}
		out := &pb.EncryptionSpec{}
		// MISSING: KMSKeyName
		return out
	}
*/
func EnvVar_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.EnvVar) *krmvertexaiv1alpha1.EnvVar {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.EnvVar{}
	out.Name = direct.LazyPtr(in.GetName())
	out.Value = direct.LazyPtr(in.GetValue())
	return out
}
func EnvVar_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.EnvVar) *pb.EnvVar {
	if in == nil {
		return nil
	}
	out := &pb.EnvVar{}
	out.Name = direct.ValueOf(in.Name)
	out.Value = direct.ValueOf(in.Value)
	return out
}
func ExampleStoreConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ExampleStoreConfig) *krmvertexaiv1alpha1.ExampleStoreConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ExampleStoreConfig{}
	out.VertexEmbeddingModel = direct.LazyPtr(in.GetVertexEmbeddingModel())
	return out
}
func ExampleStoreConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ExampleStoreConfig) *pb.ExampleStoreConfig {
	if in == nil {
		return nil
	}
	out := &pb.ExampleStoreConfig{}
	out.VertexEmbeddingModel = direct.ValueOf(in.VertexEmbeddingModel)
	return out
}
func FeatureGroup_BigQuery_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.FeatureGroup_BigQuery) *krmvertexaiv1alpha1.FeatureGroup_BigQuery {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.FeatureGroup_BigQuery{}
	out.BigQuerySource = BigQuerySource_v1alpha1_FromProto(mapCtx, in.GetBigQuerySource())
	out.EntityIDColumns = in.EntityIdColumns
	out.StaticDataSource = direct.LazyPtr(in.GetStaticDataSource())
	out.TimeSeries = FeatureGroup_BigQuery_TimeSeries_v1alpha1_FromProto(mapCtx, in.GetTimeSeries())
	out.Dense = direct.LazyPtr(in.GetDense())
	return out
}
func FeatureGroup_BigQuery_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.FeatureGroup_BigQuery) *pb.FeatureGroup_BigQuery {
	if in == nil {
		return nil
	}
	out := &pb.FeatureGroup_BigQuery{}
	out.BigQuerySource = BigQuerySource_v1alpha1_ToProto(mapCtx, in.BigQuerySource)
	out.EntityIdColumns = in.EntityIDColumns
	out.StaticDataSource = direct.ValueOf(in.StaticDataSource)
	out.TimeSeries = FeatureGroup_BigQuery_TimeSeries_v1alpha1_ToProto(mapCtx, in.TimeSeries)
	out.Dense = direct.ValueOf(in.Dense)
	return out
}
func FeatureGroup_BigQuery_TimeSeries_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.FeatureGroup_BigQuery_TimeSeries) *krmvertexaiv1alpha1.FeatureGroup_BigQuery_TimeSeries {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.FeatureGroup_BigQuery_TimeSeries{}
	out.TimestampColumn = direct.LazyPtr(in.GetTimestampColumn())
	return out
}
func FeatureGroup_BigQuery_TimeSeries_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.FeatureGroup_BigQuery_TimeSeries) *pb.FeatureGroup_BigQuery_TimeSeries {
	if in == nil {
		return nil
	}
	out := &pb.FeatureGroup_BigQuery_TimeSeries{}
	out.TimestampColumn = direct.ValueOf(in.TimestampColumn)
	return out
}
func FeatureStatsAnomaly_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.FeatureStatsAnomaly) *krmvertexaiv1alpha1.FeatureStatsAnomaly {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.FeatureStatsAnomaly{}
	out.Score = direct.LazyPtr(in.GetScore())
	out.StatsURI = direct.LazyPtr(in.GetStatsUri())
	out.AnomalyURI = direct.LazyPtr(in.GetAnomalyUri())
	out.DistributionDeviation = direct.LazyPtr(in.GetDistributionDeviation())
	out.AnomalyDetectionThreshold = direct.LazyPtr(in.GetAnomalyDetectionThreshold())
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	return out
}
func FeatureStatsAnomaly_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.FeatureStatsAnomaly) *pb.FeatureStatsAnomaly {
	if in == nil {
		return nil
	}
	out := &pb.FeatureStatsAnomaly{}
	out.Score = direct.ValueOf(in.Score)
	out.StatsUri = direct.ValueOf(in.StatsURI)
	out.AnomalyUri = direct.ValueOf(in.AnomalyURI)
	out.DistributionDeviation = direct.ValueOf(in.DistributionDeviation)
	out.AnomalyDetectionThreshold = direct.ValueOf(in.AnomalyDetectionThreshold)
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	return out
}
func Featurestore_OnlineServingConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Featurestore_OnlineServingConfig) *krmvertexaiv1alpha1.Featurestore_OnlineServingConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Featurestore_OnlineServingConfig{}
	out.FixedNodeCount = direct.LazyPtr(in.GetFixedNodeCount())
	out.Scaling = Featurestore_OnlineServingConfig_Scaling_v1alpha1_FromProto(mapCtx, in.GetScaling())
	return out
}
func Featurestore_OnlineServingConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Featurestore_OnlineServingConfig) *pb.Featurestore_OnlineServingConfig {
	if in == nil {
		return nil
	}
	out := &pb.Featurestore_OnlineServingConfig{}
	out.FixedNodeCount = direct.ValueOf(in.FixedNodeCount)
	out.Scaling = Featurestore_OnlineServingConfig_Scaling_v1alpha1_ToProto(mapCtx, in.Scaling)
	return out
}
func Featurestore_OnlineServingConfig_Scaling_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Featurestore_OnlineServingConfig_Scaling) *krmvertexaiv1alpha1.Featurestore_OnlineServingConfig_Scaling {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Featurestore_OnlineServingConfig_Scaling{}
	out.MinNodeCount = direct.LazyPtr(in.GetMinNodeCount())
	out.MaxNodeCount = direct.LazyPtr(in.GetMaxNodeCount())
	out.CPUUtilizationTarget = direct.LazyPtr(in.GetCpuUtilizationTarget())
	return out
}
func Featurestore_OnlineServingConfig_Scaling_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Featurestore_OnlineServingConfig_Scaling) *pb.Featurestore_OnlineServingConfig_Scaling {
	if in == nil {
		return nil
	}
	out := &pb.Featurestore_OnlineServingConfig_Scaling{}
	out.MinNodeCount = direct.ValueOf(in.MinNodeCount)
	out.MaxNodeCount = direct.ValueOf(in.MaxNodeCount)
	out.CpuUtilizationTarget = direct.ValueOf(in.CPUUtilizationTarget)
	return out
}
func FlexStart_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.FlexStart) *krmvertexaiv1alpha1.FlexStart {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.FlexStart{}
	out.MaxRuntimeDuration = direct.StringDuration_FromProto(mapCtx, in.GetMaxRuntimeDuration())
	return out
}
func FlexStart_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.FlexStart) *pb.FlexStart {
	if in == nil {
		return nil
	}
	out := &pb.FlexStart{}
	out.MaxRuntimeDuration = direct.StringDuration_ToProto(mapCtx, in.MaxRuntimeDuration)
	return out
}
func GCSDestination_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.GcsDestination) *krmvertexaiv1alpha1.GCSDestination {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.GCSDestination{}
	out.OutputURIPrefix = direct.LazyPtr(in.GetOutputUriPrefix())
	return out
}
func GCSDestination_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.GCSDestination) *pb.GcsDestination {
	if in == nil {
		return nil
	}
	out := &pb.GcsDestination{}
	out.OutputUriPrefix = direct.ValueOf(in.OutputURIPrefix)
	return out
}
func GCSSource_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.GcsSource) *krmvertexaiv1alpha1.GCSSource {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.GCSSource{}
	out.Uris = in.Uris
	return out
}
func GCSSource_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.GCSSource) *pb.GcsSource {
	if in == nil {
		return nil
	}
	out := &pb.GcsSource{}
	out.Uris = in.Uris
	return out
}
func MachineSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.MachineSpec) *krmvertexaiv1alpha1.MachineSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.MachineSpec{}
	out.MachineType = direct.LazyPtr(in.GetMachineType())
	out.AcceleratorType = direct.Enum_FromProto(mapCtx, in.GetAcceleratorType())
	out.AcceleratorCount = direct.LazyPtr(in.GetAcceleratorCount())
	out.GpuPartitionSize = direct.LazyPtr(in.GetGpuPartitionSize())
	out.TpuTopology = direct.LazyPtr(in.GetTpuTopology())
	out.MultihostGpuNodeCount = direct.LazyPtr(in.GetMultihostGpuNodeCount())
	out.ReservationAffinity = ReservationAffinity_v1alpha1_FromProto(mapCtx, in.GetReservationAffinity())
	return out
}
func MachineSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.MachineSpec) *pb.MachineSpec {
	if in == nil {
		return nil
	}
	out := &pb.MachineSpec{}
	out.MachineType = direct.ValueOf(in.MachineType)
	out.AcceleratorType = direct.Enum_ToProto[pb.AcceleratorType](mapCtx, in.AcceleratorType)
	out.AcceleratorCount = direct.ValueOf(in.AcceleratorCount)
	out.GpuPartitionSize = direct.ValueOf(in.GpuPartitionSize)
	out.TpuTopology = direct.ValueOf(in.TpuTopology)
	out.MultihostGpuNodeCount = direct.ValueOf(in.MultihostGpuNodeCount)
	out.ReservationAffinity = ReservationAffinity_v1alpha1_ToProto(mapCtx, in.ReservationAffinity)
	return out
}
func ManualBatchTuningParameters_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ManualBatchTuningParameters) *krmvertexaiv1alpha1.ManualBatchTuningParameters {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ManualBatchTuningParameters{}
	out.BatchSize = direct.LazyPtr(in.GetBatchSize())
	return out
}
func ManualBatchTuningParameters_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ManualBatchTuningParameters) *pb.ManualBatchTuningParameters {
	if in == nil {
		return nil
	}
	out := &pb.ManualBatchTuningParameters{}
	out.BatchSize = direct.ValueOf(in.BatchSize)
	return out
}
func MetadataStore_DataplexConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore_DataplexConfig) *krmvertexaiv1alpha1.MetadataStore_DataplexConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.MetadataStore_DataplexConfig{}
	out.EnabledPipelinesLineage = direct.LazyPtr(in.GetEnabledPipelinesLineage())
	return out
}
func MetadataStore_DataplexConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.MetadataStore_DataplexConfig) *pb.MetadataStore_DataplexConfig {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore_DataplexConfig{}
	out.EnabledPipelinesLineage = direct.ValueOf(in.EnabledPipelinesLineage)
	return out
}
func MetadataStore_DataplexConfig_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore_DataplexConfig) *krmvertexaiv1beta1.MetadataStore_DataplexConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.MetadataStore_DataplexConfig{}
	out.EnabledPipelinesLineage = direct.LazyPtr(in.GetEnabledPipelinesLineage())
	return out
}
func MetadataStore_DataplexConfig_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.MetadataStore_DataplexConfig) *pb.MetadataStore_DataplexConfig {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore_DataplexConfig{}
	out.EnabledPipelinesLineage = direct.ValueOf(in.EnabledPipelinesLineage)
	return out
}
func MetadataStore_MetadataStoreState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore_MetadataStoreState) *krmvertexaiv1alpha1.MetadataStore_MetadataStoreState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.MetadataStore_MetadataStoreState{}
	out.DiskUtilizationBytes = direct.LazyPtr(in.GetDiskUtilizationBytes())
	return out
}
func MetadataStore_MetadataStoreState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.MetadataStore_MetadataStoreState) *pb.MetadataStore_MetadataStoreState {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore_MetadataStoreState{}
	out.DiskUtilizationBytes = direct.ValueOf(in.DiskUtilizationBytes)
	return out
}
func MetadataStore_MetadataStoreState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore_MetadataStoreState) *krmvertexaiv1beta1.MetadataStore_MetadataStoreState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.MetadataStore_MetadataStoreState{}
	out.DiskUtilizationBytes = direct.LazyPtr(in.GetDiskUtilizationBytes())
	return out
}
func MetadataStore_MetadataStoreState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.MetadataStore_MetadataStoreState) *pb.MetadataStore_MetadataStoreState {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore_MetadataStoreState{}
	out.DiskUtilizationBytes = direct.ValueOf(in.DiskUtilizationBytes)
	return out
}
func ModelContainerSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelContainerSpec) *krmvertexaiv1alpha1.ModelContainerSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelContainerSpec{}
	out.ImageURI = direct.LazyPtr(in.GetImageUri())
	out.Command = in.Command
	out.Args = in.Args
	out.Env = direct.Slice_FromProto(mapCtx, in.Env, EnvVar_v1alpha1_FromProto)
	out.Ports = direct.Slice_FromProto(mapCtx, in.Ports, Port_v1alpha1_FromProto)
	out.PredictRoute = direct.LazyPtr(in.GetPredictRoute())
	out.HealthRoute = direct.LazyPtr(in.GetHealthRoute())
	out.InvokeRoutePrefix = direct.LazyPtr(in.GetInvokeRoutePrefix())
	out.GrpcPorts = direct.Slice_FromProto(mapCtx, in.GrpcPorts, Port_v1alpha1_FromProto)
	out.DeploymentTimeout = direct.StringDuration_FromProto(mapCtx, in.GetDeploymentTimeout())
	out.SharedMemorySizeMb = direct.LazyPtr(in.GetSharedMemorySizeMb())
	out.StartupProbe = Probe_v1alpha1_FromProto(mapCtx, in.GetStartupProbe())
	out.HealthProbe = Probe_v1alpha1_FromProto(mapCtx, in.GetHealthProbe())
	out.LivenessProbe = Probe_v1alpha1_FromProto(mapCtx, in.GetLivenessProbe())
	return out
}
func ModelContainerSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelContainerSpec) *pb.ModelContainerSpec {
	if in == nil {
		return nil
	}
	out := &pb.ModelContainerSpec{}
	out.ImageUri = direct.ValueOf(in.ImageURI)
	out.Command = in.Command
	out.Args = in.Args
	out.Env = direct.Slice_ToProto(mapCtx, in.Env, EnvVar_v1alpha1_ToProto)
	out.Ports = direct.Slice_ToProto(mapCtx, in.Ports, Port_v1alpha1_ToProto)
	out.PredictRoute = direct.ValueOf(in.PredictRoute)
	out.HealthRoute = direct.ValueOf(in.HealthRoute)
	out.InvokeRoutePrefix = direct.ValueOf(in.InvokeRoutePrefix)
	out.GrpcPorts = direct.Slice_ToProto(mapCtx, in.GrpcPorts, Port_v1alpha1_ToProto)
	out.DeploymentTimeout = direct.StringDuration_ToProto(mapCtx, in.DeploymentTimeout)
	out.SharedMemorySizeMb = direct.ValueOf(in.SharedMemorySizeMb)
	out.StartupProbe = Probe_v1alpha1_ToProto(mapCtx, in.StartupProbe)
	out.HealthProbe = Probe_v1alpha1_ToProto(mapCtx, in.HealthProbe)
	out.LivenessProbe = Probe_v1alpha1_ToProto(mapCtx, in.LivenessProbe)
	return out
}
func ModelMonitoringAlertConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringAlertConfig) *krmvertexaiv1alpha1.ModelMonitoringAlertConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringAlertConfig{}
	out.EmailAlertConfig = ModelMonitoringAlertConfig_EmailAlertConfig_v1alpha1_FromProto(mapCtx, in.GetEmailAlertConfig())
	out.EnableLogging = direct.LazyPtr(in.GetEnableLogging())
	out.NotificationChannels = in.NotificationChannels
	return out
}
func ModelMonitoringAlertConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringAlertConfig) *pb.ModelMonitoringAlertConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringAlertConfig{}
	if oneof := ModelMonitoringAlertConfig_EmailAlertConfig_v1alpha1_ToProto(mapCtx, in.EmailAlertConfig); oneof != nil {
		out.Alert = &pb.ModelMonitoringAlertConfig_EmailAlertConfig_{EmailAlertConfig: oneof}
	}
	out.EnableLogging = direct.ValueOf(in.EnableLogging)
	out.NotificationChannels = in.NotificationChannels
	return out
}
func ModelMonitoringAlertConfig_EmailAlertConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringAlertConfig_EmailAlertConfig) *krmvertexaiv1alpha1.ModelMonitoringAlertConfig_EmailAlertConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringAlertConfig_EmailAlertConfig{}
	out.UserEmails = in.UserEmails
	return out
}
func ModelMonitoringAlertConfig_EmailAlertConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringAlertConfig_EmailAlertConfig) *pb.ModelMonitoringAlertConfig_EmailAlertConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringAlertConfig_EmailAlertConfig{}
	out.UserEmails = in.UserEmails
	return out
}
func ModelMonitoringConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringConfig) *krmvertexaiv1alpha1.ModelMonitoringConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringConfig{}
	out.ObjectiveConfigs = direct.Slice_FromProto(mapCtx, in.ObjectiveConfigs, ModelMonitoringObjectiveConfig_v1alpha1_FromProto)
	out.AlertConfig = ModelMonitoringAlertConfig_v1alpha1_FromProto(mapCtx, in.GetAlertConfig())
	out.AnalysisInstanceSchemaURI = direct.LazyPtr(in.GetAnalysisInstanceSchemaUri())
	out.StatsAnomaliesBaseDirectory = GCSDestination_v1alpha1_FromProto(mapCtx, in.GetStatsAnomaliesBaseDirectory())
	return out
}
func ModelMonitoringConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringConfig) *pb.ModelMonitoringConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringConfig{}
	out.ObjectiveConfigs = direct.Slice_ToProto(mapCtx, in.ObjectiveConfigs, ModelMonitoringObjectiveConfig_v1alpha1_ToProto)
	out.AlertConfig = ModelMonitoringAlertConfig_v1alpha1_ToProto(mapCtx, in.AlertConfig)
	out.AnalysisInstanceSchemaUri = direct.ValueOf(in.AnalysisInstanceSchemaURI)
	out.StatsAnomaliesBaseDirectory = GCSDestination_v1alpha1_ToProto(mapCtx, in.StatsAnomaliesBaseDirectory)
	return out
}
func ModelMonitoringObjectiveConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringObjectiveConfig) *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig{}
	out.TrainingDataset = ModelMonitoringObjectiveConfig_TrainingDataset_v1alpha1_FromProto(mapCtx, in.GetTrainingDataset())
	out.TrainingPredictionSkewDetectionConfig = ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig_v1alpha1_FromProto(mapCtx, in.GetTrainingPredictionSkewDetectionConfig())
	out.PredictionDriftDetectionConfig = ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig_v1alpha1_FromProto(mapCtx, in.GetPredictionDriftDetectionConfig())
	out.ExplanationConfig = ModelMonitoringObjectiveConfig_ExplanationConfig_v1alpha1_FromProto(mapCtx, in.GetExplanationConfig())
	return out
}
func ModelMonitoringObjectiveConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig) *pb.ModelMonitoringObjectiveConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringObjectiveConfig{}
	out.TrainingDataset = ModelMonitoringObjectiveConfig_TrainingDataset_v1alpha1_ToProto(mapCtx, in.TrainingDataset)
	out.TrainingPredictionSkewDetectionConfig = ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig_v1alpha1_ToProto(mapCtx, in.TrainingPredictionSkewDetectionConfig)
	out.PredictionDriftDetectionConfig = ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig_v1alpha1_ToProto(mapCtx, in.PredictionDriftDetectionConfig)
	out.ExplanationConfig = ModelMonitoringObjectiveConfig_ExplanationConfig_v1alpha1_ToProto(mapCtx, in.ExplanationConfig)
	return out
}
func ModelMonitoringObjectiveConfig_ExplanationConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringObjectiveConfig_ExplanationConfig) *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_ExplanationConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_ExplanationConfig{}
	out.EnableFeatureAttributes = direct.LazyPtr(in.GetEnableFeatureAttributes())
	out.ExplanationBaseline = ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_v1alpha1_FromProto(mapCtx, in.GetExplanationBaseline())
	return out
}
func ModelMonitoringObjectiveConfig_ExplanationConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_ExplanationConfig) *pb.ModelMonitoringObjectiveConfig_ExplanationConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringObjectiveConfig_ExplanationConfig{}
	out.EnableFeatureAttributes = direct.ValueOf(in.EnableFeatureAttributes)
	out.ExplanationBaseline = ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_v1alpha1_ToProto(mapCtx, in.ExplanationBaseline)
	return out
}
func ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline) *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline{}
	out.GCS = GCSDestination_v1alpha1_FromProto(mapCtx, in.GetGcs())
	out.Bigquery = BigQueryDestination_v1alpha1_FromProto(mapCtx, in.GetBigquery())
	out.PredictionFormat = direct.Enum_FromProto(mapCtx, in.GetPredictionFormat())
	return out
}
func ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline) *pb.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline{}
	if oneof := GCSDestination_v1alpha1_ToProto(mapCtx, in.GCS); oneof != nil {
		out.Destination = &pb.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_Gcs{Gcs: oneof}
	}
	if oneof := BigQueryDestination_v1alpha1_ToProto(mapCtx, in.Bigquery); oneof != nil {
		out.Destination = &pb.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_Bigquery{Bigquery: oneof}
	}
	out.PredictionFormat = direct.Enum_ToProto[pb.ModelMonitoringObjectiveConfig_ExplanationConfig_ExplanationBaseline_PredictionFormat](mapCtx, in.PredictionFormat)
	return out
}
func ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig) *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig{}
	// MISSING: DriftThresholds
	// MISSING: AttributionScoreDriftThresholds
	out.DefaultDriftThreshold = ThresholdConfig_v1alpha1_FromProto(mapCtx, in.GetDefaultDriftThreshold())
	return out
}
func ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig) *pb.ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringObjectiveConfig_PredictionDriftDetectionConfig{}
	// MISSING: DriftThresholds
	// MISSING: AttributionScoreDriftThresholds
	out.DefaultDriftThreshold = ThresholdConfig_v1alpha1_ToProto(mapCtx, in.DefaultDriftThreshold)
	return out
}
func ModelMonitoringObjectiveConfig_TrainingDataset_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringObjectiveConfig_TrainingDataset) *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_TrainingDataset {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_TrainingDataset{}
	out.Dataset = direct.LazyPtr(in.GetDataset())
	out.GCSSource = GCSSource_v1alpha1_FromProto(mapCtx, in.GetGcsSource())
	out.BigquerySource = BigQuerySource_v1alpha1_FromProto(mapCtx, in.GetBigquerySource())
	out.DataFormat = direct.LazyPtr(in.GetDataFormat())
	out.TargetField = direct.LazyPtr(in.GetTargetField())
	out.LoggingSamplingStrategy = SamplingStrategy_v1alpha1_FromProto(mapCtx, in.GetLoggingSamplingStrategy())
	return out
}
func ModelMonitoringObjectiveConfig_TrainingDataset_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_TrainingDataset) *pb.ModelMonitoringObjectiveConfig_TrainingDataset {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringObjectiveConfig_TrainingDataset{}
	if oneof := ModelMonitoringObjectiveConfig_TrainingDataset_Dataset_ToProto(mapCtx, in.Dataset); oneof != nil {
		out.DataSource = oneof
	}
	if oneof := GCSSource_v1alpha1_ToProto(mapCtx, in.GCSSource); oneof != nil {
		out.DataSource = &pb.ModelMonitoringObjectiveConfig_TrainingDataset_GcsSource{GcsSource: oneof}
	}
	if oneof := BigQuerySource_v1alpha1_ToProto(mapCtx, in.BigquerySource); oneof != nil {
		out.DataSource = &pb.ModelMonitoringObjectiveConfig_TrainingDataset_BigquerySource{BigquerySource: oneof}
	}
	out.DataFormat = direct.ValueOf(in.DataFormat)
	out.TargetField = direct.ValueOf(in.TargetField)
	out.LoggingSamplingStrategy = SamplingStrategy_v1alpha1_ToProto(mapCtx, in.LoggingSamplingStrategy)
	return out
}
func ModelMonitoringObjectiveConfig_TrainingDataset_Dataset_ToProto(mapCtx *direct.MapContext, in *string) *pb.ModelMonitoringObjectiveConfig_TrainingDataset_Dataset {
	if in == nil {
		return nil
	}
	return &pb.ModelMonitoringObjectiveConfig_TrainingDataset_Dataset{Dataset: *in}
}
func ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig) *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig{}
	// MISSING: SkewThresholds
	// MISSING: AttributionScoreSkewThresholds
	out.DefaultSkewThreshold = ThresholdConfig_v1alpha1_FromProto(mapCtx, in.GetDefaultSkewThreshold())
	return out
}
func ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig) *pb.ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringObjectiveConfig_TrainingPredictionSkewDetectionConfig{}
	// MISSING: SkewThresholds
	// MISSING: AttributionScoreSkewThresholds
	out.DefaultSkewThreshold = ThresholdConfig_v1alpha1_ToProto(mapCtx, in.DefaultSkewThreshold)
	return out
}
func ModelMonitoringStatsAnomalies_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringStatsAnomalies) *krmvertexaiv1alpha1.ModelMonitoringStatsAnomalies {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringStatsAnomalies{}
	out.Objective = direct.Enum_FromProto(mapCtx, in.GetObjective())
	out.DeployedModelID = direct.LazyPtr(in.GetDeployedModelId())
	out.AnomalyCount = direct.LazyPtr(in.GetAnomalyCount())
	out.FeatureStats = direct.Slice_FromProto(mapCtx, in.FeatureStats, ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies_v1alpha1_FromProto)
	return out
}
func ModelMonitoringStatsAnomalies_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringStatsAnomalies) *pb.ModelMonitoringStatsAnomalies {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringStatsAnomalies{}
	out.Objective = direct.Enum_ToProto[pb.ModelDeploymentMonitoringObjectiveType](mapCtx, in.Objective)
	out.DeployedModelId = direct.ValueOf(in.DeployedModelID)
	out.AnomalyCount = direct.ValueOf(in.AnomalyCount)
	out.FeatureStats = direct.Slice_ToProto(mapCtx, in.FeatureStats, ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies_v1alpha1_ToProto)
	return out
}
func ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies) *krmvertexaiv1alpha1.ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies{}
	out.FeatureDisplayName = direct.LazyPtr(in.GetFeatureDisplayName())
	out.Threshold = ThresholdConfig_v1alpha1_FromProto(mapCtx, in.GetThreshold())
	out.TrainingStats = FeatureStatsAnomaly_v1alpha1_FromProto(mapCtx, in.GetTrainingStats())
	out.PredictionStats = direct.Slice_FromProto(mapCtx, in.PredictionStats, FeatureStatsAnomaly_v1alpha1_FromProto)
	return out
}
func ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies) *pb.ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies {
	if in == nil {
		return nil
	}
	out := &pb.ModelMonitoringStatsAnomalies_FeatureHistoricStatsAnomalies{}
	out.FeatureDisplayName = direct.ValueOf(in.FeatureDisplayName)
	out.Threshold = ThresholdConfig_v1alpha1_ToProto(mapCtx, in.Threshold)
	out.TrainingStats = FeatureStatsAnomaly_v1alpha1_ToProto(mapCtx, in.TrainingStats)
	out.PredictionStats = direct.Slice_ToProto(mapCtx, in.PredictionStats, FeatureStatsAnomaly_v1alpha1_ToProto)
	return out
}
func NfsMount_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.NfsMount) *krmvertexaiv1alpha1.NfsMount {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.NfsMount{}
	out.Server = direct.LazyPtr(in.GetServer())
	out.Path = direct.LazyPtr(in.GetPath())
	out.MountPoint = direct.LazyPtr(in.GetMountPoint())
	return out
}
func NfsMount_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.NfsMount) *pb.NfsMount {
	if in == nil {
		return nil
	}
	out := &pb.NfsMount{}
	out.Server = direct.ValueOf(in.Server)
	out.Path = direct.ValueOf(in.Path)
	out.MountPoint = direct.ValueOf(in.MountPoint)
	return out
}
func PSCInterfaceConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PscInterfaceConfig) *krmvertexaiv1alpha1.PSCInterfaceConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.PSCInterfaceConfig{}
	out.NetworkAttachment = direct.LazyPtr(in.GetNetworkAttachment())
	out.DNSPeeringConfigs = direct.Slice_FromProto(mapCtx, in.DnsPeeringConfigs, DNSPeeringConfig_v1alpha1_FromProto)
	return out
}
func PSCInterfaceConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.PSCInterfaceConfig) *pb.PscInterfaceConfig {
	if in == nil {
		return nil
	}
	out := &pb.PscInterfaceConfig{}
	out.NetworkAttachment = direct.ValueOf(in.NetworkAttachment)
	out.DnsPeeringConfigs = direct.Slice_ToProto(mapCtx, in.DNSPeeringConfigs, DNSPeeringConfig_v1alpha1_ToProto)
	return out
}
func Port_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Port) *krmvertexaiv1alpha1.Port {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Port{}
	out.ContainerPort = direct.LazyPtr(in.GetContainerPort())
	return out
}
func Port_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Port) *pb.Port {
	if in == nil {
		return nil
	}
	out := &pb.Port{}
	out.ContainerPort = direct.ValueOf(in.ContainerPort)
	return out
}
func PredictSchemata_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PredictSchemata) *krmvertexaiv1alpha1.PredictSchemata {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.PredictSchemata{}
	out.InstanceSchemaURI = direct.LazyPtr(in.GetInstanceSchemaUri())
	out.ParametersSchemaURI = direct.LazyPtr(in.GetParametersSchemaUri())
	out.PredictionSchemaURI = direct.LazyPtr(in.GetPredictionSchemaUri())
	return out
}
func PredictSchemata_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.PredictSchemata) *pb.PredictSchemata {
	if in == nil {
		return nil
	}
	out := &pb.PredictSchemata{}
	out.InstanceSchemaUri = direct.ValueOf(in.InstanceSchemaURI)
	out.ParametersSchemaUri = direct.ValueOf(in.ParametersSchemaURI)
	out.PredictionSchemaUri = direct.ValueOf(in.PredictionSchemaURI)
	return out
}
func Probe_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Probe) *krmvertexaiv1alpha1.Probe {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Probe{}
	out.Exec = Probe_ExecAction_v1alpha1_FromProto(mapCtx, in.GetExec())
	out.HTTPGet = Probe_HTTPGetAction_v1alpha1_FromProto(mapCtx, in.GetHttpGet())
	out.Grpc = Probe_GrpcAction_v1alpha1_FromProto(mapCtx, in.GetGrpc())
	out.TCPSocket = Probe_TCPSocketAction_v1alpha1_FromProto(mapCtx, in.GetTcpSocket())
	out.PeriodSeconds = direct.LazyPtr(in.GetPeriodSeconds())
	out.TimeoutSeconds = direct.LazyPtr(in.GetTimeoutSeconds())
	out.FailureThreshold = direct.LazyPtr(in.GetFailureThreshold())
	out.SuccessThreshold = direct.LazyPtr(in.GetSuccessThreshold())
	out.InitialDelaySeconds = direct.LazyPtr(in.GetInitialDelaySeconds())
	return out
}
func Probe_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Probe) *pb.Probe {
	if in == nil {
		return nil
	}
	out := &pb.Probe{}
	if oneof := Probe_ExecAction_v1alpha1_ToProto(mapCtx, in.Exec); oneof != nil {
		out.ProbeType = &pb.Probe_Exec{Exec: oneof}
	}
	if oneof := Probe_HTTPGetAction_v1alpha1_ToProto(mapCtx, in.HTTPGet); oneof != nil {
		out.ProbeType = &pb.Probe_HttpGet{HttpGet: oneof}
	}
	if oneof := Probe_GrpcAction_v1alpha1_ToProto(mapCtx, in.Grpc); oneof != nil {
		out.ProbeType = &pb.Probe_Grpc{Grpc: oneof}
	}
	if oneof := Probe_TCPSocketAction_v1alpha1_ToProto(mapCtx, in.TCPSocket); oneof != nil {
		out.ProbeType = &pb.Probe_TcpSocket{TcpSocket: oneof}
	}
	out.PeriodSeconds = direct.ValueOf(in.PeriodSeconds)
	out.TimeoutSeconds = direct.ValueOf(in.TimeoutSeconds)
	out.FailureThreshold = direct.ValueOf(in.FailureThreshold)
	out.SuccessThreshold = direct.ValueOf(in.SuccessThreshold)
	out.InitialDelaySeconds = direct.ValueOf(in.InitialDelaySeconds)
	return out
}
func Probe_ExecAction_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Probe_ExecAction) *krmvertexaiv1alpha1.Probe_ExecAction {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Probe_ExecAction{}
	out.Command = in.Command
	return out
}
func Probe_ExecAction_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Probe_ExecAction) *pb.Probe_ExecAction {
	if in == nil {
		return nil
	}
	out := &pb.Probe_ExecAction{}
	out.Command = in.Command
	return out
}
func Probe_GrpcAction_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Probe_GrpcAction) *krmvertexaiv1alpha1.Probe_GrpcAction {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Probe_GrpcAction{}
	out.Port = direct.LazyPtr(in.GetPort())
	out.Service = direct.LazyPtr(in.GetService())
	return out
}
func Probe_GrpcAction_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Probe_GrpcAction) *pb.Probe_GrpcAction {
	if in == nil {
		return nil
	}
	out := &pb.Probe_GrpcAction{}
	out.Port = direct.ValueOf(in.Port)
	out.Service = direct.ValueOf(in.Service)
	return out
}
func Probe_HTTPGetAction_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Probe_HttpGetAction) *krmvertexaiv1alpha1.Probe_HTTPGetAction {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Probe_HTTPGetAction{}
	out.Path = direct.LazyPtr(in.GetPath())
	out.Port = direct.LazyPtr(in.GetPort())
	out.Host = direct.LazyPtr(in.GetHost())
	out.Scheme = direct.LazyPtr(in.GetScheme())
	out.HTTPHeaders = direct.Slice_FromProto(mapCtx, in.HttpHeaders, Probe_HTTPHeader_v1alpha1_FromProto)
	return out
}
func Probe_HTTPGetAction_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Probe_HTTPGetAction) *pb.Probe_HttpGetAction {
	if in == nil {
		return nil
	}
	out := &pb.Probe_HttpGetAction{}
	out.Path = direct.ValueOf(in.Path)
	out.Port = direct.ValueOf(in.Port)
	out.Host = direct.ValueOf(in.Host)
	out.Scheme = direct.ValueOf(in.Scheme)
	out.HttpHeaders = direct.Slice_ToProto(mapCtx, in.HTTPHeaders, Probe_HTTPHeader_v1alpha1_ToProto)
	return out
}
func Probe_HTTPHeader_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Probe_HttpHeader) *krmvertexaiv1alpha1.Probe_HTTPHeader {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Probe_HTTPHeader{}
	out.Name = direct.LazyPtr(in.GetName())
	out.Value = direct.LazyPtr(in.GetValue())
	return out
}
func Probe_HTTPHeader_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Probe_HTTPHeader) *pb.Probe_HttpHeader {
	if in == nil {
		return nil
	}
	out := &pb.Probe_HttpHeader{}
	out.Name = direct.ValueOf(in.Name)
	out.Value = direct.ValueOf(in.Value)
	return out
}
func Probe_TCPSocketAction_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Probe_TcpSocketAction) *krmvertexaiv1alpha1.Probe_TCPSocketAction {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Probe_TCPSocketAction{}
	out.Port = direct.LazyPtr(in.GetPort())
	out.Host = direct.LazyPtr(in.GetHost())
	return out
}
func Probe_TCPSocketAction_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Probe_TCPSocketAction) *pb.Probe_TcpSocketAction {
	if in == nil {
		return nil
	}
	out := &pb.Probe_TcpSocketAction{}
	out.Port = direct.ValueOf(in.Port)
	out.Host = direct.ValueOf(in.Host)
	return out
}
func PythonPackageSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.PythonPackageSpec) *krmvertexaiv1alpha1.PythonPackageSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.PythonPackageSpec{}
	out.ExecutorImageURI = direct.LazyPtr(in.GetExecutorImageUri())
	// MISSING: PackageUris
	// (near miss): "PackageUris" vs "PackageURIs"
	out.PythonModule = direct.LazyPtr(in.GetPythonModule())
	out.Args = in.Args
	// MISSING: Env
	return out
}
func PythonPackageSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.PythonPackageSpec) *pb.PythonPackageSpec {
	if in == nil {
		return nil
	}
	out := &pb.PythonPackageSpec{}
	out.ExecutorImageUri = direct.ValueOf(in.ExecutorImageURI)
	// MISSING: PackageUris
	// (near miss): "PackageUris" vs "PackageURIs"
	out.PythonModule = direct.ValueOf(in.PythonModule)
	out.Args = in.Args
	// MISSING: Env
	return out
}
func ReservationAffinity_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ReservationAffinity) *krmvertexaiv1alpha1.ReservationAffinity {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ReservationAffinity{}
	out.ReservationAffinityType = direct.Enum_FromProto(mapCtx, in.GetReservationAffinityType())
	out.Key = direct.LazyPtr(in.GetKey())
	out.Values = in.Values
	return out
}
func ReservationAffinity_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ReservationAffinity) *pb.ReservationAffinity {
	if in == nil {
		return nil
	}
	out := &pb.ReservationAffinity{}
	out.ReservationAffinityType = direct.Enum_ToProto[pb.ReservationAffinity_Type](mapCtx, in.ReservationAffinityType)
	out.Key = direct.ValueOf(in.Key)
	out.Values = in.Values
	return out
}
func ResourcesConsumedObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ResourcesConsumed) *krmvertexaiv1alpha1.ResourcesConsumedObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ResourcesConsumedObservedState{}
	out.ReplicaHours = direct.LazyPtr(in.GetReplicaHours())
	return out
}
func ResourcesConsumedObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ResourcesConsumedObservedState) *pb.ResourcesConsumed {
	if in == nil {
		return nil
	}
	out := &pb.ResourcesConsumed{}
	out.ReplicaHours = direct.ValueOf(in.ReplicaHours)
	return out
}
func SampleConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SampleConfig) *krmvertexaiv1alpha1.SampleConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.SampleConfig{}
	out.InitialBatchSamplePercentage = direct.LazyPtr(in.GetInitialBatchSamplePercentage())
	out.FollowingBatchSamplePercentage = direct.LazyPtr(in.GetFollowingBatchSamplePercentage())
	out.SampleStrategy = direct.Enum_FromProto(mapCtx, in.GetSampleStrategy())
	return out
}
func SampleConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.SampleConfig) *pb.SampleConfig {
	if in == nil {
		return nil
	}
	out := &pb.SampleConfig{}
	if oneof := SampleConfig_InitialBatchSamplePercentage_ToProto(mapCtx, in.InitialBatchSamplePercentage); oneof != nil {
		out.InitialBatchSampleSize = oneof
	}
	if oneof := SampleConfig_FollowingBatchSamplePercentage_ToProto(mapCtx, in.FollowingBatchSamplePercentage); oneof != nil {
		out.FollowingBatchSampleSize = oneof
	}
	out.SampleStrategy = direct.Enum_ToProto[pb.SampleConfig_SampleStrategy](mapCtx, in.SampleStrategy)
	return out
}
func SampleConfig_InitialBatchSamplePercentage_ToProto(mapCtx *direct.MapContext, in *int32) *pb.SampleConfig_InitialBatchSamplePercentage {
	if in == nil {
		return nil
	}
	return &pb.SampleConfig_InitialBatchSamplePercentage{InitialBatchSamplePercentage: *in}
}
func SampleConfig_FollowingBatchSamplePercentage_ToProto(mapCtx *direct.MapContext, in *int32) *pb.SampleConfig_FollowingBatchSamplePercentage {
	if in == nil {
		return nil
	}
	return &pb.SampleConfig_FollowingBatchSamplePercentage{FollowingBatchSamplePercentage: *in}
}
func SamplingStrategy_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SamplingStrategy) *krmvertexaiv1alpha1.SamplingStrategy {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.SamplingStrategy{}
	out.RandomSampleConfig = SamplingStrategy_RandomSampleConfig_v1alpha1_FromProto(mapCtx, in.GetRandomSampleConfig())
	return out
}
func SamplingStrategy_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.SamplingStrategy) *pb.SamplingStrategy {
	if in == nil {
		return nil
	}
	out := &pb.SamplingStrategy{}
	out.RandomSampleConfig = SamplingStrategy_RandomSampleConfig_v1alpha1_ToProto(mapCtx, in.RandomSampleConfig)
	return out
}
func SamplingStrategy_RandomSampleConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.SamplingStrategy_RandomSampleConfig) *krmvertexaiv1alpha1.SamplingStrategy_RandomSampleConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.SamplingStrategy_RandomSampleConfig{}
	out.SampleRate = direct.LazyPtr(in.GetSampleRate())
	return out
}
func SamplingStrategy_RandomSampleConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.SamplingStrategy_RandomSampleConfig) *pb.SamplingStrategy_RandomSampleConfig {
	if in == nil {
		return nil
	}
	out := &pb.SamplingStrategy_RandomSampleConfig{}
	out.SampleRate = direct.ValueOf(in.SampleRate)
	return out
}
func Scheduling_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Scheduling) *krmvertexaiv1alpha1.Scheduling {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.Scheduling{}
	out.Timeout = direct.StringDuration_FromProto(mapCtx, in.GetTimeout())
	out.RestartJobOnWorkerRestart = direct.LazyPtr(in.GetRestartJobOnWorkerRestart())
	out.Strategy = direct.Enum_FromProto(mapCtx, in.GetStrategy())
	out.DisableRetries = direct.LazyPtr(in.GetDisableRetries())
	out.MaxWaitDuration = direct.StringDuration_FromProto(mapCtx, in.GetMaxWaitDuration())
	return out
}
func Scheduling_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.Scheduling) *pb.Scheduling {
	if in == nil {
		return nil
	}
	out := &pb.Scheduling{}
	out.Timeout = direct.StringDuration_ToProto(mapCtx, in.Timeout)
	out.RestartJobOnWorkerRestart = direct.ValueOf(in.RestartJobOnWorkerRestart)
	out.Strategy = direct.Enum_ToProto[pb.Scheduling_Strategy](mapCtx, in.Strategy)
	out.DisableRetries = direct.ValueOf(in.DisableRetries)
	out.MaxWaitDuration = direct.StringDuration_ToProto(mapCtx, in.MaxWaitDuration)
	return out
}
func ThresholdConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ThresholdConfig) *krmvertexaiv1alpha1.ThresholdConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.ThresholdConfig{}
	out.Value = direct.LazyPtr(in.GetValue())
	return out
}
func ThresholdConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.ThresholdConfig) *pb.ThresholdConfig {
	if in == nil {
		return nil
	}
	out := &pb.ThresholdConfig{}
	if oneof := ThresholdConfig_Value_ToProto(mapCtx, in.Value); oneof != nil {
		out.Threshold = oneof
	}
	return out
}
func ThresholdConfig_Value_ToProto(mapCtx *direct.MapContext, in *float64) *pb.ThresholdConfig_Value {
	if in == nil {
		return nil
	}
	return &pb.ThresholdConfig_Value{Value: *in}
}
func TrainingConfig_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.TrainingConfig) *krmvertexaiv1alpha1.TrainingConfig {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.TrainingConfig{}
	out.TimeoutTrainingMilliHours = direct.LazyPtr(in.GetTimeoutTrainingMilliHours())
	return out
}
func TrainingConfig_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.TrainingConfig) *pb.TrainingConfig {
	if in == nil {
		return nil
	}
	out := &pb.TrainingConfig{}
	out.TimeoutTrainingMilliHours = direct.ValueOf(in.TimeoutTrainingMilliHours)
	return out
}
func UnmanagedContainerModel_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.UnmanagedContainerModel) *krmvertexaiv1alpha1.UnmanagedContainerModel {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.UnmanagedContainerModel{}
	out.ArtifactURI = direct.LazyPtr(in.GetArtifactUri())
	out.PredictSchemata = PredictSchemata_v1alpha1_FromProto(mapCtx, in.GetPredictSchemata())
	out.ContainerSpec = ModelContainerSpec_v1alpha1_FromProto(mapCtx, in.GetContainerSpec())
	return out
}
func UnmanagedContainerModel_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.UnmanagedContainerModel) *pb.UnmanagedContainerModel {
	if in == nil {
		return nil
	}
	out := &pb.UnmanagedContainerModel{}
	out.ArtifactUri = direct.ValueOf(in.ArtifactURI)
	out.PredictSchemata = PredictSchemata_v1alpha1_ToProto(mapCtx, in.PredictSchemata)
	out.ContainerSpec = ModelContainerSpec_v1alpha1_ToProto(mapCtx, in.ContainerSpec)
	return out
}
func VertexAIBatchPredictionJobObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchPredictionJob) *krmvertexaiv1alpha1.VertexAIBatchPredictionJobObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIBatchPredictionJobObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.ModelVersionID = direct.LazyPtr(in.GetModelVersionId())
	// MISSING: ModelParameters
	// MISSING: ExplanationSpec
	out.OutputInfo = BatchPredictionJob_OutputInfoObservedState_v1alpha1_FromProto(mapCtx, in.GetOutputInfo())
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.Error = direct.Status_FromProto(mapCtx, in.GetError())
	// MISSING: PartialFailures
	out.ResourcesConsumed = ResourcesConsumedObservedState_v1alpha1_FromProto(mapCtx, in.GetResourcesConsumed())
	out.CompletionStats = CompletionStatsObservedState_v1alpha1_FromProto(mapCtx, in.GetCompletionStats())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.ModelMonitoringStatus = direct.Status_FromProto(mapCtx, in.GetModelMonitoringStatus())
	out.SatisfiesPzs = direct.LazyPtr(in.GetSatisfiesPzs())
	out.SatisfiesPzi = direct.LazyPtr(in.GetSatisfiesPzi())
	return out
}
func VertexAIBatchPredictionJobObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIBatchPredictionJobObservedState) *pb.BatchPredictionJob {
	if in == nil {
		return nil
	}
	out := &pb.BatchPredictionJob{}
	out.Name = direct.ValueOf(in.Name)
	out.ModelVersionId = direct.ValueOf(in.ModelVersionID)
	// MISSING: ModelParameters
	// MISSING: ExplanationSpec
	out.OutputInfo = BatchPredictionJob_OutputInfoObservedState_v1alpha1_ToProto(mapCtx, in.OutputInfo)
	out.State = direct.Enum_ToProto[pb.JobState](mapCtx, in.State)
	out.Error = direct.Status_ToProto(mapCtx, in.Error)
	// MISSING: PartialFailures
	out.ResourcesConsumed = ResourcesConsumedObservedState_v1alpha1_ToProto(mapCtx, in.ResourcesConsumed)
	out.CompletionStats = CompletionStatsObservedState_v1alpha1_ToProto(mapCtx, in.CompletionStats)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.ModelMonitoringStatus = direct.Status_ToProto(mapCtx, in.ModelMonitoringStatus)
	out.SatisfiesPzs = direct.ValueOf(in.SatisfiesPzs)
	out.SatisfiesPzi = direct.ValueOf(in.SatisfiesPzi)
	return out
}
func VertexAIBatchPredictionJobSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.BatchPredictionJob) *krmvertexaiv1alpha1.VertexAIBatchPredictionJobSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIBatchPredictionJobSpec{}
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	out.Model = direct.LazyPtr(in.GetModel())
	out.UnmanagedContainerModel = UnmanagedContainerModel_v1alpha1_FromProto(mapCtx, in.GetUnmanagedContainerModel())
	out.InputConfig = BatchPredictionJob_InputConfig_v1alpha1_FromProto(mapCtx, in.GetInputConfig())
	out.InstanceConfig = BatchPredictionJob_InstanceConfig_v1alpha1_FromProto(mapCtx, in.GetInstanceConfig())
	// MISSING: ModelParameters
	out.OutputConfig = BatchPredictionJob_OutputConfig_v1alpha1_FromProto(mapCtx, in.GetOutputConfig())
	out.DedicatedResources = BatchDedicatedResources_v1alpha1_FromProto(mapCtx, in.GetDedicatedResources())
	if in.GetServiceAccount() != "" {
		out.ServiceAccountRef = &refsv1beta1.IAMServiceAccountRef{External: in.GetServiceAccount()}
	}
	out.ManualBatchTuningParameters = ManualBatchTuningParameters_v1alpha1_FromProto(mapCtx, in.GetManualBatchTuningParameters())
	out.GenerateExplanation = direct.LazyPtr(in.GetGenerateExplanation())
	// MISSING: ExplanationSpec
	// MISSING: PartialFailures
	out.Labels = in.Labels
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	out.ModelMonitoringConfig = ModelMonitoringConfig_v1alpha1_FromProto(mapCtx, in.GetModelMonitoringConfig())
	out.ModelMonitoringStatsAnomalies = direct.Slice_FromProto(mapCtx, in.ModelMonitoringStatsAnomalies, ModelMonitoringStatsAnomalies_v1alpha1_FromProto)
	out.DisableContainerLogging = direct.LazyPtr(in.GetDisableContainerLogging())
	return out
}
func VertexAIBatchPredictionJobSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIBatchPredictionJobSpec) *pb.BatchPredictionJob {
	if in == nil {
		return nil
	}
	out := &pb.BatchPredictionJob{}
	out.DisplayName = direct.ValueOf(in.DisplayName)
	out.Model = direct.ValueOf(in.Model)
	out.UnmanagedContainerModel = UnmanagedContainerModel_v1alpha1_ToProto(mapCtx, in.UnmanagedContainerModel)
	out.InputConfig = BatchPredictionJob_InputConfig_v1alpha1_ToProto(mapCtx, in.InputConfig)
	out.InstanceConfig = BatchPredictionJob_InstanceConfig_v1alpha1_ToProto(mapCtx, in.InstanceConfig)
	// MISSING: ModelParameters
	out.OutputConfig = BatchPredictionJob_OutputConfig_v1alpha1_ToProto(mapCtx, in.OutputConfig)
	out.DedicatedResources = BatchDedicatedResources_v1alpha1_ToProto(mapCtx, in.DedicatedResources)
	if in.ServiceAccountRef != nil {
		out.ServiceAccount = in.ServiceAccountRef.External
	}
	out.ManualBatchTuningParameters = ManualBatchTuningParameters_v1alpha1_ToProto(mapCtx, in.ManualBatchTuningParameters)
	out.GenerateExplanation = direct.ValueOf(in.GenerateExplanation)
	// MISSING: ExplanationSpec
	// MISSING: PartialFailures
	out.Labels = in.Labels
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	out.ModelMonitoringConfig = ModelMonitoringConfig_v1alpha1_ToProto(mapCtx, in.ModelMonitoringConfig)
	out.ModelMonitoringStatsAnomalies = direct.Slice_ToProto(mapCtx, in.ModelMonitoringStatsAnomalies, ModelMonitoringStatsAnomalies_v1alpha1_ToProto)
	out.DisableContainerLogging = direct.ValueOf(in.DisableContainerLogging)
	return out
}
func VertexAICustomJobObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomJob) *krmvertexaiv1alpha1.VertexAICustomJobObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAICustomJobObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.StartTime = direct.StringTimestamp_FromProto(mapCtx, in.GetStartTime())
	out.EndTime = direct.StringTimestamp_FromProto(mapCtx, in.GetEndTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.Error = direct.Status_FromProto(mapCtx, in.GetError())
	// MISSING: WebAccessUris
	// (near miss): "WebAccessUris" vs "WebAccessURIs"
	out.SatisfiesPzs = direct.LazyPtr(in.GetSatisfiesPzs())
	out.SatisfiesPzi = direct.LazyPtr(in.GetSatisfiesPzi())
	return out
}
func VertexAICustomJobObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAICustomJobObservedState) *pb.CustomJob {
	if in == nil {
		return nil
	}
	out := &pb.CustomJob{}
	out.Name = direct.ValueOf(in.Name)
	out.State = direct.Enum_ToProto[pb.JobState](mapCtx, in.State)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.StartTime = direct.StringTimestamp_ToProto(mapCtx, in.StartTime)
	out.EndTime = direct.StringTimestamp_ToProto(mapCtx, in.EndTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.Error = direct.Status_ToProto(mapCtx, in.Error)
	// MISSING: WebAccessUris
	// (near miss): "WebAccessUris" vs "WebAccessURIs"
	out.SatisfiesPzs = direct.ValueOf(in.SatisfiesPzs)
	out.SatisfiesPzi = direct.ValueOf(in.SatisfiesPzi)
	return out
}
func VertexAICustomJobSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.CustomJob) *krmvertexaiv1alpha1.VertexAICustomJobSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAICustomJobSpec{}
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	out.JobSpec = CustomJobSpec_v1alpha1_FromProto(mapCtx, in.GetJobSpec())
	out.Labels = in.Labels
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	// MISSING: WebAccessUris
	return out
}
func VertexAICustomJobSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAICustomJobSpec) *pb.CustomJob {
	if in == nil {
		return nil
	}
	out := &pb.CustomJob{}
	out.DisplayName = direct.ValueOf(in.DisplayName)
	out.JobSpec = CustomJobSpec_v1alpha1_ToProto(mapCtx, in.JobSpec)
	out.Labels = in.Labels
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	// MISSING: WebAccessUris
	return out
}
func VertexAIDataLabelingJobObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DataLabelingJob) *krmvertexaiv1alpha1.VertexAIDataLabelingJobObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIDataLabelingJobObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	// MISSING: Datasets
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	out.LabelingProgress = direct.LazyPtr(in.GetLabelingProgress())
	out.CurrentSpend = Money_v1alpha1_FromProto(mapCtx, in.GetCurrentSpend())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.Error = direct.Status_FromProto(mapCtx, in.GetError())
	return out
}
func VertexAIDataLabelingJobObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIDataLabelingJobObservedState) *pb.DataLabelingJob {
	if in == nil {
		return nil
	}
	out := &pb.DataLabelingJob{}
	out.Name = direct.ValueOf(in.Name)
	// MISSING: Datasets
	out.State = direct.Enum_ToProto[pb.JobState](mapCtx, in.State)
	out.LabelingProgress = direct.ValueOf(in.LabelingProgress)
	out.CurrentSpend = Money_v1alpha1_ToProto(mapCtx, in.CurrentSpend)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.Error = direct.Status_ToProto(mapCtx, in.Error)
	return out
}
func VertexAIDataLabelingJobSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DataLabelingJob) *krmvertexaiv1alpha1.VertexAIDataLabelingJobSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIDataLabelingJobSpec{}
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())

	if v := in.GetDatasets(); len(v) != 0 {
		for i := range v {
			out.DatasetRefs = append(out.DatasetRefs, krmvertexaiv1beta1.VertexAIDatasetRef{External: v[i]})
		}
	}

	out.AnnotationLabels = in.AnnotationLabels
	out.LabelerCount = direct.LazyPtr(in.GetLabelerCount())
	out.InstructionURI = direct.LazyPtr(in.GetInstructionUri())
	out.InputsSchemaURI = direct.LazyPtr(in.GetInputsSchemaUri())
	out.Inputs = JSON_v1alpha1_FromProto(mapCtx, in.GetInputs())
	out.Labels = in.Labels
	out.SpecialistPools = in.SpecialistPools
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	out.ActiveLearningConfig = ActiveLearningConfig_v1alpha1_FromProto(mapCtx, in.GetActiveLearningConfig())
	return out
}
func VertexAIDataLabelingJobSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIDataLabelingJobSpec) *pb.DataLabelingJob {
	if in == nil {
		return nil
	}
	out := &pb.DataLabelingJob{}
	out.DisplayName = direct.ValueOf(in.DisplayName)

	if v := in.DatasetRefs; len(v) != 0 {
		for i := range v {
			out.Datasets = append(out.Datasets, v[i].External)
		}
	}

	out.AnnotationLabels = in.AnnotationLabels
	out.LabelerCount = direct.ValueOf(in.LabelerCount)
	out.InstructionUri = direct.ValueOf(in.InstructionURI)
	out.InputsSchemaUri = direct.ValueOf(in.InputsSchemaURI)
	out.Inputs = JSON_v1alpha1_ToProto(mapCtx, in.Inputs)
	out.Labels = in.Labels
	out.SpecialistPools = in.SpecialistPools
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	out.ActiveLearningConfig = ActiveLearningConfig_v1alpha1_ToProto(mapCtx, in.ActiveLearningConfig)
	return out
}
func VertexAIDatasetObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Dataset) *krmvertexaiv1beta1.VertexAIDatasetObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.VertexAIDatasetObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	// MISSING: Description
	// MISSING: Metadata
	// MISSING: DataItemCount
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	// MISSING: UpdateTime
	// MISSING: Etag
	// MISSING: Labels
	// MISSING: SavedQueries
	// MISSING: MetadataArtifact
	// MISSING: ModelReference
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIDatasetObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.VertexAIDatasetObservedState) *pb.Dataset {
	if in == nil {
		return nil
	}
	out := &pb.Dataset{}
	out.Name = direct.ValueOf(in.Name)
	// MISSING: Description
	// MISSING: Metadata
	// MISSING: DataItemCount
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	// MISSING: UpdateTime
	// MISSING: Etag
	// MISSING: Labels
	// MISSING: SavedQueries
	// MISSING: MetadataArtifact
	// MISSING: ModelReference
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIDatasetSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.Dataset) *krmvertexaiv1beta1.VertexAIDatasetSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.VertexAIDatasetSpec{}
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	// MISSING: Description
	out.MetadataSchemaURI = direct.LazyPtr(in.GetMetadataSchemaUri())
	// MISSING: Metadata
	// MISSING: DataItemCount
	// MISSING: UpdateTime
	// MISSING: Etag
	// MISSING: Labels
	// MISSING: SavedQueries
	out.EncryptionSpec = DatasetEncryptionSpec_v1beta1_FromProto(mapCtx, in.GetEncryptionSpec())
	// MISSING: MetadataArtifact
	// MISSING: ModelReference
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIDatasetSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.VertexAIDatasetSpec) *pb.Dataset {
	if in == nil {
		return nil
	}
	out := &pb.Dataset{}
	out.DisplayName = direct.ValueOf(in.DisplayName)
	// MISSING: Description
	out.MetadataSchemaUri = direct.ValueOf(in.MetadataSchemaURI)
	// MISSING: Metadata
	// MISSING: DataItemCount
	// MISSING: UpdateTime
	// MISSING: Etag
	// MISSING: Labels
	// MISSING: SavedQueries
	out.EncryptionSpec = DatasetEncryptionSpec_v1beta1_ToProto(mapCtx, in.EncryptionSpec)
	// MISSING: MetadataArtifact
	// MISSING: ModelReference
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIDeploymentResourcePoolObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeploymentResourcePool) *krmvertexaiv1alpha1.VertexAIDeploymentResourcePoolObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIDeploymentResourcePoolObservedState{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.SatisfiesPzs = direct.LazyPtr(in.GetSatisfiesPzs())
	out.SatisfiesPzi = direct.LazyPtr(in.GetSatisfiesPzi())
	return out
}
func VertexAIDeploymentResourcePoolObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIDeploymentResourcePoolObservedState) *pb.DeploymentResourcePool {
	if in == nil {
		return nil
	}
	out := &pb.DeploymentResourcePool{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.SatisfiesPzs = direct.ValueOf(in.SatisfiesPzs)
	out.SatisfiesPzi = direct.ValueOf(in.SatisfiesPzi)
	return out
}
func VertexAIDeploymentResourcePoolSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.DeploymentResourcePool) *krmvertexaiv1alpha1.VertexAIDeploymentResourcePoolSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIDeploymentResourcePoolSpec{}
	// MISSING: Name
	out.DedicatedResources = DedicatedResources_v1alpha1_FromProto(mapCtx, in.GetDedicatedResources())
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	if in.GetServiceAccount() != "" {
		out.ServiceAccountRef = &refsv1beta1.IAMServiceAccountRef{External: in.GetServiceAccount()}
	}
	out.DisableContainerLogging = direct.LazyPtr(in.GetDisableContainerLogging())
	return out
}
func VertexAIDeploymentResourcePoolSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIDeploymentResourcePoolSpec) *pb.DeploymentResourcePool {
	if in == nil {
		return nil
	}
	out := &pb.DeploymentResourcePool{}
	// MISSING: Name
	out.DedicatedResources = DedicatedResources_v1alpha1_ToProto(mapCtx, in.DedicatedResources)
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	if in.ServiceAccountRef != nil {
		out.ServiceAccount = in.ServiceAccountRef.External
	}
	out.DisableContainerLogging = direct.ValueOf(in.DisableContainerLogging)
	return out
}
func VertexAIExampleStoreObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ExampleStore) *krmvertexaiv1alpha1.VertexAIExampleStoreObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIExampleStoreObservedState{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	return out
}
func VertexAIExampleStoreObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIExampleStoreObservedState) *pb.ExampleStore {
	if in == nil {
		return nil
	}
	out := &pb.ExampleStore{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	return out
}
func VertexAIExampleStoreSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.ExampleStore) *krmvertexaiv1alpha1.VertexAIExampleStoreSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIExampleStoreSpec{}
	// MISSING: Name
	out.DisplayName = in.GetDisplayName()
	out.Description = direct.LazyPtr(in.GetDescription())
	out.ExampleStoreConfig = ExampleStoreConfig_v1alpha1_FromProto(mapCtx, in.GetExampleStoreConfig())
	return out
}
func VertexAIExampleStoreSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIExampleStoreSpec) *pb.ExampleStore {
	if in == nil {
		return nil
	}
	out := &pb.ExampleStore{}
	// MISSING: Name
	out.DisplayName = VertexAIExampleStoreSpec_DisplayName_ToProto(mapCtx, in.DisplayName)
	out.Description = direct.ValueOf(in.Description)
	out.ExampleStoreConfig = ExampleStoreConfig_v1alpha1_ToProto(mapCtx, in.ExampleStoreConfig)
	return out
}
func VertexAIFeatureGroupObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.FeatureGroup) *krmvertexaiv1alpha1.VertexAIFeatureGroupObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIFeatureGroupObservedState{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	// MISSING: Etag
	out.ServiceAccountEmail = direct.LazyPtr(in.GetServiceAccountEmail())
	return out
}
func VertexAIFeatureGroupObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIFeatureGroupObservedState) *pb.FeatureGroup {
	if in == nil {
		return nil
	}
	out := &pb.FeatureGroup{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	// MISSING: Etag
	out.ServiceAccountEmail = direct.ValueOf(in.ServiceAccountEmail)
	return out
}
func VertexAIFeatureGroupSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.FeatureGroup) *krmvertexaiv1alpha1.VertexAIFeatureGroupSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIFeatureGroupSpec{}
	out.BigQuery = FeatureGroup_BigQuery_v1alpha1_FromProto(mapCtx, in.GetBigQuery())
	// MISSING: Name
	// MISSING: Etag
	out.Labels = in.Labels
	out.Description = direct.LazyPtr(in.GetDescription())
	out.ServiceAgentType = direct.Enum_FromProto(mapCtx, in.GetServiceAgentType())
	return out
}
func VertexAIFeatureGroupSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIFeatureGroupSpec) *pb.FeatureGroup {
	if in == nil {
		return nil
	}
	out := &pb.FeatureGroup{}
	if oneof := FeatureGroup_BigQuery_v1alpha1_ToProto(mapCtx, in.BigQuery); oneof != nil {
		out.Source = &pb.FeatureGroup_BigQuery_{BigQuery: oneof}
	}
	// MISSING: Name
	// MISSING: Etag
	out.Labels = in.Labels
	out.Description = direct.ValueOf(in.Description)
	out.ServiceAgentType = direct.Enum_ToProto[pb.FeatureGroup_ServiceAgentType](mapCtx, in.ServiceAgentType)
	return out
}
func VertexAIFeaturestoreObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Featurestore) *krmvertexaiv1alpha1.VertexAIFeaturestoreObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIFeaturestoreObservedState{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	// MISSING: Etag
	out.State = direct.Enum_FromProto(mapCtx, in.GetState())
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIFeaturestoreObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIFeaturestoreObservedState) *pb.Featurestore {
	if in == nil {
		return nil
	}
	out := &pb.Featurestore{}
	// MISSING: Name
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	// MISSING: Etag
	out.State = direct.Enum_ToProto[pb.Featurestore_State](mapCtx, in.State)
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIFeaturestoreSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Featurestore) *krmvertexaiv1alpha1.VertexAIFeaturestoreSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIFeaturestoreSpec{}
	// MISSING: Name
	// MISSING: Etag
	out.Labels = in.Labels
	out.OnlineServingConfig = Featurestore_OnlineServingConfig_v1alpha1_FromProto(mapCtx, in.GetOnlineServingConfig())
	out.OnlineStorageTTLDays = direct.LazyPtr(in.GetOnlineStorageTtlDays())
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIFeaturestoreSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIFeaturestoreSpec) *pb.Featurestore {
	if in == nil {
		return nil
	}
	out := &pb.Featurestore{}
	// MISSING: Name
	// MISSING: Etag
	out.Labels = in.Labels
	out.OnlineServingConfig = Featurestore_OnlineServingConfig_v1alpha1_ToProto(mapCtx, in.OnlineServingConfig)
	out.OnlineStorageTtlDays = direct.ValueOf(in.OnlineStorageTTLDays)
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	// MISSING: SatisfiesPzs
	// MISSING: SatisfiesPzi
	return out
}
func VertexAIMetadataStoreObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore) *krmvertexaiv1alpha1.VertexAIMetadataStoreObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIMetadataStoreObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.State = MetadataStore_MetadataStoreState_v1alpha1_FromProto(mapCtx, in.GetState())
	return out
}
func VertexAIMetadataStoreObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIMetadataStoreObservedState) *pb.MetadataStore {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore{}
	out.Name = direct.ValueOf(in.Name)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.State = MetadataStore_MetadataStoreState_v1alpha1_ToProto(mapCtx, in.State)
	return out
}
func VertexAIMetadataStoreObservedState_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore) *krmvertexaiv1beta1.VertexAIMetadataStoreObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.VertexAIMetadataStoreObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	out.State = MetadataStore_MetadataStoreState_v1beta1_FromProto(mapCtx, in.GetState())
	return out
}
func VertexAIMetadataStoreObservedState_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.VertexAIMetadataStoreObservedState) *pb.MetadataStore {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore{}
	out.Name = direct.ValueOf(in.Name)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	out.State = MetadataStore_MetadataStoreState_v1beta1_ToProto(mapCtx, in.State)
	return out
}
func VertexAIMetadataStoreSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore) *krmvertexaiv1alpha1.VertexAIMetadataStoreSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAIMetadataStoreSpec{}
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	out.Description = direct.LazyPtr(in.GetDescription())
	out.DataplexConfig = MetadataStore_DataplexConfig_v1alpha1_FromProto(mapCtx, in.GetDataplexConfig())
	return out
}
func VertexAIMetadataStoreSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAIMetadataStoreSpec) *pb.MetadataStore {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore{}
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	out.Description = direct.ValueOf(in.Description)
	out.DataplexConfig = MetadataStore_DataplexConfig_v1alpha1_ToProto(mapCtx, in.DataplexConfig)
	return out
}
func VertexAIMetadataStoreSpec_v1beta1_FromProto(mapCtx *direct.MapContext, in *pb.MetadataStore) *krmvertexaiv1beta1.VertexAIMetadataStoreSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1beta1.VertexAIMetadataStoreSpec{}
	out.EncryptionSpec = EncryptionSpec_v1beta1_FromProto(mapCtx, in.GetEncryptionSpec())
	out.Description = direct.LazyPtr(in.GetDescription())
	out.DataplexConfig = MetadataStore_DataplexConfig_v1beta1_FromProto(mapCtx, in.GetDataplexConfig())
	return out
}
func VertexAIMetadataStoreSpec_v1beta1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1beta1.VertexAIMetadataStoreSpec) *pb.MetadataStore {
	if in == nil {
		return nil
	}
	out := &pb.MetadataStore{}
	out.EncryptionSpec = EncryptionSpec_v1beta1_ToProto(mapCtx, in.EncryptionSpec)
	out.Description = direct.ValueOf(in.Description)
	out.DataplexConfig = MetadataStore_DataplexConfig_v1beta1_ToProto(mapCtx, in.DataplexConfig)
	return out
}
func VertexAITensorboardExperimentObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.TensorboardExperiment) *krmvertexaiv1alpha1.VertexAITensorboardExperimentObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAITensorboardExperimentObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	// MISSING: Etag
	return out
}
func VertexAITensorboardExperimentObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAITensorboardExperimentObservedState) *pb.TensorboardExperiment {
	if in == nil {
		return nil
	}
	out := &pb.TensorboardExperiment{}
	out.Name = direct.ValueOf(in.Name)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	// MISSING: Etag
	return out
}
func VertexAITensorboardExperimentSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.TensorboardExperiment) *krmvertexaiv1alpha1.VertexAITensorboardExperimentSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAITensorboardExperimentSpec{}
	out.DisplayName = direct.LazyPtr(in.GetDisplayName())
	out.Description = direct.LazyPtr(in.GetDescription())
	out.Labels = in.Labels
	// MISSING: Etag
	out.Source = direct.LazyPtr(in.GetSource())
	return out
}
func VertexAITensorboardExperimentSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAITensorboardExperimentSpec) *pb.TensorboardExperiment {
	if in == nil {
		return nil
	}
	out := &pb.TensorboardExperiment{}
	out.DisplayName = direct.ValueOf(in.DisplayName)
	out.Description = direct.ValueOf(in.Description)
	out.Labels = in.Labels
	// MISSING: Etag
	out.Source = direct.ValueOf(in.Source)
	return out
}
func VertexAITensorboardObservedState_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Tensorboard) *krmvertexaiv1alpha1.VertexAITensorboardObservedState {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAITensorboardObservedState{}
	out.Name = direct.LazyPtr(in.GetName())
	out.BlobStoragePathPrefix = direct.LazyPtr(in.GetBlobStoragePathPrefix())
	out.RunCount = direct.LazyPtr(in.GetRunCount())
	out.CreateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetCreateTime())
	out.UpdateTime = direct.StringTimestamp_FromProto(mapCtx, in.GetUpdateTime())
	// MISSING: Labels
	// MISSING: Etag
	out.SatisfiesPzs = direct.LazyPtr(in.GetSatisfiesPzs())
	out.SatisfiesPzi = direct.LazyPtr(in.GetSatisfiesPzi())
	return out
}
func VertexAITensorboardObservedState_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAITensorboardObservedState) *pb.Tensorboard {
	if in == nil {
		return nil
	}
	out := &pb.Tensorboard{}
	out.Name = direct.ValueOf(in.Name)
	out.BlobStoragePathPrefix = direct.ValueOf(in.BlobStoragePathPrefix)
	out.RunCount = direct.ValueOf(in.RunCount)
	out.CreateTime = direct.StringTimestamp_ToProto(mapCtx, in.CreateTime)
	out.UpdateTime = direct.StringTimestamp_ToProto(mapCtx, in.UpdateTime)
	// MISSING: Labels
	// MISSING: Etag
	out.SatisfiesPzs = direct.ValueOf(in.SatisfiesPzs)
	out.SatisfiesPzi = direct.ValueOf(in.SatisfiesPzi)
	return out
}
func VertexAITensorboardSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.Tensorboard) *krmvertexaiv1alpha1.VertexAITensorboardSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.VertexAITensorboardSpec{}
	out.DisplayName = in.GetDisplayName()
	out.Description = direct.LazyPtr(in.GetDescription())
	out.EncryptionSpec = EncryptionSpec_v1alpha1_FromProto(mapCtx, in.GetEncryptionSpec())
	// MISSING: Labels
	// MISSING: Etag
	out.IsDefault = direct.LazyPtr(in.GetIsDefault())
	return out
}
func VertexAITensorboardSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.VertexAITensorboardSpec) *pb.Tensorboard {
	if in == nil {
		return nil
	}
	out := &pb.Tensorboard{}
	out.DisplayName = VertexAITensorboardSpec_DisplayName_ToProto(mapCtx, in.DisplayName)
	out.Description = direct.ValueOf(in.Description)
	out.EncryptionSpec = EncryptionSpec_v1alpha1_ToProto(mapCtx, in.EncryptionSpec)
	// MISSING: Labels
	// MISSING: Etag
	out.IsDefault = direct.ValueOf(in.IsDefault)
	return out
}
func WorkerPoolSpec_v1alpha1_FromProto(mapCtx *direct.MapContext, in *pb.WorkerPoolSpec) *krmvertexaiv1alpha1.WorkerPoolSpec {
	if in == nil {
		return nil
	}
	out := &krmvertexaiv1alpha1.WorkerPoolSpec{}
	out.ContainerSpec = ContainerSpec_v1alpha1_FromProto(mapCtx, in.GetContainerSpec())
	out.PythonPackageSpec = PythonPackageSpec_v1alpha1_FromProto(mapCtx, in.GetPythonPackageSpec())
	out.MachineSpec = MachineSpec_v1alpha1_FromProto(mapCtx, in.GetMachineSpec())
	out.ReplicaCount = direct.LazyPtr(in.GetReplicaCount())
	out.NfsMounts = direct.Slice_FromProto(mapCtx, in.NfsMounts, NfsMount_v1alpha1_FromProto)
	out.DiskSpec = DiskSpec_v1alpha1_FromProto(mapCtx, in.GetDiskSpec())
	return out
}
func WorkerPoolSpec_v1alpha1_ToProto(mapCtx *direct.MapContext, in *krmvertexaiv1alpha1.WorkerPoolSpec) *pb.WorkerPoolSpec {
	if in == nil {
		return nil
	}
	out := &pb.WorkerPoolSpec{}
	if oneof := ContainerSpec_v1alpha1_ToProto(mapCtx, in.ContainerSpec); oneof != nil {
		out.Task = &pb.WorkerPoolSpec_ContainerSpec{ContainerSpec: oneof}
	}
	if oneof := PythonPackageSpec_v1alpha1_ToProto(mapCtx, in.PythonPackageSpec); oneof != nil {
		out.Task = &pb.WorkerPoolSpec_PythonPackageSpec{PythonPackageSpec: oneof}
	}
	out.MachineSpec = MachineSpec_v1alpha1_ToProto(mapCtx, in.MachineSpec)
	out.ReplicaCount = direct.ValueOf(in.ReplicaCount)
	out.NfsMounts = direct.Slice_ToProto(mapCtx, in.NfsMounts, NfsMount_v1alpha1_ToProto)
	out.DiskSpec = DiskSpec_v1alpha1_ToProto(mapCtx, in.DiskSpec)
	return out
}
