// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: batch.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.batch.v1alpha
// resource: CloudBatchResourceAllowance:ResourceAllowance

package v1alpha1

// +kcc:proto=google.cloud.batch.v1alpha.Notification
type Notification struct {
	// Required. The Pub/Sub topic where notifications like the resource allowance
	//  state changes will be published. The topic must exist in the same project
	//  as the job and billings will be charged to this project. If not specified,
	//  no Pub/Sub messages will be sent. Topic format:
	//  `projects/{project}/topics/{topic}`.
	// +kcc:proto:field=google.cloud.batch.v1alpha.Notification.pubsub_topic
	// +required
	PubsubTopic *string `json:"pubsubTopic,omitempty"`
}

/* unreachable type ResourceAllowance
// +kcc:proto=google.cloud.batch.v1alpha.ResourceAllowance
type ResourceAllowance struct {
	// The detail of usage resource allowance.
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.usage_resource_allowance
	UsageResourceAllowance *UsageResourceAllowance `json:"usageResourceAllowance,omitempty"`

	// Identifier. ResourceAllowance name.
	//  For example:
	//  "projects/123456/locations/us-central1/resourceAllowances/resource-allowance-1".
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.name
	Name *string `json:"name,omitempty"`

	// Optional. Labels are attributes that can be set and used by both the
	//  user and by Batch. Labels must meet the following constraints:
	//
	//  * Keys and values can contain only lowercase letters, numeric characters,
	//  underscores, and dashes.
	//  * All characters must use UTF-8 encoding, and international characters are
	//  allowed.
	//  * Keys must start with a lowercase letter or international character.
	//  * Each resource is limited to a maximum of 64 labels.
	//
	//  Both keys and values are additionally constrained to be <= 128 bytes.
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.labels
	Labels map[string]string `json:"labels,omitempty"`

	// Optional. Notification configurations.
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.notifications
	Notifications []Notification `json:"notifications,omitempty"`
}
*/

// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowance
type UsageResourceAllowance struct {
	// Required. Spec of a usage ResourceAllowance.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowance.spec
	// +required
	Spec *UsageResourceAllowanceSpec `json:"spec,omitempty"`
}

// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceSpec
type UsageResourceAllowanceSpec struct {
	// Required. Spec type is unique for each usage ResourceAllowance.
	//  Batch now only supports type as "cpu-core-hours" for CPU usage consumption
	//  tracking.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceSpec.type
	// +required
	Type *string `json:"type,omitempty"`

	// Required. Threshold of a UsageResourceAllowance limiting how many resources
	//  can be consumed for each type.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceSpec.limit
	// +required
	Limit *UsageResourceAllowanceSpec_Limit `json:"limit,omitempty"`
}

// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceSpec.Limit
type UsageResourceAllowanceSpec_Limit struct {
	// Optional. A CalendarPeriod represents the abstract concept of a time
	//  period that has a canonical start.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceSpec.Limit.calendar_period
	CalendarPeriod *string `json:"calendarPeriod,omitempty"`

	// Required. Limit value of a UsageResourceAllowance within its one
	//  duration.
	//
	//  Limit cannot be a negative value. Default is 0.
	//  For example, you can set `limit` as 10000.0 with duration of the current
	//  month by setting `calendar_period` field as monthly. That means in your
	//  current month, 10000.0 is the core hour limitation that your resources
	//  are allowed to consume.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceSpec.Limit.limit
	// +required
	Limit *float64 `json:"limit,omitempty"`
}

/* unreachable type UsageResourceAllowanceStatus
// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus
type UsageResourceAllowanceStatus struct {
}
*/

/* unreachable type UsageResourceAllowanceStatus_ConsumptionReport
// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.ConsumptionReport
type UsageResourceAllowanceStatus_ConsumptionReport struct {
}
*/

/* unreachable type UsageResourceAllowanceStatus_LimitStatus
// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.LimitStatus
type UsageResourceAllowanceStatus_LimitStatus struct {
}
*/

// +kcc:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.PeriodConsumption
type UsageResourceAllowanceStatus_PeriodConsumption struct {
}

// +kcc:proto=google.type.Interval
type Interval struct {
	// Optional. Inclusive start of the interval.
	//
	//  If specified, a Timestamp matching this interval will have to be the same
	//  or after the start.
	// +kcc:proto:field=google.type.Interval.start_time
	StartTime *string `json:"startTime,omitempty"`

	// Optional. Exclusive end of the interval.
	//
	//  If specified, a Timestamp matching this interval will have to be before the
	//  end.
	// +kcc:proto:field=google.type.Interval.end_time
	EndTime *string `json:"endTime,omitempty"`
}

/* unreachable type ResourceAllowanceObservedState
// +kcc:observedstate:proto=google.cloud.batch.v1alpha.ResourceAllowance
type ResourceAllowanceObservedState struct {
	// The detail of usage resource allowance.
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.usage_resource_allowance
	UsageResourceAllowance *UsageResourceAllowanceObservedState `json:"usageResourceAllowance,omitempty"`

	// Output only. A system generated unique ID (in UUID4 format) for the
	//  ResourceAllowance.
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.uid
	Uid *string `json:"uid,omitempty"`

	// Output only. Time when the ResourceAllowance was created.
	// +kcc:proto:field=google.cloud.batch.v1alpha.ResourceAllowance.create_time
	CreateTime *string `json:"createTime,omitempty"`
}
*/

// +kcc:observedstate:proto=google.cloud.batch.v1alpha.UsageResourceAllowance
type UsageResourceAllowanceObservedState struct {
	// Output only. Status of a usage ResourceAllowance.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowance.status
	Status *UsageResourceAllowanceStatusObservedState `json:"status,omitempty"`
}

// +kcc:observedstate:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus
type UsageResourceAllowanceStatusObservedState struct {
	// Output only. ResourceAllowance state.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.state
	State *string `json:"state,omitempty"`

	// Output only. ResourceAllowance consumption status for usage resources.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.limit_status
	LimitStatus *UsageResourceAllowanceStatus_LimitStatusObservedState `json:"limitStatus,omitempty"`

	// Output only. The report of ResourceAllowance consumptions in a time period.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.report
	Report *UsageResourceAllowanceStatus_ConsumptionReportObservedState `json:"report,omitempty"`
}

// +kcc:observedstate:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.ConsumptionReport
type UsageResourceAllowanceStatus_ConsumptionReportObservedState struct {
	// Output only. ResourceAllowance consumptions in the latest calendar
	//  period. Key is the calendar period in string format. Batch currently
	//  supports HOUR, DAY, MONTH and YEAR.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.ConsumptionReport.latest_period_consumptions
	LatestPeriodConsumptions map[string]UsageResourceAllowanceStatus_PeriodConsumption `json:"latestPeriodConsumptions,omitempty"`
}

// +kcc:observedstate:proto=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.LimitStatus
type UsageResourceAllowanceStatus_LimitStatusObservedState struct {
	// Output only. The consumption interval.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.LimitStatus.consumption_interval
	ConsumptionInterval *Interval `json:"consumptionInterval,omitempty"`

	// Output only. Limit value of a UsageResourceAllowance within its one
	//  duration.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.LimitStatus.limit
	Limit *float64 `json:"limit,omitempty"`

	// Output only. Accumulated consumption during `consumption_interval`.
	// +kcc:proto:field=google.cloud.batch.v1alpha.UsageResourceAllowanceStatus.LimitStatus.consumed
	Consumed *float64 `json:"consumed,omitempty"`
}
