//go:build !ignore_autogenerated

// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/apis/k8s/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaAdjusterSettings) DeepCopyInto(out *APIQuotaAdjusterSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaAdjusterSettings.
func (in *APIQuotaAdjusterSettings) DeepCopy() *APIQuotaAdjusterSettings {
	if in == nil {
		return nil
	}
	out := new(APIQuotaAdjusterSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIQuotaAdjusterSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaAdjusterSettingsList) DeepCopyInto(out *APIQuotaAdjusterSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIQuotaAdjusterSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaAdjusterSettingsList.
func (in *APIQuotaAdjusterSettingsList) DeepCopy() *APIQuotaAdjusterSettingsList {
	if in == nil {
		return nil
	}
	out := new(APIQuotaAdjusterSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIQuotaAdjusterSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaAdjusterSettingsObservedState) DeepCopyInto(out *APIQuotaAdjusterSettingsObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaAdjusterSettingsObservedState.
func (in *APIQuotaAdjusterSettingsObservedState) DeepCopy() *APIQuotaAdjusterSettingsObservedState {
	if in == nil {
		return nil
	}
	out := new(APIQuotaAdjusterSettingsObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaAdjusterSettingsSpec) DeepCopyInto(out *APIQuotaAdjusterSettingsSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(refsv1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaAdjusterSettingsSpec.
func (in *APIQuotaAdjusterSettingsSpec) DeepCopy() *APIQuotaAdjusterSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(APIQuotaAdjusterSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaAdjusterSettingsStatus) DeepCopyInto(out *APIQuotaAdjusterSettingsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(APIQuotaAdjusterSettingsObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaAdjusterSettingsStatus.
func (in *APIQuotaAdjusterSettingsStatus) DeepCopy() *APIQuotaAdjusterSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(APIQuotaAdjusterSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaPreference) DeepCopyInto(out *APIQuotaPreference) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaPreference.
func (in *APIQuotaPreference) DeepCopy() *APIQuotaPreference {
	if in == nil {
		return nil
	}
	out := new(APIQuotaPreference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIQuotaPreference) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaPreferenceList) DeepCopyInto(out *APIQuotaPreferenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIQuotaPreference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaPreferenceList.
func (in *APIQuotaPreferenceList) DeepCopy() *APIQuotaPreferenceList {
	if in == nil {
		return nil
	}
	out := new(APIQuotaPreferenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIQuotaPreferenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaPreferenceObservedState) DeepCopyInto(out *APIQuotaPreferenceObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaPreferenceObservedState.
func (in *APIQuotaPreferenceObservedState) DeepCopy() *APIQuotaPreferenceObservedState {
	if in == nil {
		return nil
	}
	out := new(APIQuotaPreferenceObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaPreferenceSpec) DeepCopyInto(out *APIQuotaPreferenceSpec) {
	*out = *in
	if in.ProjectRef != nil {
		in, out := &in.ProjectRef, &out.ProjectRef
		*out = new(refsv1beta1.ProjectRef)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaPreferenceSpec.
func (in *APIQuotaPreferenceSpec) DeepCopy() *APIQuotaPreferenceSpec {
	if in == nil {
		return nil
	}
	out := new(APIQuotaPreferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIQuotaPreferenceStatus) DeepCopyInto(out *APIQuotaPreferenceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1alpha1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ExternalRef != nil {
		in, out := &in.ExternalRef, &out.ExternalRef
		*out = new(string)
		**out = **in
	}
	if in.ObservedState != nil {
		in, out := &in.ObservedState, &out.ObservedState
		*out = new(APIQuotaPreferenceObservedState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIQuotaPreferenceStatus.
func (in *APIQuotaPreferenceStatus) DeepCopy() *APIQuotaPreferenceStatus {
	if in == nil {
		return nil
	}
	out := new(APIQuotaPreferenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaAdjusterSettingsIdentity) DeepCopyInto(out *QuotaAdjusterSettingsIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(QuotaAdjusterSettingsParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaAdjusterSettingsIdentity.
func (in *QuotaAdjusterSettingsIdentity) DeepCopy() *QuotaAdjusterSettingsIdentity {
	if in == nil {
		return nil
	}
	out := new(QuotaAdjusterSettingsIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaAdjusterSettingsParent) DeepCopyInto(out *QuotaAdjusterSettingsParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaAdjusterSettingsParent.
func (in *QuotaAdjusterSettingsParent) DeepCopy() *QuotaAdjusterSettingsParent {
	if in == nil {
		return nil
	}
	out := new(QuotaAdjusterSettingsParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaAdjusterSettingsRef) DeepCopyInto(out *QuotaAdjusterSettingsRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaAdjusterSettingsRef.
func (in *QuotaAdjusterSettingsRef) DeepCopy() *QuotaAdjusterSettingsRef {
	if in == nil {
		return nil
	}
	out := new(QuotaAdjusterSettingsRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPreferenceIdentity) DeepCopyInto(out *QuotaPreferenceIdentity) {
	*out = *in
	if in.parent != nil {
		in, out := &in.parent, &out.parent
		*out = new(QuotaPreferenceParent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPreferenceIdentity.
func (in *QuotaPreferenceIdentity) DeepCopy() *QuotaPreferenceIdentity {
	if in == nil {
		return nil
	}
	out := new(QuotaPreferenceIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPreferenceParent) DeepCopyInto(out *QuotaPreferenceParent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPreferenceParent.
func (in *QuotaPreferenceParent) DeepCopy() *QuotaPreferenceParent {
	if in == nil {
		return nil
	}
	out := new(QuotaPreferenceParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPreferenceRef) DeepCopyInto(out *QuotaPreferenceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPreferenceRef.
func (in *QuotaPreferenceRef) DeepCopy() *QuotaPreferenceRef {
	if in == nil {
		return nil
	}
	out := new(QuotaPreferenceRef)
	in.DeepCopyInto(out)
	return out
}
