// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: datalineage.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.datacatalog.lineage.v1
// resource: DataLineageProcess:Process

package v1alpha1

// +kcc:proto=google.cloud.datacatalog.lineage.v1.Origin
type Origin struct {
	// Type of the source.
	//
	//  Use of a source_type other than `CUSTOM` for process creation
	//  or updating is highly discouraged, and may be restricted in the future
	//  without notice.
	// +kcc:proto:field=google.cloud.datacatalog.lineage.v1.Origin.source_type
	SourceType *string `json:"sourceType,omitempty"`

	// If the source_type isn't CUSTOM, the value of this field should be a GCP
	//  resource name of the system, which reports lineage. The project and
	//  location parts of the resource name must match the project and location of
	//  the lineage resource being created. Examples:
	//
	//  - `{source_type: COMPOSER, name:
	//    "projects/foo/locations/us/environments/bar"}`
	//  - `{source_type: BIGQUERY, name: "projects/foo/locations/eu"}`
	//  - `{source_type: CUSTOM,   name: "myCustomIntegration"}`
	// +kcc:proto:field=google.cloud.datacatalog.lineage.v1.Origin.name
	Name *string `json:"name,omitempty"`
}

/* unreachable type Process
// +kcc:proto=google.cloud.datacatalog.lineage.v1.Process
type Process struct {
	// Immutable. The resource name of the lineage process. Format:
	//  `projects/{project}/locations/{location}/processes/{process}`.
	//  Can be specified or auto-assigned.
	//  {process} must be not longer than 200 characters and only
	//  contain characters in a set: `a-zA-Z0-9_-:.`
	// +kcc:proto:field=google.cloud.datacatalog.lineage.v1.Process.name
	Name *string `json:"name,omitempty"`

	// Optional. A human-readable name you can set to display in a user interface.
	//  Must be not longer than 200 characters and only contain UTF-8 letters
	//  or numbers, spaces or characters like `_-:&.`
	// +kcc:proto:field=google.cloud.datacatalog.lineage.v1.Process.display_name
	DisplayName *string `json:"displayName,omitempty"`

	// Optional. The attributes of the process. Should only be used for the
	//  purpose of non-semantic management (classifying, describing or labeling the
	//  process).
	//
	//  Up to 100 attributes are allowed.
	// +kcc:proto:field=google.cloud.datacatalog.lineage.v1.Process.attributes
	Attributes map[string]apiextensionsv1.JSON `json:"attributes,omitempty"`

	// Optional. The origin of this process and its runs and lineage events.
	// +kcc:proto:field=google.cloud.datacatalog.lineage.v1.Process.origin
	Origin *Origin `json:"origin,omitempty"`
}
*/
